// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrixmul_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrixmul_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrixmul_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<22> matrixmul_1::ap_ST_fsm_state1 = "1";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state2 = "10";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state3 = "100";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state4 = "1000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state5 = "10000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state6 = "100000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state8 = "10000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state9 = "100000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<22> matrixmul_1::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<1> matrixmul_1::ap_const_lv1_0 = "0";
const sc_lv<1> matrixmul_1::ap_const_lv1_1 = "1";
const sc_lv<2> matrixmul_1::ap_const_lv2_0 = "00";
const sc_lv<2> matrixmul_1::ap_const_lv2_2 = "10";
const sc_lv<2> matrixmul_1::ap_const_lv2_3 = "11";
const sc_lv<2> matrixmul_1::ap_const_lv2_1 = "1";
const sc_lv<32> matrixmul_1::ap_const_lv32_2 = "10";
const sc_lv<32> matrixmul_1::ap_const_lv32_4 = "100";
const sc_lv<32> matrixmul_1::ap_const_lv32_14 = "10100";
const sc_lv<32> matrixmul_1::ap_const_lv32_15 = "10101";
const sc_lv<32> matrixmul_1::ap_const_lv32_1 = "1";
const sc_lv<32> matrixmul_1::ap_const_lv32_3 = "11";
const sc_lv<32> matrixmul_1::ap_const_lv32_5 = "101";
const sc_lv<32> matrixmul_1::ap_const_lv32_6 = "110";
const sc_lv<32> matrixmul_1::ap_const_lv32_7 = "111";
const sc_lv<32> matrixmul_1::ap_const_lv32_8 = "1000";
const sc_lv<32> matrixmul_1::ap_const_lv32_C = "1100";
const sc_lv<32> matrixmul_1::ap_const_lv32_11 = "10001";
const sc_lv<32> matrixmul_1::ap_const_lv32_12 = "10010";
const sc_lv<32> matrixmul_1::ap_const_lv32_13 = "10011";
const sc_lv<4> matrixmul_1::ap_const_lv4_0 = "0000";
const sc_lv<32> matrixmul_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrixmul_1::ap_const_lv32_D = "1101";
const sc_lv<32> matrixmul_1::ap_const_lv32_9 = "1001";
const sc_lv<4> matrixmul_1::ap_const_lv4_8 = "1000";
const sc_lv<4> matrixmul_1::ap_const_lv4_1 = "1";
const sc_lv<3> matrixmul_1::ap_const_lv3_0 = "000";
const sc_lv<4> matrixmul_1::ap_const_lv4_7 = "111";
const bool matrixmul_1::ap_const_boolean_1 = true;

matrixmul_1::matrixmul_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    input_A_U = new matrixmul_1_input_A("input_A_U");
    input_A_U->clk(ap_clk);
    input_A_U->reset(ap_rst_n_inv);
    input_A_U->address0(input_A_address0);
    input_A_U->ce0(input_A_ce0);
    input_A_U->we0(input_A_we0);
    input_A_U->d0(in_A_V_data_0_data_out);
    input_A_U->q0(input_A_q0);
    input_B_U = new matrixmul_1_input_A("input_B_U");
    input_B_U->clk(ap_clk);
    input_B_U->reset(ap_rst_n_inv);
    input_B_U->address0(input_B_address0);
    input_B_U->ce0(input_B_ce0);
    input_B_U->we0(input_B_we0);
    input_B_U->d0(in_A_V_data_0_data_out);
    input_B_U->q0(input_B_q0);
    output_C_U = new matrixmul_1_input_A("output_C_U");
    output_C_U->clk(ap_clk);
    output_C_U->reset(ap_rst_n_inv);
    output_C_U->address0(output_C_address0);
    output_C_U->ce0(output_C_ce0);
    output_C_U->we0(output_C_we0);
    output_C_U->d0(res_0_reg_242);
    output_C_U->q0(output_C_q0);
    matrixmul_1_fadd_cud_U1 = new matrixmul_1_fadd_cud<1,5,32,32,32>("matrixmul_1_fadd_cud_U1");
    matrixmul_1_fadd_cud_U1->clk(ap_clk);
    matrixmul_1_fadd_cud_U1->reset(ap_rst_n_inv);
    matrixmul_1_fadd_cud_U1->din0(res_0_reg_242);
    matrixmul_1_fadd_cud_U1->din1(tmp_3_reg_659);
    matrixmul_1_fadd_cud_U1->ce(ap_var_for_const0);
    matrixmul_1_fadd_cud_U1->dout(grp_fu_277_p2);
    matrixmul_1_fmul_dEe_U2 = new matrixmul_1_fmul_dEe<1,4,32,32,32>("matrixmul_1_fmul_dEe_U2");
    matrixmul_1_fmul_dEe_U2->clk(ap_clk);
    matrixmul_1_fmul_dEe_U2->reset(ap_rst_n_inv);
    matrixmul_1_fmul_dEe_U2->din0(input_A_load_reg_649);
    matrixmul_1_fmul_dEe_U2->din1(input_B_load_reg_654);
    matrixmul_1_fmul_dEe_U2->ce(ap_var_for_const0);
    matrixmul_1_fmul_dEe_U2->dout(grp_fu_282_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln23_fu_332_p2);
    sensitive << ( zext_ln20_reg_565 );
    sensitive << ( zext_ln23_fu_328_p1 );

    SC_METHOD(thread_add_ln32_fu_382_p2);
    sensitive << ( zext_ln29_reg_586 );
    sensitive << ( zext_ln32_fu_378_p1 );

    SC_METHOD(thread_add_ln41_1_fu_480_p2);
    sensitive << ( zext_ln43_reg_621 );
    sensitive << ( zext_ln41_2_fu_476_p1 );

    SC_METHOD(thread_add_ln41_fu_458_p2);
    sensitive << ( zext_ln38_reg_607 );
    sensitive << ( zext_ln41_fu_454_p1 );

    SC_METHOD(thread_add_ln43_fu_432_p2);
    sensitive << ( zext_ln38_reg_607 );
    sensitive << ( zext_ln43_fu_428_p1 );

    SC_METHOD(thread_add_ln50_fu_536_p2);
    sensitive << ( zext_ln52_reg_677 );
    sensitive << ( zext_ln50_fu_532_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state19);
    sensitive << ( out_C_TREADY );
    sensitive << ( out_C_V_data_1_state );
    sensitive << ( out_C_V_last_V_1_state );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( icmp_ln20_fu_316_p2 );

    SC_METHOD(thread_ap_block_state5);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( icmp_ln29_fu_366_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_col_4_fu_372_p2);
    sensitive << ( col_1_reg_198 );

    SC_METHOD(thread_col_5_fu_526_p2);
    sensitive << ( col_3_reg_266 );

    SC_METHOD(thread_col_6_fu_422_p2);
    sensitive << ( col_2_reg_220 );

    SC_METHOD(thread_col_fu_322_p2);
    sensitive << ( col_0_reg_176 );

    SC_METHOD(thread_icmp_ln18_fu_292_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_0_reg_165 );

    SC_METHOD(thread_icmp_ln20_fu_316_p2);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln20_fu_316_p2 );
    sensitive << ( col_0_reg_176 );

    SC_METHOD(thread_icmp_ln27_fu_342_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( row_1_reg_187 );

    SC_METHOD(thread_icmp_ln29_fu_366_p2);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln29_fu_366_p2 );
    sensitive << ( col_1_reg_198 );

    SC_METHOD(thread_icmp_ln37_fu_392_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( row_2_reg_209 );

    SC_METHOD(thread_icmp_ln38_fu_416_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( col_2_reg_220 );

    SC_METHOD(thread_icmp_ln40_fu_442_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( index_0_reg_231 );

    SC_METHOD(thread_icmp_ln48_fu_490_p2);
    sensitive << ( out_C_TREADY );
    sensitive << ( out_C_V_data_1_state );
    sensitive << ( out_C_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( row_3_reg_255 );

    SC_METHOD(thread_icmp_ln49_fu_520_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( col_3_reg_266 );

    SC_METHOD(thread_icmp_ln52_1_fu_546_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln49_fu_520_p2 );
    sensitive << ( col_3_reg_266 );

    SC_METHOD(thread_icmp_ln52_fu_514_p2);
    sensitive << ( out_C_TREADY );
    sensitive << ( out_C_V_data_1_state );
    sensitive << ( out_C_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( icmp_ln48_fu_490_p2 );
    sensitive << ( row_3_reg_255 );

    SC_METHOD(thread_in_A_TDATA_blk_n);
    sensitive << ( in_A_V_data_0_state );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln20_fu_316_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln29_fu_366_p2 );

    SC_METHOD(thread_in_A_TREADY);
    sensitive << ( in_A_V_last_V_0_state );

    SC_METHOD(thread_in_A_V_data_0_ack_in);
    sensitive << ( in_A_V_data_0_state );

    SC_METHOD(thread_in_A_V_data_0_ack_out);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln20_fu_316_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln29_fu_366_p2 );

    SC_METHOD(thread_in_A_V_data_0_data_out);
    sensitive << ( in_A_V_data_0_payload_A );
    sensitive << ( in_A_V_data_0_payload_B );
    sensitive << ( in_A_V_data_0_sel );

    SC_METHOD(thread_in_A_V_data_0_load_A);
    sensitive << ( in_A_V_data_0_sel_wr );
    sensitive << ( in_A_V_data_0_state_cmp_full );

    SC_METHOD(thread_in_A_V_data_0_load_B);
    sensitive << ( in_A_V_data_0_sel_wr );
    sensitive << ( in_A_V_data_0_state_cmp_full );

    SC_METHOD(thread_in_A_V_data_0_sel);
    sensitive << ( in_A_V_data_0_sel_rd );

    SC_METHOD(thread_in_A_V_data_0_state_cmp_full);
    sensitive << ( in_A_V_data_0_state );

    SC_METHOD(thread_in_A_V_data_0_vld_in);
    sensitive << ( in_A_TVALID );

    SC_METHOD(thread_in_A_V_data_0_vld_out);
    sensitive << ( in_A_V_data_0_state );

    SC_METHOD(thread_in_A_V_last_V_0_ack_out);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln20_fu_316_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln29_fu_366_p2 );

    SC_METHOD(thread_in_A_V_last_V_0_vld_in);
    sensitive << ( in_A_TVALID );

    SC_METHOD(thread_index_fu_448_p2);
    sensitive << ( index_0_reg_231 );

    SC_METHOD(thread_input_A_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln23_1_fu_337_p1 );
    sensitive << ( zext_ln41_1_fu_463_p1 );

    SC_METHOD(thread_input_A_ce0);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln20_fu_316_p2 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_input_A_we0);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln20_fu_316_p2 );

    SC_METHOD(thread_input_B_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln32_1_fu_387_p1 );
    sensitive << ( zext_ln41_3_fu_485_p1 );

    SC_METHOD(thread_input_B_ce0);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln29_fu_366_p2 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_input_B_we0);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln29_fu_366_p2 );

    SC_METHOD(thread_out_C_TDATA);
    sensitive << ( out_C_V_data_1_data_out );

    SC_METHOD(thread_out_C_TDATA_blk_n);
    sensitive << ( out_C_V_data_1_state );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_out_C_TLAST);
    sensitive << ( out_C_V_last_V_1_data_out );

    SC_METHOD(thread_out_C_TVALID);
    sensitive << ( out_C_V_last_V_1_state );

    SC_METHOD(thread_out_C_V_data_1_ack_in);
    sensitive << ( out_C_V_data_1_state );

    SC_METHOD(thread_out_C_V_data_1_ack_out);
    sensitive << ( out_C_TREADY );

    SC_METHOD(thread_out_C_V_data_1_data_out);
    sensitive << ( out_C_V_data_1_payload_A );
    sensitive << ( out_C_V_data_1_payload_B );
    sensitive << ( out_C_V_data_1_sel );

    SC_METHOD(thread_out_C_V_data_1_load_A);
    sensitive << ( out_C_V_data_1_sel_wr );
    sensitive << ( out_C_V_data_1_state_cmp_full );

    SC_METHOD(thread_out_C_V_data_1_load_B);
    sensitive << ( out_C_V_data_1_sel_wr );
    sensitive << ( out_C_V_data_1_state_cmp_full );

    SC_METHOD(thread_out_C_V_data_1_sel);
    sensitive << ( out_C_V_data_1_sel_rd );

    SC_METHOD(thread_out_C_V_data_1_state_cmp_full);
    sensitive << ( out_C_V_data_1_state );

    SC_METHOD(thread_out_C_V_data_1_vld_in);
    sensitive << ( out_C_V_data_1_ack_in );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_out_C_V_data_1_vld_out);
    sensitive << ( out_C_V_data_1_state );

    SC_METHOD(thread_out_C_V_last_V_1_ack_in);
    sensitive << ( out_C_V_last_V_1_state );

    SC_METHOD(thread_out_C_V_last_V_1_ack_out);
    sensitive << ( out_C_TREADY );

    SC_METHOD(thread_out_C_V_last_V_1_data_out);
    sensitive << ( out_C_V_last_V_1_payload_A );
    sensitive << ( out_C_V_last_V_1_payload_B );
    sensitive << ( out_C_V_last_V_1_sel );

    SC_METHOD(thread_out_C_V_last_V_1_load_A);
    sensitive << ( out_C_V_last_V_1_sel_wr );
    sensitive << ( out_C_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_out_C_V_last_V_1_load_B);
    sensitive << ( out_C_V_last_V_1_sel_wr );
    sensitive << ( out_C_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_out_C_V_last_V_1_sel);
    sensitive << ( out_C_V_last_V_1_sel_rd );

    SC_METHOD(thread_out_C_V_last_V_1_state_cmp_full);
    sensitive << ( out_C_V_last_V_1_state );

    SC_METHOD(thread_out_C_V_last_V_1_vld_in);
    sensitive << ( out_C_V_data_1_ack_in );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_out_C_V_last_V_1_vld_out);
    sensitive << ( out_C_V_last_V_1_state );

    SC_METHOD(thread_output_C_address0);
    sensitive << ( output_C_addr_1_reg_626 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( zext_ln50_1_fu_541_p1 );

    SC_METHOD(thread_output_C_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_output_C_we0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln40_fu_442_p2 );

    SC_METHOD(thread_row_4_fu_348_p2);
    sensitive << ( row_1_reg_187 );

    SC_METHOD(thread_row_5_fu_398_p2);
    sensitive << ( row_2_reg_209 );

    SC_METHOD(thread_row_6_fu_496_p2);
    sensitive << ( row_3_reg_255 );

    SC_METHOD(thread_row_fu_298_p2);
    sensitive << ( row_0_reg_165 );

    SC_METHOD(thread_tmp_6_fu_304_p3);
    sensitive << ( row_0_reg_165 );

    SC_METHOD(thread_tmp_7_fu_354_p3);
    sensitive << ( row_1_reg_187 );

    SC_METHOD(thread_tmp_8_fu_404_p3);
    sensitive << ( row_2_reg_209 );

    SC_METHOD(thread_tmp_9_fu_502_p3);
    sensitive << ( row_3_reg_255 );

    SC_METHOD(thread_tmp_last_V_fu_552_p2);
    sensitive << ( icmp_ln52_reg_682 );
    sensitive << ( icmp_ln52_1_fu_546_p2 );

    SC_METHOD(thread_tmp_s_fu_468_p3);
    sensitive << ( index_0_reg_231 );

    SC_METHOD(thread_zext_ln20_fu_312_p1);
    sensitive << ( tmp_6_fu_304_p3 );

    SC_METHOD(thread_zext_ln23_1_fu_337_p1);
    sensitive << ( add_ln23_fu_332_p2 );

    SC_METHOD(thread_zext_ln23_fu_328_p1);
    sensitive << ( col_0_reg_176 );

    SC_METHOD(thread_zext_ln29_fu_362_p1);
    sensitive << ( tmp_7_fu_354_p3 );

    SC_METHOD(thread_zext_ln32_1_fu_387_p1);
    sensitive << ( add_ln32_fu_382_p2 );

    SC_METHOD(thread_zext_ln32_fu_378_p1);
    sensitive << ( col_1_reg_198 );

    SC_METHOD(thread_zext_ln38_fu_412_p1);
    sensitive << ( tmp_8_fu_404_p3 );

    SC_METHOD(thread_zext_ln41_1_fu_463_p1);
    sensitive << ( add_ln41_fu_458_p2 );

    SC_METHOD(thread_zext_ln41_2_fu_476_p1);
    sensitive << ( tmp_s_fu_468_p3 );

    SC_METHOD(thread_zext_ln41_3_fu_485_p1);
    sensitive << ( add_ln41_1_fu_480_p2 );

    SC_METHOD(thread_zext_ln41_fu_454_p1);
    sensitive << ( index_0_reg_231 );

    SC_METHOD(thread_zext_ln43_1_fu_437_p1);
    sensitive << ( add_ln43_fu_432_p2 );

    SC_METHOD(thread_zext_ln43_fu_428_p1);
    sensitive << ( col_2_reg_220 );

    SC_METHOD(thread_zext_ln50_1_fu_541_p1);
    sensitive << ( add_ln50_fu_536_p2 );

    SC_METHOD(thread_zext_ln50_fu_532_p1);
    sensitive << ( col_3_reg_266 );

    SC_METHOD(thread_zext_ln52_fu_510_p1);
    sensitive << ( tmp_9_fu_502_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( in_A_V_data_0_vld_out );
    sensitive << ( out_C_TREADY );
    sensitive << ( out_C_V_data_1_ack_in );
    sensitive << ( out_C_V_data_1_state );
    sensitive << ( out_C_V_last_V_1_state );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln20_fu_316_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln29_fu_366_p2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_292_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln27_fu_342_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln37_fu_392_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln38_fu_416_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln40_fu_442_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( icmp_ln48_fu_490_p2 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln49_fu_520_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    in_A_V_data_0_sel_rd = SC_LOGIC_0;
    in_A_V_data_0_sel_wr = SC_LOGIC_0;
    in_A_V_data_0_state = "00";
    in_A_V_last_V_0_state = "00";
    out_C_V_data_1_sel_rd = SC_LOGIC_0;
    out_C_V_data_1_sel_wr = SC_LOGIC_0;
    out_C_V_data_1_state = "00";
    out_C_V_last_V_1_sel_rd = SC_LOGIC_0;
    out_C_V_last_V_1_sel_wr = SC_LOGIC_0;
    out_C_V_last_V_1_state = "00";
    ap_CS_fsm = "0000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrixmul_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, in_A_TDATA, "(port)in_A_TDATA");
    sc_trace(mVcdFile, in_A_TVALID, "(port)in_A_TVALID");
    sc_trace(mVcdFile, in_A_TREADY, "(port)in_A_TREADY");
    sc_trace(mVcdFile, in_A_TLAST, "(port)in_A_TLAST");
    sc_trace(mVcdFile, out_C_TDATA, "(port)out_C_TDATA");
    sc_trace(mVcdFile, out_C_TVALID, "(port)out_C_TVALID");
    sc_trace(mVcdFile, out_C_TREADY, "(port)out_C_TREADY");
    sc_trace(mVcdFile, out_C_TLAST, "(port)out_C_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, in_A_V_data_0_data_out, "in_A_V_data_0_data_out");
    sc_trace(mVcdFile, in_A_V_data_0_vld_in, "in_A_V_data_0_vld_in");
    sc_trace(mVcdFile, in_A_V_data_0_vld_out, "in_A_V_data_0_vld_out");
    sc_trace(mVcdFile, in_A_V_data_0_ack_in, "in_A_V_data_0_ack_in");
    sc_trace(mVcdFile, in_A_V_data_0_ack_out, "in_A_V_data_0_ack_out");
    sc_trace(mVcdFile, in_A_V_data_0_payload_A, "in_A_V_data_0_payload_A");
    sc_trace(mVcdFile, in_A_V_data_0_payload_B, "in_A_V_data_0_payload_B");
    sc_trace(mVcdFile, in_A_V_data_0_sel_rd, "in_A_V_data_0_sel_rd");
    sc_trace(mVcdFile, in_A_V_data_0_sel_wr, "in_A_V_data_0_sel_wr");
    sc_trace(mVcdFile, in_A_V_data_0_sel, "in_A_V_data_0_sel");
    sc_trace(mVcdFile, in_A_V_data_0_load_A, "in_A_V_data_0_load_A");
    sc_trace(mVcdFile, in_A_V_data_0_load_B, "in_A_V_data_0_load_B");
    sc_trace(mVcdFile, in_A_V_data_0_state, "in_A_V_data_0_state");
    sc_trace(mVcdFile, in_A_V_data_0_state_cmp_full, "in_A_V_data_0_state_cmp_full");
    sc_trace(mVcdFile, in_A_V_last_V_0_vld_in, "in_A_V_last_V_0_vld_in");
    sc_trace(mVcdFile, in_A_V_last_V_0_ack_out, "in_A_V_last_V_0_ack_out");
    sc_trace(mVcdFile, in_A_V_last_V_0_state, "in_A_V_last_V_0_state");
    sc_trace(mVcdFile, out_C_V_data_1_data_out, "out_C_V_data_1_data_out");
    sc_trace(mVcdFile, out_C_V_data_1_vld_in, "out_C_V_data_1_vld_in");
    sc_trace(mVcdFile, out_C_V_data_1_vld_out, "out_C_V_data_1_vld_out");
    sc_trace(mVcdFile, out_C_V_data_1_ack_in, "out_C_V_data_1_ack_in");
    sc_trace(mVcdFile, out_C_V_data_1_ack_out, "out_C_V_data_1_ack_out");
    sc_trace(mVcdFile, out_C_V_data_1_payload_A, "out_C_V_data_1_payload_A");
    sc_trace(mVcdFile, out_C_V_data_1_payload_B, "out_C_V_data_1_payload_B");
    sc_trace(mVcdFile, out_C_V_data_1_sel_rd, "out_C_V_data_1_sel_rd");
    sc_trace(mVcdFile, out_C_V_data_1_sel_wr, "out_C_V_data_1_sel_wr");
    sc_trace(mVcdFile, out_C_V_data_1_sel, "out_C_V_data_1_sel");
    sc_trace(mVcdFile, out_C_V_data_1_load_A, "out_C_V_data_1_load_A");
    sc_trace(mVcdFile, out_C_V_data_1_load_B, "out_C_V_data_1_load_B");
    sc_trace(mVcdFile, out_C_V_data_1_state, "out_C_V_data_1_state");
    sc_trace(mVcdFile, out_C_V_data_1_state_cmp_full, "out_C_V_data_1_state_cmp_full");
    sc_trace(mVcdFile, out_C_V_last_V_1_data_out, "out_C_V_last_V_1_data_out");
    sc_trace(mVcdFile, out_C_V_last_V_1_vld_in, "out_C_V_last_V_1_vld_in");
    sc_trace(mVcdFile, out_C_V_last_V_1_vld_out, "out_C_V_last_V_1_vld_out");
    sc_trace(mVcdFile, out_C_V_last_V_1_ack_in, "out_C_V_last_V_1_ack_in");
    sc_trace(mVcdFile, out_C_V_last_V_1_ack_out, "out_C_V_last_V_1_ack_out");
    sc_trace(mVcdFile, out_C_V_last_V_1_payload_A, "out_C_V_last_V_1_payload_A");
    sc_trace(mVcdFile, out_C_V_last_V_1_payload_B, "out_C_V_last_V_1_payload_B");
    sc_trace(mVcdFile, out_C_V_last_V_1_sel_rd, "out_C_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, out_C_V_last_V_1_sel_wr, "out_C_V_last_V_1_sel_wr");
    sc_trace(mVcdFile, out_C_V_last_V_1_sel, "out_C_V_last_V_1_sel");
    sc_trace(mVcdFile, out_C_V_last_V_1_load_A, "out_C_V_last_V_1_load_A");
    sc_trace(mVcdFile, out_C_V_last_V_1_load_B, "out_C_V_last_V_1_load_B");
    sc_trace(mVcdFile, out_C_V_last_V_1_state, "out_C_V_last_V_1_state");
    sc_trace(mVcdFile, out_C_V_last_V_1_state_cmp_full, "out_C_V_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, in_A_TDATA_blk_n, "in_A_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln20_fu_316_p2, "icmp_ln20_fu_316_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln29_fu_366_p2, "icmp_ln29_fu_366_p2");
    sc_trace(mVcdFile, out_C_TDATA_blk_n, "out_C_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, row_fu_298_p2, "row_fu_298_p2");
    sc_trace(mVcdFile, row_reg_560, "row_reg_560");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln20_fu_312_p1, "zext_ln20_fu_312_p1");
    sc_trace(mVcdFile, zext_ln20_reg_565, "zext_ln20_reg_565");
    sc_trace(mVcdFile, icmp_ln18_fu_292_p2, "icmp_ln18_fu_292_p2");
    sc_trace(mVcdFile, col_fu_322_p2, "col_fu_322_p2");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, row_4_fu_348_p2, "row_4_fu_348_p2");
    sc_trace(mVcdFile, row_4_reg_581, "row_4_reg_581");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln29_fu_362_p1, "zext_ln29_fu_362_p1");
    sc_trace(mVcdFile, zext_ln29_reg_586, "zext_ln29_reg_586");
    sc_trace(mVcdFile, icmp_ln27_fu_342_p2, "icmp_ln27_fu_342_p2");
    sc_trace(mVcdFile, col_4_fu_372_p2, "col_4_fu_372_p2");
    sc_trace(mVcdFile, ap_block_state5, "ap_block_state5");
    sc_trace(mVcdFile, row_5_fu_398_p2, "row_5_fu_398_p2");
    sc_trace(mVcdFile, row_5_reg_602, "row_5_reg_602");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln38_fu_412_p1, "zext_ln38_fu_412_p1");
    sc_trace(mVcdFile, zext_ln38_reg_607, "zext_ln38_reg_607");
    sc_trace(mVcdFile, icmp_ln37_fu_392_p2, "icmp_ln37_fu_392_p2");
    sc_trace(mVcdFile, col_6_fu_422_p2, "col_6_fu_422_p2");
    sc_trace(mVcdFile, col_6_reg_616, "col_6_reg_616");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, zext_ln43_fu_428_p1, "zext_ln43_fu_428_p1");
    sc_trace(mVcdFile, zext_ln43_reg_621, "zext_ln43_reg_621");
    sc_trace(mVcdFile, icmp_ln38_fu_416_p2, "icmp_ln38_fu_416_p2");
    sc_trace(mVcdFile, output_C_addr_1_reg_626, "output_C_addr_1_reg_626");
    sc_trace(mVcdFile, index_fu_448_p2, "index_fu_448_p2");
    sc_trace(mVcdFile, index_reg_634, "index_reg_634");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln40_fu_442_p2, "icmp_ln40_fu_442_p2");
    sc_trace(mVcdFile, input_A_q0, "input_A_q0");
    sc_trace(mVcdFile, input_A_load_reg_649, "input_A_load_reg_649");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, input_B_q0, "input_B_q0");
    sc_trace(mVcdFile, input_B_load_reg_654, "input_B_load_reg_654");
    sc_trace(mVcdFile, grp_fu_282_p2, "grp_fu_282_p2");
    sc_trace(mVcdFile, tmp_3_reg_659, "tmp_3_reg_659");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_fu_277_p2, "grp_fu_277_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, row_6_fu_496_p2, "row_6_fu_496_p2");
    sc_trace(mVcdFile, row_6_reg_672, "row_6_reg_672");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_block_state19, "ap_block_state19");
    sc_trace(mVcdFile, zext_ln52_fu_510_p1, "zext_ln52_fu_510_p1");
    sc_trace(mVcdFile, zext_ln52_reg_677, "zext_ln52_reg_677");
    sc_trace(mVcdFile, icmp_ln48_fu_490_p2, "icmp_ln48_fu_490_p2");
    sc_trace(mVcdFile, icmp_ln52_fu_514_p2, "icmp_ln52_fu_514_p2");
    sc_trace(mVcdFile, icmp_ln52_reg_682, "icmp_ln52_reg_682");
    sc_trace(mVcdFile, col_5_fu_526_p2, "col_5_fu_526_p2");
    sc_trace(mVcdFile, col_5_reg_690, "col_5_reg_690");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, icmp_ln49_fu_520_p2, "icmp_ln49_fu_520_p2");
    sc_trace(mVcdFile, tmp_last_V_fu_552_p2, "tmp_last_V_fu_552_p2");
    sc_trace(mVcdFile, tmp_last_V_reg_700, "tmp_last_V_reg_700");
    sc_trace(mVcdFile, output_C_q0, "output_C_q0");
    sc_trace(mVcdFile, input_A_address0, "input_A_address0");
    sc_trace(mVcdFile, input_A_ce0, "input_A_ce0");
    sc_trace(mVcdFile, input_A_we0, "input_A_we0");
    sc_trace(mVcdFile, input_B_address0, "input_B_address0");
    sc_trace(mVcdFile, input_B_ce0, "input_B_ce0");
    sc_trace(mVcdFile, input_B_we0, "input_B_we0");
    sc_trace(mVcdFile, output_C_address0, "output_C_address0");
    sc_trace(mVcdFile, output_C_ce0, "output_C_ce0");
    sc_trace(mVcdFile, output_C_we0, "output_C_we0");
    sc_trace(mVcdFile, row_0_reg_165, "row_0_reg_165");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, col_0_reg_176, "col_0_reg_176");
    sc_trace(mVcdFile, row_1_reg_187, "row_1_reg_187");
    sc_trace(mVcdFile, col_1_reg_198, "col_1_reg_198");
    sc_trace(mVcdFile, row_2_reg_209, "row_2_reg_209");
    sc_trace(mVcdFile, col_2_reg_220, "col_2_reg_220");
    sc_trace(mVcdFile, index_0_reg_231, "index_0_reg_231");
    sc_trace(mVcdFile, res_0_reg_242, "res_0_reg_242");
    sc_trace(mVcdFile, row_3_reg_255, "row_3_reg_255");
    sc_trace(mVcdFile, col_3_reg_266, "col_3_reg_266");
    sc_trace(mVcdFile, zext_ln23_1_fu_337_p1, "zext_ln23_1_fu_337_p1");
    sc_trace(mVcdFile, zext_ln32_1_fu_387_p1, "zext_ln32_1_fu_387_p1");
    sc_trace(mVcdFile, zext_ln43_1_fu_437_p1, "zext_ln43_1_fu_437_p1");
    sc_trace(mVcdFile, zext_ln41_1_fu_463_p1, "zext_ln41_1_fu_463_p1");
    sc_trace(mVcdFile, zext_ln41_3_fu_485_p1, "zext_ln41_3_fu_485_p1");
    sc_trace(mVcdFile, zext_ln50_1_fu_541_p1, "zext_ln50_1_fu_541_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_6_fu_304_p3, "tmp_6_fu_304_p3");
    sc_trace(mVcdFile, zext_ln23_fu_328_p1, "zext_ln23_fu_328_p1");
    sc_trace(mVcdFile, add_ln23_fu_332_p2, "add_ln23_fu_332_p2");
    sc_trace(mVcdFile, tmp_7_fu_354_p3, "tmp_7_fu_354_p3");
    sc_trace(mVcdFile, zext_ln32_fu_378_p1, "zext_ln32_fu_378_p1");
    sc_trace(mVcdFile, add_ln32_fu_382_p2, "add_ln32_fu_382_p2");
    sc_trace(mVcdFile, tmp_8_fu_404_p3, "tmp_8_fu_404_p3");
    sc_trace(mVcdFile, add_ln43_fu_432_p2, "add_ln43_fu_432_p2");
    sc_trace(mVcdFile, zext_ln41_fu_454_p1, "zext_ln41_fu_454_p1");
    sc_trace(mVcdFile, add_ln41_fu_458_p2, "add_ln41_fu_458_p2");
    sc_trace(mVcdFile, tmp_s_fu_468_p3, "tmp_s_fu_468_p3");
    sc_trace(mVcdFile, zext_ln41_2_fu_476_p1, "zext_ln41_2_fu_476_p1");
    sc_trace(mVcdFile, add_ln41_1_fu_480_p2, "add_ln41_1_fu_480_p2");
    sc_trace(mVcdFile, tmp_9_fu_502_p3, "tmp_9_fu_502_p3");
    sc_trace(mVcdFile, zext_ln50_fu_532_p1, "zext_ln50_fu_532_p1");
    sc_trace(mVcdFile, add_ln50_fu_536_p2, "add_ln50_fu_536_p2");
    sc_trace(mVcdFile, icmp_ln52_1_fu_546_p2, "icmp_ln52_1_fu_546_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matrixmul_1.hdltvin.dat");
    mHdltvoutHandle.open("matrixmul_1.hdltvout.dat");
}

matrixmul_1::~matrixmul_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete input_A_U;
    delete input_B_U;
    delete output_C_U;
    delete matrixmul_1_fadd_cud_U1;
    delete matrixmul_1_fmul_dEe_U2;
}

void matrixmul_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void matrixmul_1::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())))) {
        col_0_reg_176 = col_fu_322_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln18_fu_292_p2.read()))) {
        col_0_reg_176 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())))) {
        col_1_reg_198 = col_4_fu_372_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_fu_342_p2.read()))) {
        col_1_reg_198 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln40_fu_442_p2.read()))) {
        col_2_reg_220 = col_6_reg_616.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln37_fu_392_p2.read()))) {
        col_2_reg_220 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && 
         esl_seteq<1,1,1>(out_C_V_data_1_ack_in.read(), ap_const_logic_1))) {
        col_3_reg_266 = col_5_reg_690.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
                !(esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read()))) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln48_fu_490_p2.read()))) {
        col_3_reg_266 = ap_const_lv4_0;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_A_V_data_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_vld_out.read()))) {
            in_A_V_data_0_sel_rd =  (sc_logic) (~in_A_V_data_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_A_V_data_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_ack_in.read()))) {
            in_A_V_data_0_sel_wr =  (sc_logic) (~in_A_V_data_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_A_V_data_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_ack_out.read()) && 
              esl_seteq<1,2,2>(in_A_V_data_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_in.read()) && 
              esl_seteq<1,2,2>(in_A_V_data_0_state.read(), ap_const_lv2_2)))) {
            in_A_V_data_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_A_V_data_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_A_V_data_0_state.read(), ap_const_lv2_1)))) {
            in_A_V_data_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(in_A_V_data_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_A_V_data_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(in_A_V_data_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_ack_out.read()))))) {
            in_A_V_data_0_state = ap_const_lv2_3;
        } else {
            in_A_V_data_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_A_V_last_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_last_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, in_A_V_last_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, in_A_V_last_V_0_state.read())))) {
            in_A_V_last_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, in_A_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_A_V_last_V_0_state.read())))) {
            in_A_V_last_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, in_A_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_A_V_last_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, in_A_V_last_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_last_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_last_V_0_ack_out.read()))))) {
            in_A_V_last_V_0_state = ap_const_lv2_3;
        } else {
            in_A_V_last_V_0_state = ap_const_lv2_2;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        index_0_reg_231 = index_reg_634.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln38_fu_416_p2.read()))) {
        index_0_reg_231 = ap_const_lv4_0;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_C_V_data_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_vld_out.read()))) {
            out_C_V_data_1_sel_rd =  (sc_logic) (~out_C_V_data_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_C_V_data_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_ack_in.read()))) {
            out_C_V_data_1_sel_wr =  (sc_logic) (~out_C_V_data_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_C_V_data_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_C_V_data_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_C_V_data_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, out_C_V_data_1_state.read())))) {
            out_C_V_data_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read())))) {
            out_C_V_data_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, out_C_V_data_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_C_V_data_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_ack_out.read()))))) {
            out_C_V_data_1_state = ap_const_lv2_3;
        } else {
            out_C_V_data_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_C_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_vld_out.read()))) {
            out_C_V_last_V_1_sel_rd =  (sc_logic) (~out_C_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_C_V_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_ack_in.read()))) {
            out_C_V_last_V_1_sel_wr =  (sc_logic) (~out_C_V_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_C_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_C_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_C_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, out_C_V_last_V_1_state.read())))) {
            out_C_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read())))) {
            out_C_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, out_C_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_C_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_ack_out.read()))))) {
            out_C_V_last_V_1_state = ap_const_lv2_3;
        } else {
            out_C_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        res_0_reg_242 = grp_fu_277_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln38_fu_416_p2.read()))) {
        res_0_reg_242 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln20_fu_316_p2.read()))) {
        row_0_reg_165 = row_reg_560.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        row_0_reg_165 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln18_fu_292_p2.read()))) {
        row_1_reg_187 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln29_fu_366_p2.read()))) {
        row_1_reg_187 = row_4_reg_581.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln27_fu_342_p2.read()))) {
        row_2_reg_209 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln38_fu_416_p2.read()))) {
        row_2_reg_209 = row_5_reg_602.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln37_fu_392_p2.read()))) {
        row_3_reg_255 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln49_fu_520_p2.read()))) {
        row_3_reg_255 = row_6_reg_672.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        col_5_reg_690 = col_5_fu_526_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        col_6_reg_616 = col_6_fu_422_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && !(esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln48_fu_490_p2.read()))) {
        icmp_ln52_reg_682 = icmp_ln52_fu_514_p2.read();
        zext_ln52_reg_677 = zext_ln52_fu_510_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_load_A.read())) {
        in_A_V_data_0_payload_A = in_A_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_load_B.read())) {
        in_A_V_data_0_payload_B = in_A_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        index_reg_634 = index_fu_448_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        input_A_load_reg_649 = input_A_q0.read();
        input_B_load_reg_654 = input_B_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_load_A.read())) {
        out_C_V_data_1_payload_A = output_C_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_load_B.read())) {
        out_C_V_data_1_payload_B = output_C_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_load_A.read())) {
        out_C_V_last_V_1_payload_A = tmp_last_V_reg_700.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_load_B.read())) {
        out_C_V_last_V_1_payload_B = tmp_last_V_reg_700.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln38_fu_416_p2.read()))) {
        output_C_addr_1_reg_626 =  (sc_lv<6>) (zext_ln43_1_fu_437_p1.read());
        zext_ln43_reg_621 = zext_ln43_fu_428_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        row_4_reg_581 = row_4_fu_348_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        row_5_reg_602 = row_5_fu_398_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && !(esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read()))))) {
        row_6_reg_672 = row_6_fu_496_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_reg_560 = row_fu_298_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_3_reg_659 = grp_fu_282_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln49_fu_520_p2.read()))) {
        tmp_last_V_reg_700 = tmp_last_V_fu_552_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln18_fu_292_p2.read()))) {
        zext_ln20_reg_565 = zext_ln20_fu_312_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_fu_342_p2.read()))) {
        zext_ln29_reg_586 = zext_ln29_fu_362_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln37_fu_392_p2.read()))) {
        zext_ln38_reg_607 = zext_ln38_fu_412_p1.read();
    }
}

void matrixmul_1::thread_add_ln23_fu_332_p2() {
    add_ln23_fu_332_p2 = (!zext_ln20_reg_565.read().is_01() || !zext_ln23_fu_328_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln20_reg_565.read()) + sc_biguint<8>(zext_ln23_fu_328_p1.read()));
}

void matrixmul_1::thread_add_ln32_fu_382_p2() {
    add_ln32_fu_382_p2 = (!zext_ln29_reg_586.read().is_01() || !zext_ln32_fu_378_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln29_reg_586.read()) + sc_biguint<8>(zext_ln32_fu_378_p1.read()));
}

void matrixmul_1::thread_add_ln41_1_fu_480_p2() {
    add_ln41_1_fu_480_p2 = (!zext_ln43_reg_621.read().is_01() || !zext_ln41_2_fu_476_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln43_reg_621.read()) + sc_biguint<8>(zext_ln41_2_fu_476_p1.read()));
}

void matrixmul_1::thread_add_ln41_fu_458_p2() {
    add_ln41_fu_458_p2 = (!zext_ln41_fu_454_p1.read().is_01() || !zext_ln38_reg_607.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln41_fu_454_p1.read()) + sc_biguint<8>(zext_ln38_reg_607.read()));
}

void matrixmul_1::thread_add_ln43_fu_432_p2() {
    add_ln43_fu_432_p2 = (!zext_ln38_reg_607.read().is_01() || !zext_ln43_fu_428_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln38_reg_607.read()) + sc_biguint<8>(zext_ln43_fu_428_p1.read()));
}

void matrixmul_1::thread_add_ln50_fu_536_p2() {
    add_ln50_fu_536_p2 = (!zext_ln52_reg_677.read().is_01() || !zext_ln50_fu_532_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln52_reg_677.read()) + sc_biguint<8>(zext_ln50_fu_532_p1.read()));
}

void matrixmul_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrixmul_1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void matrixmul_1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void matrixmul_1::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void matrixmul_1::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void matrixmul_1::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void matrixmul_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrixmul_1::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void matrixmul_1::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void matrixmul_1::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void matrixmul_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matrixmul_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matrixmul_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void matrixmul_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void matrixmul_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void matrixmul_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void matrixmul_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void matrixmul_1::thread_ap_block_state19() {
    ap_block_state19 = (esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read())));
}

void matrixmul_1::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()));
}

void matrixmul_1::thread_ap_block_state5() {
    ap_block_state5 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()));
}

void matrixmul_1::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void matrixmul_1::thread_col_4_fu_372_p2() {
    col_4_fu_372_p2 = (!col_1_reg_198.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_1_reg_198.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_col_5_fu_526_p2() {
    col_5_fu_526_p2 = (!col_3_reg_266.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_3_reg_266.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_col_6_fu_422_p2() {
    col_6_fu_422_p2 = (!col_2_reg_220.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_2_reg_220.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_col_fu_322_p2() {
    col_fu_322_p2 = (!col_0_reg_176.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_0_reg_176.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_icmp_ln18_fu_292_p2() {
    icmp_ln18_fu_292_p2 = (!row_0_reg_165.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(row_0_reg_165.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln20_fu_316_p2() {
    icmp_ln20_fu_316_p2 = (!col_0_reg_176.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(col_0_reg_176.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln27_fu_342_p2() {
    icmp_ln27_fu_342_p2 = (!row_1_reg_187.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(row_1_reg_187.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln29_fu_366_p2() {
    icmp_ln29_fu_366_p2 = (!col_1_reg_198.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(col_1_reg_198.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln37_fu_392_p2() {
    icmp_ln37_fu_392_p2 = (!row_2_reg_209.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(row_2_reg_209.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln38_fu_416_p2() {
    icmp_ln38_fu_416_p2 = (!col_2_reg_220.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(col_2_reg_220.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln40_fu_442_p2() {
    icmp_ln40_fu_442_p2 = (!index_0_reg_231.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(index_0_reg_231.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln48_fu_490_p2() {
    icmp_ln48_fu_490_p2 = (!row_3_reg_255.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(row_3_reg_255.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln49_fu_520_p2() {
    icmp_ln49_fu_520_p2 = (!col_3_reg_266.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(col_3_reg_266.read() == ap_const_lv4_8);
}

void matrixmul_1::thread_icmp_ln52_1_fu_546_p2() {
    icmp_ln52_1_fu_546_p2 = (!col_3_reg_266.read().is_01() || !ap_const_lv4_7.is_01())? sc_lv<1>(): sc_lv<1>(col_3_reg_266.read() == ap_const_lv4_7);
}

void matrixmul_1::thread_icmp_ln52_fu_514_p2() {
    icmp_ln52_fu_514_p2 = (!row_3_reg_255.read().is_01() || !ap_const_lv4_7.is_01())? sc_lv<1>(): sc_lv<1>(row_3_reg_255.read() == ap_const_lv4_7);
}

void matrixmul_1::thread_in_A_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read())))) {
        in_A_TDATA_blk_n = in_A_V_data_0_state.read()[0];
    } else {
        in_A_TDATA_blk_n = ap_const_logic_1;
    }
}

void matrixmul_1::thread_in_A_TREADY() {
    in_A_TREADY = in_A_V_last_V_0_state.read()[1];
}

void matrixmul_1::thread_in_A_V_data_0_ack_in() {
    in_A_V_data_0_ack_in = in_A_V_data_0_state.read()[1];
}

void matrixmul_1::thread_in_A_V_data_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()))))) {
        in_A_V_data_0_ack_out = ap_const_logic_1;
    } else {
        in_A_V_data_0_ack_out = ap_const_logic_0;
    }
}

void matrixmul_1::thread_in_A_V_data_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_A_V_data_0_sel.read())) {
        in_A_V_data_0_data_out = in_A_V_data_0_payload_B.read();
    } else {
        in_A_V_data_0_data_out = in_A_V_data_0_payload_A.read();
    }
}

void matrixmul_1::thread_in_A_V_data_0_load_A() {
    in_A_V_data_0_load_A = (in_A_V_data_0_state_cmp_full.read() & ~in_A_V_data_0_sel_wr.read());
}

void matrixmul_1::thread_in_A_V_data_0_load_B() {
    in_A_V_data_0_load_B = (in_A_V_data_0_sel_wr.read() & in_A_V_data_0_state_cmp_full.read());
}

void matrixmul_1::thread_in_A_V_data_0_sel() {
    in_A_V_data_0_sel = in_A_V_data_0_sel_rd.read();
}

void matrixmul_1::thread_in_A_V_data_0_state_cmp_full() {
    in_A_V_data_0_state_cmp_full =  (sc_logic) ((!in_A_V_data_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(in_A_V_data_0_state.read() != ap_const_lv2_1))[0];
}

void matrixmul_1::thread_in_A_V_data_0_vld_in() {
    in_A_V_data_0_vld_in = in_A_TVALID.read();
}

void matrixmul_1::thread_in_A_V_data_0_vld_out() {
    in_A_V_data_0_vld_out = in_A_V_data_0_state.read()[0];
}

void matrixmul_1::thread_in_A_V_last_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()))))) {
        in_A_V_last_V_0_ack_out = ap_const_logic_1;
    } else {
        in_A_V_last_V_0_ack_out = ap_const_logic_0;
    }
}

void matrixmul_1::thread_in_A_V_last_V_0_vld_in() {
    in_A_V_last_V_0_vld_in = in_A_TVALID.read();
}

void matrixmul_1::thread_index_fu_448_p2() {
    index_fu_448_p2 = (!index_0_reg_231.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(index_0_reg_231.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_input_A_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_A_address0 =  (sc_lv<6>) (zext_ln41_1_fu_463_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        input_A_address0 =  (sc_lv<6>) (zext_ln23_1_fu_337_p1.read());
    } else {
        input_A_address0 = "XXXXXX";
    }
}

void matrixmul_1::thread_input_A_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        input_A_ce0 = ap_const_logic_1;
    } else {
        input_A_ce0 = ap_const_logic_0;
    }
}

void matrixmul_1::thread_input_A_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())))) {
        input_A_we0 = ap_const_logic_1;
    } else {
        input_A_we0 = ap_const_logic_0;
    }
}

void matrixmul_1::thread_input_B_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_B_address0 =  (sc_lv<6>) (zext_ln41_3_fu_485_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        input_B_address0 =  (sc_lv<6>) (zext_ln32_1_fu_387_p1.read());
    } else {
        input_B_address0 = "XXXXXX";
    }
}

void matrixmul_1::thread_input_B_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        input_B_ce0 = ap_const_logic_1;
    } else {
        input_B_ce0 = ap_const_logic_0;
    }
}

void matrixmul_1::thread_input_B_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())))) {
        input_B_we0 = ap_const_logic_1;
    } else {
        input_B_we0 = ap_const_logic_0;
    }
}

void matrixmul_1::thread_out_C_TDATA() {
    out_C_TDATA = out_C_V_data_1_data_out.read();
}

void matrixmul_1::thread_out_C_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        out_C_TDATA_blk_n = out_C_V_data_1_state.read()[1];
    } else {
        out_C_TDATA_blk_n = ap_const_logic_1;
    }
}

void matrixmul_1::thread_out_C_TLAST() {
    out_C_TLAST = out_C_V_last_V_1_data_out.read();
}

void matrixmul_1::thread_out_C_TVALID() {
    out_C_TVALID = out_C_V_last_V_1_state.read()[0];
}

void matrixmul_1::thread_out_C_V_data_1_ack_in() {
    out_C_V_data_1_ack_in = out_C_V_data_1_state.read()[1];
}

void matrixmul_1::thread_out_C_V_data_1_ack_out() {
    out_C_V_data_1_ack_out = out_C_TREADY.read();
}

void matrixmul_1::thread_out_C_V_data_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_data_1_sel.read())) {
        out_C_V_data_1_data_out = out_C_V_data_1_payload_B.read();
    } else {
        out_C_V_data_1_data_out = out_C_V_data_1_payload_A.read();
    }
}

void matrixmul_1::thread_out_C_V_data_1_load_A() {
    out_C_V_data_1_load_A = (out_C_V_data_1_state_cmp_full.read() & ~out_C_V_data_1_sel_wr.read());
}

void matrixmul_1::thread_out_C_V_data_1_load_B() {
    out_C_V_data_1_load_B = (out_C_V_data_1_sel_wr.read() & out_C_V_data_1_state_cmp_full.read());
}

void matrixmul_1::thread_out_C_V_data_1_sel() {
    out_C_V_data_1_sel = out_C_V_data_1_sel_rd.read();
}

void matrixmul_1::thread_out_C_V_data_1_state_cmp_full() {
    out_C_V_data_1_state_cmp_full =  (sc_logic) ((!out_C_V_data_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_C_V_data_1_state.read() != ap_const_lv2_1))[0];
}

void matrixmul_1::thread_out_C_V_data_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
         esl_seteq<1,1,1>(out_C_V_data_1_ack_in.read(), ap_const_logic_1))) {
        out_C_V_data_1_vld_in = ap_const_logic_1;
    } else {
        out_C_V_data_1_vld_in = ap_const_logic_0;
    }
}

void matrixmul_1::thread_out_C_V_data_1_vld_out() {
    out_C_V_data_1_vld_out = out_C_V_data_1_state.read()[0];
}

void matrixmul_1::thread_out_C_V_last_V_1_ack_in() {
    out_C_V_last_V_1_ack_in = out_C_V_last_V_1_state.read()[1];
}

void matrixmul_1::thread_out_C_V_last_V_1_ack_out() {
    out_C_V_last_V_1_ack_out = out_C_TREADY.read();
}

void matrixmul_1::thread_out_C_V_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_C_V_last_V_1_sel.read())) {
        out_C_V_last_V_1_data_out = out_C_V_last_V_1_payload_B.read();
    } else {
        out_C_V_last_V_1_data_out = out_C_V_last_V_1_payload_A.read();
    }
}

void matrixmul_1::thread_out_C_V_last_V_1_load_A() {
    out_C_V_last_V_1_load_A = (out_C_V_last_V_1_state_cmp_full.read() & ~out_C_V_last_V_1_sel_wr.read());
}

void matrixmul_1::thread_out_C_V_last_V_1_load_B() {
    out_C_V_last_V_1_load_B = (out_C_V_last_V_1_sel_wr.read() & out_C_V_last_V_1_state_cmp_full.read());
}

void matrixmul_1::thread_out_C_V_last_V_1_sel() {
    out_C_V_last_V_1_sel = out_C_V_last_V_1_sel_rd.read();
}

void matrixmul_1::thread_out_C_V_last_V_1_state_cmp_full() {
    out_C_V_last_V_1_state_cmp_full =  (sc_logic) ((!out_C_V_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_C_V_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void matrixmul_1::thread_out_C_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
         esl_seteq<1,1,1>(out_C_V_data_1_ack_in.read(), ap_const_logic_1))) {
        out_C_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        out_C_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void matrixmul_1::thread_out_C_V_last_V_1_vld_out() {
    out_C_V_last_V_1_vld_out = out_C_V_last_V_1_state.read()[0];
}

void matrixmul_1::thread_output_C_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        output_C_address0 =  (sc_lv<6>) (zext_ln50_1_fu_541_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_C_address0 = output_C_addr_1_reg_626.read();
    } else {
        output_C_address0 = "XXXXXX";
    }
}

void matrixmul_1::thread_output_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        output_C_ce0 = ap_const_logic_1;
    } else {
        output_C_ce0 = ap_const_logic_0;
    }
}

void matrixmul_1::thread_output_C_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln40_fu_442_p2.read()))) {
        output_C_we0 = ap_const_logic_1;
    } else {
        output_C_we0 = ap_const_logic_0;
    }
}

void matrixmul_1::thread_row_4_fu_348_p2() {
    row_4_fu_348_p2 = (!row_1_reg_187.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_1_reg_187.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_row_5_fu_398_p2() {
    row_5_fu_398_p2 = (!row_2_reg_209.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_2_reg_209.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_row_6_fu_496_p2() {
    row_6_fu_496_p2 = (!row_3_reg_255.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_3_reg_255.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_row_fu_298_p2() {
    row_fu_298_p2 = (!row_0_reg_165.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_0_reg_165.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrixmul_1::thread_tmp_6_fu_304_p3() {
    tmp_6_fu_304_p3 = esl_concat<4,3>(row_0_reg_165.read(), ap_const_lv3_0);
}

void matrixmul_1::thread_tmp_7_fu_354_p3() {
    tmp_7_fu_354_p3 = esl_concat<4,3>(row_1_reg_187.read(), ap_const_lv3_0);
}

void matrixmul_1::thread_tmp_8_fu_404_p3() {
    tmp_8_fu_404_p3 = esl_concat<4,3>(row_2_reg_209.read(), ap_const_lv3_0);
}

void matrixmul_1::thread_tmp_9_fu_502_p3() {
    tmp_9_fu_502_p3 = esl_concat<4,3>(row_3_reg_255.read(), ap_const_lv3_0);
}

void matrixmul_1::thread_tmp_last_V_fu_552_p2() {
    tmp_last_V_fu_552_p2 = (icmp_ln52_reg_682.read() & icmp_ln52_1_fu_546_p2.read());
}

void matrixmul_1::thread_tmp_s_fu_468_p3() {
    tmp_s_fu_468_p3 = esl_concat<4,3>(index_0_reg_231.read(), ap_const_lv3_0);
}

void matrixmul_1::thread_zext_ln20_fu_312_p1() {
    zext_ln20_fu_312_p1 = esl_zext<8,7>(tmp_6_fu_304_p3.read());
}

void matrixmul_1::thread_zext_ln23_1_fu_337_p1() {
    zext_ln23_1_fu_337_p1 = esl_zext<64,8>(add_ln23_fu_332_p2.read());
}

void matrixmul_1::thread_zext_ln23_fu_328_p1() {
    zext_ln23_fu_328_p1 = esl_zext<8,4>(col_0_reg_176.read());
}

void matrixmul_1::thread_zext_ln29_fu_362_p1() {
    zext_ln29_fu_362_p1 = esl_zext<8,7>(tmp_7_fu_354_p3.read());
}

void matrixmul_1::thread_zext_ln32_1_fu_387_p1() {
    zext_ln32_1_fu_387_p1 = esl_zext<64,8>(add_ln32_fu_382_p2.read());
}

void matrixmul_1::thread_zext_ln32_fu_378_p1() {
    zext_ln32_fu_378_p1 = esl_zext<8,4>(col_1_reg_198.read());
}

void matrixmul_1::thread_zext_ln38_fu_412_p1() {
    zext_ln38_fu_412_p1 = esl_zext<8,7>(tmp_8_fu_404_p3.read());
}

void matrixmul_1::thread_zext_ln41_1_fu_463_p1() {
    zext_ln41_1_fu_463_p1 = esl_zext<64,8>(add_ln41_fu_458_p2.read());
}

void matrixmul_1::thread_zext_ln41_2_fu_476_p1() {
    zext_ln41_2_fu_476_p1 = esl_zext<8,7>(tmp_s_fu_468_p3.read());
}

void matrixmul_1::thread_zext_ln41_3_fu_485_p1() {
    zext_ln41_3_fu_485_p1 = esl_zext<64,8>(add_ln41_1_fu_480_p2.read());
}

void matrixmul_1::thread_zext_ln41_fu_454_p1() {
    zext_ln41_fu_454_p1 = esl_zext<8,4>(index_0_reg_231.read());
}

void matrixmul_1::thread_zext_ln43_1_fu_437_p1() {
    zext_ln43_1_fu_437_p1 = esl_zext<64,8>(add_ln43_fu_432_p2.read());
}

void matrixmul_1::thread_zext_ln43_fu_428_p1() {
    zext_ln43_fu_428_p1 = esl_zext<8,4>(col_2_reg_220.read());
}

void matrixmul_1::thread_zext_ln50_1_fu_541_p1() {
    zext_ln50_1_fu_541_p1 = esl_zext<64,8>(add_ln50_fu_536_p2.read());
}

void matrixmul_1::thread_zext_ln50_fu_532_p1() {
    zext_ln50_fu_532_p1 = esl_zext<8,4>(col_3_reg_266.read());
}

void matrixmul_1::thread_zext_ln52_fu_510_p1() {
    zext_ln52_fu_510_p1 = esl_zext<8,7>(tmp_9_fu_502_p3.read());
}

void matrixmul_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln18_fu_292_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln20_fu_316_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln20_fu_316_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln27_fu_342_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln29_fu_366_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_366_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_A_V_data_0_vld_out.read())))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln37_fu_392_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln38_fu_416_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln40_fu_442_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 262144 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && !(esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read()))) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_fu_490_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && !(esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_data_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_C_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_data_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_C_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_C_V_last_V_1_state.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln48_fu_490_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 524288 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln49_fu_520_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(out_C_V_data_1_ack_in.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state22;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 2097152 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && esl_seteq<1,1,1>(out_C_V_data_1_ack_in.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state22;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<22>) ("XXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void matrixmul_1::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_A_TDATA\" :  \"" << in_A_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_A_TVALID\" :  \"" << in_A_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"in_A_TREADY\" :  \"" << in_A_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_A_TLAST\" :  \"" << in_A_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_C_TDATA\" :  \"" << out_C_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_C_TVALID\" :  \"" << out_C_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_C_TREADY\" :  \"" << out_C_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_C_TLAST\" :  \"" << out_C_TLAST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

