# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Sem_6/AELD/Labs/Lab_5_HW/Lab_5_HW.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_acp_0/design_1_fir_compiler_acp_0.xci
# IP: The module: 'design_1_fir_compiler_acp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Sem_6/AELD/Labs/Lab_5_HW/Lab_5_HW.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_acp_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_acp_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Sem_6/AELD/Labs/Lab_5_HW/Lab_5_HW.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_acp_0/design_1_fir_compiler_acp_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_acp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Sem_6/AELD/Labs/Lab_5_HW/Lab_5_HW.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_acp_0/design_1_fir_compiler_acp_0.xci
# IP: The module: 'design_1_fir_compiler_acp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Sem_6/AELD/Labs/Lab_5_HW/Lab_5_HW.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_acp_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_acp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Sem_6/AELD/Labs/Lab_5_HW/Lab_5_HW.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_acp_0/design_1_fir_compiler_acp_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_acp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
