// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixmul_2,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.104000,HLS_SYN_LAT=2768,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=5,HLS_SYN_FF=999,HLS_SYN_LUT=1805,HLS_VERSION=2019_1}" *)

module matrixmul_2 (
        ap_clk,
        ap_rst_n,
        in_A_TDATA,
        in_A_TVALID,
        in_A_TREADY,
        in_A_TLAST,
        out_C_TDATA,
        out_C_TVALID,
        out_C_TREADY,
        out_C_TLAST
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_pp2_stage0 = 13'd32;
parameter    ap_ST_fsm_pp2_stage1 = 13'd64;
parameter    ap_ST_fsm_pp2_stage2 = 13'd128;
parameter    ap_ST_fsm_pp2_stage3 = 13'd256;
parameter    ap_ST_fsm_pp2_stage4 = 13'd512;
parameter    ap_ST_fsm_state19 = 13'd1024;
parameter    ap_ST_fsm_pp3_stage0 = 13'd2048;
parameter    ap_ST_fsm_state23 = 13'd4096;

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_A_TDATA;
input   in_A_TVALID;
output   in_A_TREADY;
input  [0:0] in_A_TLAST;
output  [31:0] out_C_TDATA;
output   out_C_TVALID;
input   out_C_TREADY;
output  [0:0] out_C_TLAST;

 reg    ap_rst_n_inv;
reg   [31:0] in_A_V_data_0_data_out;
wire    in_A_V_data_0_vld_in;
wire    in_A_V_data_0_vld_out;
wire    in_A_V_data_0_ack_in;
reg    in_A_V_data_0_ack_out;
reg   [31:0] in_A_V_data_0_payload_A;
reg   [31:0] in_A_V_data_0_payload_B;
reg    in_A_V_data_0_sel_rd;
reg    in_A_V_data_0_sel_wr;
wire    in_A_V_data_0_sel;
wire    in_A_V_data_0_load_A;
wire    in_A_V_data_0_load_B;
reg   [1:0] in_A_V_data_0_state;
wire    in_A_V_data_0_state_cmp_full;
wire    in_A_V_last_V_0_vld_in;
reg    in_A_V_last_V_0_ack_out;
reg   [1:0] in_A_V_last_V_0_state;
reg   [31:0] out_C_V_data_1_data_out;
reg    out_C_V_data_1_vld_in;
wire    out_C_V_data_1_vld_out;
wire    out_C_V_data_1_ack_in;
wire    out_C_V_data_1_ack_out;
reg   [31:0] out_C_V_data_1_payload_A;
reg   [31:0] out_C_V_data_1_payload_B;
reg    out_C_V_data_1_sel_rd;
reg    out_C_V_data_1_sel_wr;
wire    out_C_V_data_1_sel;
wire    out_C_V_data_1_load_A;
wire    out_C_V_data_1_load_B;
reg   [1:0] out_C_V_data_1_state;
wire    out_C_V_data_1_state_cmp_full;
reg   [0:0] out_C_V_last_V_1_data_out;
reg    out_C_V_last_V_1_vld_in;
wire    out_C_V_last_V_1_vld_out;
wire    out_C_V_last_V_1_ack_in;
wire    out_C_V_last_V_1_ack_out;
reg   [0:0] out_C_V_last_V_1_payload_A;
reg   [0:0] out_C_V_last_V_1_payload_B;
reg    out_C_V_last_V_1_sel_rd;
reg    out_C_V_last_V_1_sel_wr;
wire    out_C_V_last_V_1_sel;
wire    out_C_V_last_V_1_load_A;
wire    out_C_V_last_V_1_load_B;
reg   [1:0] out_C_V_last_V_1_state;
wire    out_C_V_last_V_1_state_cmp_full;
reg    in_A_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln77_fu_373_p2;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln87_fu_446_p2;
reg    out_C_TDATA_blk_n;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter1;
wire    ap_block_pp3_stage0;
reg   [0:0] icmp_ln110_reg_940;
reg    ap_enable_reg_pp3_iter2;
reg   [0:0] icmp_ln110_reg_940_pp3_iter1_reg;
reg   [9:0] indvar_flatten38_reg_257;
reg   [3:0] row_2_reg_268;
reg   [7:0] indvar_flatten23_reg_280;
reg   [3:0] col_2_reg_291;
reg   [3:0] index_0_reg_302;
reg   [31:0] res_0_reg_314;
reg   [6:0] indvar_flatten50_reg_326;
reg   [3:0] row_3_reg_337;
reg   [3:0] col_3_reg_348;
wire   [6:0] add_ln77_fu_379_p2;
reg    ap_block_state2;
wire   [3:0] select_ln83_1_fu_405_p3;
wire   [3:0] col_fu_440_p2;
wire   [6:0] add_ln87_fu_452_p2;
reg    ap_block_state4;
wire   [3:0] select_ln93_1_fu_478_p3;
wire   [3:0] col_4_fu_513_p2;
wire   [0:0] icmp_ln98_fu_519_p2;
reg   [0:0] icmp_ln98_reg_837;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state6_pp2_stage0_iter0;
wire    ap_block_state11_pp2_stage0_iter1;
wire    ap_block_state16_pp2_stage0_iter2;
wire    ap_block_pp2_stage0_11001;
reg   [0:0] icmp_ln98_reg_837_pp2_iter1_reg;
reg   [0:0] icmp_ln98_reg_837_pp2_iter2_reg;
wire   [9:0] add_ln98_fu_525_p2;
reg   [9:0] add_ln98_reg_841;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] icmp_ln99_fu_531_p2;
reg   [0:0] icmp_ln99_reg_846;
wire   [3:0] select_ln103_fu_537_p3;
reg   [3:0] select_ln103_reg_854;
wire   [0:0] icmp_ln101_fu_545_p2;
reg   [0:0] icmp_ln101_reg_860;
wire   [7:0] add_ln99_fu_551_p2;
reg   [7:0] add_ln99_reg_865;
wire   [3:0] select_ln103_1_fu_563_p3;
reg   [3:0] select_ln103_1_reg_870;
wire    ap_CS_fsm_pp2_stage1;
wire    ap_block_state7_pp2_stage1_iter0;
wire    ap_block_state12_pp2_stage1_iter1;
wire    ap_block_state17_pp2_stage1_iter2;
wire    ap_block_pp2_stage1_11001;
wire   [0:0] or_ln103_fu_597_p2;
reg   [0:0] or_ln103_reg_875;
reg   [0:0] or_ln103_reg_875_pp2_iter1_reg;
wire   [3:0] select_ln103_4_fu_610_p3;
reg   [3:0] select_ln103_4_reg_880;
reg   [5:0] output_C_addr_1_reg_885;
reg   [5:0] output_C_addr_1_reg_885_pp2_iter1_reg;
reg   [5:0] output_C_addr_1_reg_885_pp2_iter2_reg;
wire   [3:0] index_fu_670_p2;
reg   [3:0] index_reg_900;
wire   [0:0] icmp_ln101_1_fu_676_p2;
reg   [0:0] icmp_ln101_1_reg_905;
reg   [0:0] icmp_ln101_1_reg_905_pp2_iter1_reg;
reg   [0:0] icmp_ln101_1_reg_905_pp2_iter2_reg;
wire   [31:0] input_A_q0;
reg   [31:0] input_A_load_reg_909;
wire    ap_CS_fsm_pp2_stage2;
wire    ap_block_state8_pp2_stage2_iter0;
wire    ap_block_state13_pp2_stage2_iter1;
wire    ap_block_state18_pp2_stage2_iter2;
wire    ap_block_pp2_stage2_11001;
wire   [31:0] input_B_q0;
reg   [31:0] input_B_load_reg_914;
wire   [7:0] select_ln99_fu_682_p3;
reg   [7:0] select_ln99_reg_919;
wire    ap_CS_fsm_pp2_stage4;
wire    ap_block_state10_pp2_stage4_iter0;
wire    ap_block_state15_pp2_stage4_iter1;
wire    ap_block_pp2_stage4_11001;
wire   [31:0] grp_fu_363_p2;
reg   [31:0] tmp_3_reg_924;
wire   [31:0] grp_fu_359_p2;
reg   [31:0] res_reg_934;
reg    ap_enable_reg_pp2_iter2;
wire   [0:0] icmp_ln110_fu_696_p2;
wire    ap_block_state20_pp3_stage0_iter0;
wire    ap_block_state21_pp3_stage0_iter1;
reg    ap_block_state21_io;
wire    ap_block_state22_pp3_stage0_iter2;
reg    ap_block_state22_io;
reg    ap_block_pp3_stage0_11001;
wire   [6:0] add_ln110_fu_702_p2;
reg    ap_enable_reg_pp3_iter0;
wire   [3:0] select_ln113_1_fu_728_p3;
reg   [3:0] select_ln113_1_reg_949;
wire   [0:0] tmp_last_V_fu_789_p2;
reg   [0:0] tmp_last_V_reg_959;
wire   [3:0] col_6_fu_795_p2;
wire   [31:0] output_C_q0;
wire    ap_CS_fsm_state5;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state6;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage4_subdone;
wire    ap_block_pp2_stage2_subdone;
wire    ap_CS_fsm_state19;
reg    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state20;
reg   [5:0] input_A_address0;
reg    input_A_ce0;
reg    input_A_we0;
reg   [5:0] input_B_address0;
reg    input_B_ce0;
reg    input_B_we0;
reg   [5:0] output_C_address0;
reg    output_C_ce0;
reg    output_C_we0;
reg   [6:0] indvar_flatten_reg_191;
wire    ap_CS_fsm_state1;
reg   [3:0] row_0_reg_202;
reg   [3:0] col_0_reg_213;
reg   [6:0] indvar_flatten11_reg_224;
wire    ap_CS_fsm_state3;
reg   [3:0] row_1_reg_235;
reg   [3:0] col_1_reg_246;
reg   [9:0] ap_phi_mux_indvar_flatten38_phi_fu_261_p4;
wire    ap_block_pp2_stage0;
reg   [3:0] ap_phi_mux_row_2_phi_fu_272_p4;
wire    ap_block_pp2_stage1;
reg   [7:0] ap_phi_mux_indvar_flatten23_phi_fu_284_p4;
reg   [3:0] ap_phi_mux_col_2_phi_fu_295_p4;
reg   [3:0] ap_phi_mux_index_0_phi_fu_306_p4;
reg   [31:0] ap_phi_mux_res_0_phi_fu_318_p4;
wire    ap_block_pp2_stage2;
reg   [3:0] ap_phi_mux_row_3_phi_fu_341_p4;
wire   [63:0] zext_ln83_1_fu_435_p1;
wire   [63:0] zext_ln93_1_fu_508_p1;
wire   [63:0] zext_ln105_fu_627_p1;
wire   [63:0] zext_ln103_3_fu_642_p1;
wire   [63:0] zext_ln103_5_fu_665_p1;
wire   [63:0] zext_ln113_1_fu_778_p1;
wire    ap_block_pp3_stage0_01001;
wire   [31:0] grp_fu_359_p0;
wire    ap_CS_fsm_pp2_stage3;
wire    ap_block_pp2_stage3;
wire   [0:0] icmp_ln79_fu_391_p2;
wire   [3:0] row_fu_385_p2;
wire   [6:0] tmp_fu_413_p3;
wire   [3:0] select_ln83_fu_397_p3;
wire   [7:0] zext_ln83_fu_425_p1;
wire   [7:0] zext_ln80_fu_421_p1;
wire   [7:0] add_ln83_fu_429_p2;
wire   [0:0] icmp_ln89_fu_464_p2;
wire   [3:0] row_4_fu_458_p2;
wire   [6:0] tmp_1_fu_486_p3;
wire   [3:0] select_ln93_fu_470_p3;
wire   [7:0] zext_ln93_fu_498_p1;
wire   [7:0] zext_ln90_fu_494_p1;
wire   [7:0] add_ln93_fu_502_p2;
wire   [3:0] row_6_fu_557_p2;
wire   [6:0] tmp_2_fu_570_p3;
wire   [0:0] xor_ln103_fu_582_p2;
wire   [0:0] and_ln103_fu_587_p2;
wire   [3:0] col_5_fu_592_p2;
wire   [7:0] zext_ln103_1_fu_617_p1;
wire   [7:0] zext_ln103_fu_578_p1;
wire   [7:0] add_ln105_fu_621_p2;
wire   [3:0] select_ln103_2_fu_602_p3;
wire   [7:0] zext_ln103_2_fu_632_p1;
wire   [7:0] add_ln103_fu_636_p2;
wire   [6:0] tmp_5_fu_647_p3;
wire   [7:0] zext_ln103_4_fu_655_p1;
wire   [7:0] add_ln103_1_fu_659_p2;
wire    ap_block_pp2_stage4;
wire   [0:0] icmp_ln111_fu_714_p2;
wire   [3:0] row_7_fu_708_p2;
wire   [6:0] tmp_7_fu_736_p3;
wire   [0:0] icmp_ln115_fu_748_p2;
wire   [0:0] icmp_ln115_2_fu_754_p2;
wire   [3:0] select_ln113_fu_720_p3;
wire   [7:0] zext_ln113_fu_768_p1;
wire   [7:0] zext_ln115_fu_744_p1;
wire   [7:0] add_ln113_fu_772_p2;
wire   [0:0] select_ln113_2_fu_760_p3;
wire   [0:0] icmp_ln115_1_fu_783_p2;
reg   [12:0] ap_NS_fsm;
wire    ap_CS_fsm_state23;
reg    ap_block_state23;
wire    ap_block_pp2_stage1_subdone;
wire    ap_block_state9_pp2_stage3_iter0;
wire    ap_block_state14_pp2_stage3_iter1;
wire    ap_block_pp2_stage3_subdone;
wire    ap_block_pp2_stage3_11001;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;

// power-on initialization
initial begin
#0 in_A_V_data_0_sel_rd = 1'b0;
#0 in_A_V_data_0_sel_wr = 1'b0;
#0 in_A_V_data_0_state = 2'd0;
#0 in_A_V_last_V_0_state = 2'd0;
#0 out_C_V_data_1_sel_rd = 1'b0;
#0 out_C_V_data_1_sel_wr = 1'b0;
#0 out_C_V_data_1_state = 2'd0;
#0 out_C_V_last_V_1_sel_rd = 1'b0;
#0 out_C_V_last_V_1_sel_wr = 1'b0;
#0 out_C_V_last_V_1_state = 2'd0;
#0 ap_CS_fsm = 13'd1;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
end

matrixmul_2_input_A #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
input_A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_A_address0),
    .ce0(input_A_ce0),
    .we0(input_A_we0),
    .d0(in_A_V_data_0_data_out),
    .q0(input_A_q0)
);

matrixmul_2_input_A #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
input_B_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_B_address0),
    .ce0(input_B_ce0),
    .we0(input_B_we0),
    .d0(in_A_V_data_0_data_out),
    .q0(input_B_q0)
);

matrixmul_2_input_A #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
output_C_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_C_address0),
    .ce0(output_C_ce0),
    .we0(output_C_we0),
    .d0(res_reg_934),
    .q0(output_C_q0)
);

matrixmul_2_fadd_cud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matrixmul_2_fadd_cud_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_359_p0),
    .din1(tmp_3_reg_924),
    .ce(1'b1),
    .dout(grp_fu_359_p2)
);

matrixmul_2_fmul_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matrixmul_2_fmul_dEe_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(input_A_load_reg_909),
    .din1(input_B_load_reg_914),
    .ce(1'b1),
    .dout(grp_fu_363_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage4_subdone) & (1'b1 == ap_CS_fsm_pp2_stage4))) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp2_stage4_subdone) & (1'b1 == ap_CS_fsm_pp2_stage4)) | ((1'b0 == ap_block_pp2_stage2_subdone) & (1'b1 == ap_CS_fsm_pp2_stage2)))) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp2_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_condition_pp3_exit_iter0_state20) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp3_exit_iter0_state20)) begin
                ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state20);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            ap_enable_reg_pp3_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_data_0_sel_rd <= 1'b0;
    end else begin
        if (((in_A_V_data_0_ack_out == 1'b1) & (in_A_V_data_0_vld_out == 1'b1))) begin
            in_A_V_data_0_sel_rd <= ~in_A_V_data_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_data_0_sel_wr <= 1'b0;
    end else begin
        if (((in_A_V_data_0_ack_in == 1'b1) & (in_A_V_data_0_vld_in == 1'b1))) begin
            in_A_V_data_0_sel_wr <= ~in_A_V_data_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_data_0_state <= 2'd0;
    end else begin
        if ((((in_A_V_data_0_state == 2'd2) & (in_A_V_data_0_vld_in == 1'b0)) | ((in_A_V_data_0_state == 2'd3) & (in_A_V_data_0_vld_in == 1'b0) & (in_A_V_data_0_ack_out == 1'b1)))) begin
            in_A_V_data_0_state <= 2'd2;
        end else if ((((in_A_V_data_0_state == 2'd1) & (in_A_V_data_0_ack_out == 1'b0)) | ((in_A_V_data_0_state == 2'd3) & (in_A_V_data_0_ack_out == 1'b0) & (in_A_V_data_0_vld_in == 1'b1)))) begin
            in_A_V_data_0_state <= 2'd1;
        end else if (((~((in_A_V_data_0_vld_in == 1'b0) & (in_A_V_data_0_ack_out == 1'b1)) & ~((in_A_V_data_0_ack_out == 1'b0) & (in_A_V_data_0_vld_in == 1'b1)) & (in_A_V_data_0_state == 2'd3)) | ((in_A_V_data_0_state == 2'd1) & (in_A_V_data_0_ack_out == 1'b1)) | ((in_A_V_data_0_state == 2'd2) & (in_A_V_data_0_vld_in == 1'b1)))) begin
            in_A_V_data_0_state <= 2'd3;
        end else begin
            in_A_V_data_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((in_A_V_last_V_0_state == 2'd2) & (in_A_V_last_V_0_vld_in == 1'b0)) | ((in_A_V_last_V_0_state == 2'd3) & (in_A_V_last_V_0_vld_in == 1'b0) & (in_A_V_last_V_0_ack_out == 1'b1)))) begin
            in_A_V_last_V_0_state <= 2'd2;
        end else if ((((in_A_V_last_V_0_state == 2'd1) & (in_A_V_last_V_0_ack_out == 1'b0)) | ((in_A_V_last_V_0_state == 2'd3) & (in_A_V_last_V_0_ack_out == 1'b0) & (in_A_V_last_V_0_vld_in == 1'b1)))) begin
            in_A_V_last_V_0_state <= 2'd1;
        end else if (((~((in_A_V_last_V_0_vld_in == 1'b0) & (in_A_V_last_V_0_ack_out == 1'b1)) & ~((in_A_V_last_V_0_ack_out == 1'b0) & (in_A_V_last_V_0_vld_in == 1'b1)) & (in_A_V_last_V_0_state == 2'd3)) | ((in_A_V_last_V_0_state == 2'd1) & (in_A_V_last_V_0_ack_out == 1'b1)) | ((in_A_V_last_V_0_state == 2'd2) & (in_A_V_last_V_0_vld_in == 1'b1)))) begin
            in_A_V_last_V_0_state <= 2'd3;
        end else begin
            in_A_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((out_C_V_data_1_ack_out == 1'b1) & (out_C_V_data_1_vld_out == 1'b1))) begin
            out_C_V_data_1_sel_rd <= ~out_C_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((out_C_V_data_1_ack_in == 1'b1) & (out_C_V_data_1_vld_in == 1'b1))) begin
            out_C_V_data_1_sel_wr <= ~out_C_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_data_1_state <= 2'd0;
    end else begin
        if ((((out_C_V_data_1_state == 2'd2) & (out_C_V_data_1_vld_in == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_V_data_1_vld_in == 1'b0) & (out_C_V_data_1_ack_out == 1'b1)))) begin
            out_C_V_data_1_state <= 2'd2;
        end else if ((((out_C_V_data_1_state == 2'd1) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0) & (out_C_V_data_1_vld_in == 1'b1)))) begin
            out_C_V_data_1_state <= 2'd1;
        end else if (((~((out_C_V_data_1_vld_in == 1'b0) & (out_C_V_data_1_ack_out == 1'b1)) & ~((out_C_TREADY == 1'b0) & (out_C_V_data_1_vld_in == 1'b1)) & (out_C_V_data_1_state == 2'd3)) | ((out_C_V_data_1_state == 2'd1) & (out_C_V_data_1_ack_out == 1'b1)) | ((out_C_V_data_1_state == 2'd2) & (out_C_V_data_1_vld_in == 1'b1)))) begin
            out_C_V_data_1_state <= 2'd3;
        end else begin
            out_C_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_C_V_last_V_1_ack_out == 1'b1) & (out_C_V_last_V_1_vld_out == 1'b1))) begin
            out_C_V_last_V_1_sel_rd <= ~out_C_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((out_C_V_last_V_1_ack_in == 1'b1) & (out_C_V_last_V_1_vld_in == 1'b1))) begin
            out_C_V_last_V_1_sel_wr <= ~out_C_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((out_C_V_last_V_1_state == 2'd2) & (out_C_V_last_V_1_vld_in == 1'b0)) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_V_last_V_1_vld_in == 1'b0) & (out_C_V_last_V_1_ack_out == 1'b1)))) begin
            out_C_V_last_V_1_state <= 2'd2;
        end else if ((((out_C_V_last_V_1_state == 2'd1) & (out_C_TREADY == 1'b0)) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0) & (out_C_V_last_V_1_vld_in == 1'b1)))) begin
            out_C_V_last_V_1_state <= 2'd1;
        end else if (((~((out_C_V_last_V_1_vld_in == 1'b0) & (out_C_V_last_V_1_ack_out == 1'b1)) & ~((out_C_TREADY == 1'b0) & (out_C_V_last_V_1_vld_in == 1'b1)) & (out_C_V_last_V_1_state == 2'd3)) | ((out_C_V_last_V_1_state == 2'd1) & (out_C_V_last_V_1_ack_out == 1'b1)) | ((out_C_V_last_V_1_state == 2'd2) & (out_C_V_last_V_1_vld_in == 1'b1)))) begin
            out_C_V_last_V_1_state <= 2'd3;
        end else begin
            out_C_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_0_reg_213 <= col_fu_440_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        col_0_reg_213 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        col_1_reg_246 <= 4'd0;
    end else if ((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        col_1_reg_246 <= col_4_fu_513_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_2_reg_291 <= 4'd0;
    end else if (((icmp_ln98_reg_837 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        col_2_reg_291 <= select_ln103_4_reg_880;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        col_3_reg_348 <= 4'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln110_fu_696_p2 == 1'd0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        col_3_reg_348 <= col_6_fu_795_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        index_0_reg_302 <= 4'd0;
    end else if (((icmp_ln98_reg_837 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        index_0_reg_302 <= index_reg_900;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        indvar_flatten11_reg_224 <= 7'd0;
    end else if ((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten11_reg_224 <= add_ln87_fu_452_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        indvar_flatten23_reg_280 <= 8'd0;
    end else if (((icmp_ln98_reg_837 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        indvar_flatten23_reg_280 <= select_ln99_reg_919;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        indvar_flatten38_reg_257 <= 10'd0;
    end else if (((icmp_ln98_reg_837 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        indvar_flatten38_reg_257 <= add_ln98_reg_841;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        indvar_flatten50_reg_326 <= 7'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln110_fu_696_p2 == 1'd0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        indvar_flatten50_reg_326 <= add_ln110_fu_702_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_reg_191 <= add_ln77_fu_379_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        indvar_flatten_reg_191 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_0_reg_314 <= 32'd0;
    end else if (((1'b0 == ap_block_pp2_stage2_11001) & (icmp_ln98_reg_837_pp2_iter2_reg == 1'd0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        res_0_reg_314 <= res_reg_934;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_0_reg_202 <= select_ln83_1_fu_405_p3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        row_0_reg_202 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        row_1_reg_235 <= 4'd0;
    end else if ((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        row_1_reg_235 <= select_ln93_1_fu_478_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        row_2_reg_268 <= 4'd0;
    end else if (((icmp_ln98_reg_837_pp2_iter1_reg == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        row_2_reg_268 <= select_ln103_1_reg_870;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        row_3_reg_337 <= 4'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln110_reg_940 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        row_3_reg_337 <= select_ln113_1_reg_949;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln98_reg_841 <= add_ln98_fu_525_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_fu_519_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln99_reg_865 <= add_ln99_fu_551_p2;
        icmp_ln101_reg_860 <= icmp_ln101_fu_545_p2;
        icmp_ln99_reg_846 <= icmp_ln99_fu_531_p2;
        select_ln103_reg_854 <= select_ln103_fu_537_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_reg_837 == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        icmp_ln101_1_reg_905 <= icmp_ln101_1_fu_676_p2;
        or_ln103_reg_875 <= or_ln103_fu_597_p2;
        output_C_addr_1_reg_885 <= zext_ln105_fu_627_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        icmp_ln101_1_reg_905_pp2_iter1_reg <= icmp_ln101_1_reg_905;
        icmp_ln101_1_reg_905_pp2_iter2_reg <= icmp_ln101_1_reg_905_pp2_iter1_reg;
        or_ln103_reg_875_pp2_iter1_reg <= or_ln103_reg_875;
        output_C_addr_1_reg_885_pp2_iter1_reg <= output_C_addr_1_reg_885;
        output_C_addr_1_reg_885_pp2_iter2_reg <= output_C_addr_1_reg_885_pp2_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln110_reg_940 <= icmp_ln110_fu_696_p2;
        icmp_ln110_reg_940_pp3_iter1_reg <= icmp_ln110_reg_940;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln98_reg_837 <= icmp_ln98_fu_519_p2;
        icmp_ln98_reg_837_pp2_iter1_reg <= icmp_ln98_reg_837;
        icmp_ln98_reg_837_pp2_iter2_reg <= icmp_ln98_reg_837_pp2_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((in_A_V_data_0_load_A == 1'b1)) begin
        in_A_V_data_0_payload_A <= in_A_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((in_A_V_data_0_load_B == 1'b1)) begin
        in_A_V_data_0_payload_B <= in_A_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_reg_837 == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        index_reg_900 <= index_fu_670_p2;
        select_ln103_1_reg_870 <= select_ln103_1_fu_563_p3;
        select_ln103_4_reg_880 <= select_ln103_4_fu_610_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage2_11001) & (icmp_ln98_reg_837 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        input_A_load_reg_909 <= input_A_q0;
        input_B_load_reg_914 <= input_B_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_data_1_load_A == 1'b1)) begin
        out_C_V_data_1_payload_A <= output_C_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_data_1_load_B == 1'b1)) begin
        out_C_V_data_1_payload_B <= output_C_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_last_V_1_load_A == 1'b1)) begin
        out_C_V_last_V_1_payload_A <= tmp_last_V_reg_959;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_last_V_1_load_B == 1'b1)) begin
        out_C_V_last_V_1_payload_B <= tmp_last_V_reg_959;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_reg_837_pp2_iter2_reg == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        res_reg_934 <= grp_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln110_fu_696_p2 == 1'd0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        select_ln113_1_reg_949 <= select_ln113_1_fu_728_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage4_11001) & (icmp_ln98_reg_837 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage4) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        select_ln99_reg_919 <= select_ln99_fu_682_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_reg_837_pp2_iter1_reg == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        tmp_3_reg_924 <= grp_fu_363_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln110_fu_696_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        tmp_last_V_reg_959 <= tmp_last_V_fu_789_p2;
    end
end

always @ (*) begin
    if ((icmp_ln98_fu_519_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln110_fu_696_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state20 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state20 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (icmp_ln98_reg_837 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_col_2_phi_fu_295_p4 = select_ln103_4_reg_880;
    end else begin
        ap_phi_mux_col_2_phi_fu_295_p4 = col_2_reg_291;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (icmp_ln98_reg_837 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_index_0_phi_fu_306_p4 = index_reg_900;
    end else begin
        ap_phi_mux_index_0_phi_fu_306_p4 = index_0_reg_302;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (icmp_ln98_reg_837 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_indvar_flatten23_phi_fu_284_p4 = select_ln99_reg_919;
    end else begin
        ap_phi_mux_indvar_flatten23_phi_fu_284_p4 = indvar_flatten23_reg_280;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (icmp_ln98_reg_837 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_indvar_flatten38_phi_fu_261_p4 = add_ln98_reg_841;
    end else begin
        ap_phi_mux_indvar_flatten38_phi_fu_261_p4 = indvar_flatten38_reg_257;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage2) & (icmp_ln98_reg_837_pp2_iter2_reg == 1'd0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        ap_phi_mux_res_0_phi_fu_318_p4 = res_reg_934;
    end else begin
        ap_phi_mux_res_0_phi_fu_318_p4 = res_0_reg_314;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (icmp_ln98_reg_837_pp2_iter1_reg == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        ap_phi_mux_row_2_phi_fu_272_p4 = select_ln103_1_reg_870;
    end else begin
        ap_phi_mux_row_2_phi_fu_272_p4 = row_2_reg_268;
    end
end

always @ (*) begin
    if (((icmp_ln110_reg_940 == 1'd0) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_mux_row_3_phi_fu_341_p4 = select_ln113_1_reg_949;
    end else begin
        ap_phi_mux_row_3_phi_fu_341_p4 = row_3_reg_337;
    end
end

always @ (*) begin
    if ((((icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        in_A_TDATA_blk_n = in_A_V_data_0_state[1'd0];
    end else begin
        in_A_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        in_A_V_data_0_ack_out = 1'b1;
    end else begin
        in_A_V_data_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((in_A_V_data_0_sel == 1'b1)) begin
        in_A_V_data_0_data_out = in_A_V_data_0_payload_B;
    end else begin
        in_A_V_data_0_data_out = in_A_V_data_0_payload_A;
    end
end

always @ (*) begin
    if (((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        in_A_V_last_V_0_ack_out = 1'b1;
    end else begin
        in_A_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        input_A_address0 = zext_ln103_3_fu_642_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_A_address0 = zext_ln83_1_fu_435_p1;
    end else begin
        input_A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1)) | (~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        input_A_ce0 = 1'b1;
    end else begin
        input_A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        input_A_we0 = 1'b1;
    end else begin
        input_A_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        input_B_address0 = zext_ln103_5_fu_665_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_B_address0 = zext_ln93_1_fu_508_p1;
    end else begin
        input_B_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1)) | (~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        input_B_ce0 = 1'b1;
    end else begin
        input_B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        input_B_we0 = 1'b1;
    end else begin
        input_B_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln110_reg_940_pp3_iter1_reg == 1'd0) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1)) | ((icmp_ln110_reg_940 == 1'd0) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        out_C_TDATA_blk_n = out_C_V_data_1_state[1'd1];
    end else begin
        out_C_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((out_C_V_data_1_sel == 1'b1)) begin
        out_C_V_data_1_data_out = out_C_V_data_1_payload_B;
    end else begin
        out_C_V_data_1_data_out = out_C_V_data_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln110_reg_940 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        out_C_V_data_1_vld_in = 1'b1;
    end else begin
        out_C_V_data_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((out_C_V_last_V_1_sel == 1'b1)) begin
        out_C_V_last_V_1_data_out = out_C_V_last_V_1_payload_B;
    end else begin
        out_C_V_last_V_1_data_out = out_C_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln110_reg_940 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        out_C_V_last_V_1_vld_in = 1'b1;
    end else begin
        out_C_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        output_C_address0 = zext_ln113_1_fu_778_p1;
    end else if (((1'b0 == ap_block_pp2_stage2) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        output_C_address0 = output_C_addr_1_reg_885_pp2_iter2_reg;
    end else begin
        output_C_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage2_11001) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2)) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        output_C_ce0 = 1'b1;
    end else begin
        output_C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln101_1_reg_905_pp2_iter2_reg == 1'd1) & (1'b0 == ap_block_pp2_stage2_11001) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        output_C_we0 = 1'b1;
    end else begin
        output_C_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln77_fu_373_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if ((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln87_fu_446_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((ap_enable_reg_pp2_iter1 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (icmp_ln98_fu_519_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else if (((ap_enable_reg_pp2_iter1 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (icmp_ln98_fu_519_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_pp2_stage2 : begin
            if ((~((1'b0 == ap_block_pp2_stage2_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2)) & (1'b0 == ap_block_pp2_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end else if (((1'b0 == ap_block_pp2_stage2_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end
        end
        ap_ST_fsm_pp2_stage3 : begin
            if ((1'b0 == ap_block_pp2_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end
        end
        ap_ST_fsm_pp2_stage4 : begin
            if ((1'b0 == ap_block_pp2_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage4;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((1'b0 == ap_block_pp3_stage0_subdone) & (icmp_ln110_fu_696_p2 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if ((((1'b0 == ap_block_pp3_stage0_subdone) & (icmp_ln110_fu_696_p2 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b1)) | ((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state23 : begin
            if ((~((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_1_fu_659_p2 = (zext_ln103_1_fu_617_p1 + zext_ln103_4_fu_655_p1);

assign add_ln103_fu_636_p2 = (zext_ln103_2_fu_632_p1 + zext_ln103_fu_578_p1);

assign add_ln105_fu_621_p2 = (zext_ln103_1_fu_617_p1 + zext_ln103_fu_578_p1);

assign add_ln110_fu_702_p2 = (indvar_flatten50_reg_326 + 7'd1);

assign add_ln113_fu_772_p2 = (zext_ln113_fu_768_p1 + zext_ln115_fu_744_p1);

assign add_ln77_fu_379_p2 = (indvar_flatten_reg_191 + 7'd1);

assign add_ln83_fu_429_p2 = (zext_ln83_fu_425_p1 + zext_ln80_fu_421_p1);

assign add_ln87_fu_452_p2 = (indvar_flatten11_reg_224 + 7'd1);

assign add_ln93_fu_502_p2 = (zext_ln93_fu_498_p1 + zext_ln90_fu_494_p1);

assign add_ln98_fu_525_p2 = (ap_phi_mux_indvar_flatten38_phi_fu_261_p4 + 10'd1);

assign add_ln99_fu_551_p2 = (ap_phi_mux_indvar_flatten23_phi_fu_284_p4 + 8'd1);

assign and_ln103_fu_587_p2 = (xor_ln103_fu_582_p2 & icmp_ln101_reg_860);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp2_stage2 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp2_stage3 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp2_stage4 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_11001 = (((1'b1 == ap_block_state22_io) & (ap_enable_reg_pp3_iter2 == 1'b1)) | ((1'b1 == ap_block_state21_io) & (ap_enable_reg_pp3_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp3_stage0_subdone = (((1'b1 == ap_block_state22_io) & (ap_enable_reg_pp3_iter2 == 1'b1)) | ((1'b1 == ap_block_state21_io) & (ap_enable_reg_pp3_iter1 == 1'b1)));
end

assign ap_block_state10_pp2_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp2_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp2_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp2_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp2_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp2_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp2_stage2_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2 = ((icmp_ln77_fu_373_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0));
end

assign ap_block_state20_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_io = ((icmp_ln110_reg_940 == 1'd0) & (out_C_V_data_1_ack_in == 1'b0));
end

assign ap_block_state21_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22_io = ((icmp_ln110_reg_940_pp3_iter1_reg == 1'd0) & (out_C_V_data_1_ack_in == 1'b0));
end

assign ap_block_state22_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state23 = ((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state4 = ((icmp_ln87_fu_446_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0));
end

assign ap_block_state6_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp2_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp2_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp2_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_4_fu_513_p2 = (select_ln93_fu_470_p3 + 4'd1);

assign col_5_fu_592_p2 = (select_ln103_reg_854 + 4'd1);

assign col_6_fu_795_p2 = (select_ln113_fu_720_p3 + 4'd1);

assign col_fu_440_p2 = (select_ln83_fu_397_p3 + 4'd1);

assign grp_fu_359_p0 = ((or_ln103_reg_875_pp2_iter1_reg[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_res_0_phi_fu_318_p4);

assign icmp_ln101_1_fu_676_p2 = ((index_fu_670_p2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln101_fu_545_p2 = ((ap_phi_mux_index_0_phi_fu_306_p4 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_696_p2 = ((indvar_flatten50_reg_326 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_714_p2 = ((col_3_reg_348 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln115_1_fu_783_p2 = ((select_ln113_fu_720_p3 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln115_2_fu_754_p2 = ((ap_phi_mux_row_3_phi_fu_341_p4 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_748_p2 = ((row_7_fu_708_p2 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_373_p2 = ((indvar_flatten_reg_191 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_391_p2 = ((col_0_reg_213 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_446_p2 = ((indvar_flatten11_reg_224 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_464_p2 = ((col_1_reg_246 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_519_p2 = ((ap_phi_mux_indvar_flatten38_phi_fu_261_p4 == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_531_p2 = ((ap_phi_mux_indvar_flatten23_phi_fu_284_p4 == 8'd64) ? 1'b1 : 1'b0);

assign in_A_TREADY = in_A_V_last_V_0_state[1'd1];

assign in_A_V_data_0_ack_in = in_A_V_data_0_state[1'd1];

assign in_A_V_data_0_load_A = (in_A_V_data_0_state_cmp_full & ~in_A_V_data_0_sel_wr);

assign in_A_V_data_0_load_B = (in_A_V_data_0_state_cmp_full & in_A_V_data_0_sel_wr);

assign in_A_V_data_0_sel = in_A_V_data_0_sel_rd;

assign in_A_V_data_0_state_cmp_full = ((in_A_V_data_0_state != 2'd1) ? 1'b1 : 1'b0);

assign in_A_V_data_0_vld_in = in_A_TVALID;

assign in_A_V_data_0_vld_out = in_A_V_data_0_state[1'd0];

assign in_A_V_last_V_0_vld_in = in_A_TVALID;

assign index_fu_670_p2 = (select_ln103_2_fu_602_p3 + 4'd1);

assign or_ln103_fu_597_p2 = (icmp_ln99_reg_846 | and_ln103_fu_587_p2);

assign out_C_TDATA = out_C_V_data_1_data_out;

assign out_C_TLAST = out_C_V_last_V_1_data_out;

assign out_C_TVALID = out_C_V_last_V_1_state[1'd0];

assign out_C_V_data_1_ack_in = out_C_V_data_1_state[1'd1];

assign out_C_V_data_1_ack_out = out_C_TREADY;

assign out_C_V_data_1_load_A = (out_C_V_data_1_state_cmp_full & ~out_C_V_data_1_sel_wr);

assign out_C_V_data_1_load_B = (out_C_V_data_1_state_cmp_full & out_C_V_data_1_sel_wr);

assign out_C_V_data_1_sel = out_C_V_data_1_sel_rd;

assign out_C_V_data_1_state_cmp_full = ((out_C_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_C_V_data_1_vld_out = out_C_V_data_1_state[1'd0];

assign out_C_V_last_V_1_ack_in = out_C_V_last_V_1_state[1'd1];

assign out_C_V_last_V_1_ack_out = out_C_TREADY;

assign out_C_V_last_V_1_load_A = (out_C_V_last_V_1_state_cmp_full & ~out_C_V_last_V_1_sel_wr);

assign out_C_V_last_V_1_load_B = (out_C_V_last_V_1_state_cmp_full & out_C_V_last_V_1_sel_wr);

assign out_C_V_last_V_1_sel = out_C_V_last_V_1_sel_rd;

assign out_C_V_last_V_1_state_cmp_full = ((out_C_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_C_V_last_V_1_vld_out = out_C_V_last_V_1_state[1'd0];

assign row_4_fu_458_p2 = (row_1_reg_235 + 4'd1);

assign row_6_fu_557_p2 = (ap_phi_mux_row_2_phi_fu_272_p4 + 4'd1);

assign row_7_fu_708_p2 = (ap_phi_mux_row_3_phi_fu_341_p4 + 4'd1);

assign row_fu_385_p2 = (row_0_reg_202 + 4'd1);

assign select_ln103_1_fu_563_p3 = ((icmp_ln99_reg_846[0:0] === 1'b1) ? row_6_fu_557_p2 : ap_phi_mux_row_2_phi_fu_272_p4);

assign select_ln103_2_fu_602_p3 = ((or_ln103_fu_597_p2[0:0] === 1'b1) ? 4'd0 : index_0_reg_302);

assign select_ln103_4_fu_610_p3 = ((and_ln103_fu_587_p2[0:0] === 1'b1) ? col_5_fu_592_p2 : select_ln103_reg_854);

assign select_ln103_fu_537_p3 = ((icmp_ln99_fu_531_p2[0:0] === 1'b1) ? 4'd0 : ap_phi_mux_col_2_phi_fu_295_p4);

assign select_ln113_1_fu_728_p3 = ((icmp_ln111_fu_714_p2[0:0] === 1'b1) ? row_7_fu_708_p2 : ap_phi_mux_row_3_phi_fu_341_p4);

assign select_ln113_2_fu_760_p3 = ((icmp_ln111_fu_714_p2[0:0] === 1'b1) ? icmp_ln115_fu_748_p2 : icmp_ln115_2_fu_754_p2);

assign select_ln113_fu_720_p3 = ((icmp_ln111_fu_714_p2[0:0] === 1'b1) ? 4'd0 : col_3_reg_348);

assign select_ln83_1_fu_405_p3 = ((icmp_ln79_fu_391_p2[0:0] === 1'b1) ? row_fu_385_p2 : row_0_reg_202);

assign select_ln83_fu_397_p3 = ((icmp_ln79_fu_391_p2[0:0] === 1'b1) ? 4'd0 : col_0_reg_213);

assign select_ln93_1_fu_478_p3 = ((icmp_ln89_fu_464_p2[0:0] === 1'b1) ? row_4_fu_458_p2 : row_1_reg_235);

assign select_ln93_fu_470_p3 = ((icmp_ln89_fu_464_p2[0:0] === 1'b1) ? 4'd0 : col_1_reg_246);

assign select_ln99_fu_682_p3 = ((icmp_ln99_reg_846[0:0] === 1'b1) ? 8'd1 : add_ln99_reg_865);

assign tmp_1_fu_486_p3 = {{select_ln93_1_fu_478_p3}, {3'd0}};

assign tmp_2_fu_570_p3 = {{select_ln103_1_fu_563_p3}, {3'd0}};

assign tmp_5_fu_647_p3 = {{select_ln103_2_fu_602_p3}, {3'd0}};

assign tmp_7_fu_736_p3 = {{select_ln113_1_fu_728_p3}, {3'd0}};

assign tmp_fu_413_p3 = {{select_ln83_1_fu_405_p3}, {3'd0}};

assign tmp_last_V_fu_789_p2 = (select_ln113_2_fu_760_p3 & icmp_ln115_1_fu_783_p2);

assign xor_ln103_fu_582_p2 = (icmp_ln99_reg_846 ^ 1'd1);

assign zext_ln103_1_fu_617_p1 = select_ln103_4_fu_610_p3;

assign zext_ln103_2_fu_632_p1 = select_ln103_2_fu_602_p3;

assign zext_ln103_3_fu_642_p1 = add_ln103_fu_636_p2;

assign zext_ln103_4_fu_655_p1 = tmp_5_fu_647_p3;

assign zext_ln103_5_fu_665_p1 = add_ln103_1_fu_659_p2;

assign zext_ln103_fu_578_p1 = tmp_2_fu_570_p3;

assign zext_ln105_fu_627_p1 = add_ln105_fu_621_p2;

assign zext_ln113_1_fu_778_p1 = add_ln113_fu_772_p2;

assign zext_ln113_fu_768_p1 = select_ln113_fu_720_p3;

assign zext_ln115_fu_744_p1 = tmp_7_fu_736_p3;

assign zext_ln80_fu_421_p1 = tmp_fu_413_p3;

assign zext_ln83_1_fu_435_p1 = add_ln83_fu_429_p2;

assign zext_ln83_fu_425_p1 = select_ln83_fu_397_p3;

assign zext_ln90_fu_494_p1 = tmp_1_fu_486_p3;

assign zext_ln93_1_fu_508_p1 = add_ln93_fu_502_p2;

assign zext_ln93_fu_498_p1 = select_ln93_fu_470_p3;

endmodule //matrixmul_2
