-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrixmul_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_A_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_A_TVALID : IN STD_LOGIC;
    in_A_TREADY : OUT STD_LOGIC;
    in_A_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_C_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_C_TVALID : OUT STD_LOGIC;
    out_C_TREADY : IN STD_LOGIC;
    out_C_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of matrixmul_1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrixmul_1,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=6148,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=5,HLS_SYN_FF=734,HLS_SYN_LUT=1428,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (21 downto 0) := "0000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (21 downto 0) := "0000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (21 downto 0) := "0000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (21 downto 0) := "0000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (21 downto 0) := "0000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (21 downto 0) := "0001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (21 downto 0) := "0010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (21 downto 0) := "0100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (21 downto 0) := "1000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal in_A_V_data_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal in_A_V_data_0_vld_in : STD_LOGIC;
    signal in_A_V_data_0_vld_out : STD_LOGIC;
    signal in_A_V_data_0_ack_in : STD_LOGIC;
    signal in_A_V_data_0_ack_out : STD_LOGIC;
    signal in_A_V_data_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal in_A_V_data_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal in_A_V_data_0_sel_rd : STD_LOGIC := '0';
    signal in_A_V_data_0_sel_wr : STD_LOGIC := '0';
    signal in_A_V_data_0_sel : STD_LOGIC;
    signal in_A_V_data_0_load_A : STD_LOGIC;
    signal in_A_V_data_0_load_B : STD_LOGIC;
    signal in_A_V_data_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_A_V_data_0_state_cmp_full : STD_LOGIC;
    signal in_A_V_last_V_0_vld_in : STD_LOGIC;
    signal in_A_V_last_V_0_ack_out : STD_LOGIC;
    signal in_A_V_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_C_V_data_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal out_C_V_data_1_vld_in : STD_LOGIC;
    signal out_C_V_data_1_vld_out : STD_LOGIC;
    signal out_C_V_data_1_ack_in : STD_LOGIC;
    signal out_C_V_data_1_ack_out : STD_LOGIC;
    signal out_C_V_data_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal out_C_V_data_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal out_C_V_data_1_sel_rd : STD_LOGIC := '0';
    signal out_C_V_data_1_sel_wr : STD_LOGIC := '0';
    signal out_C_V_data_1_sel : STD_LOGIC;
    signal out_C_V_data_1_load_A : STD_LOGIC;
    signal out_C_V_data_1_load_B : STD_LOGIC;
    signal out_C_V_data_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_C_V_data_1_state_cmp_full : STD_LOGIC;
    signal out_C_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal out_C_V_last_V_1_vld_in : STD_LOGIC;
    signal out_C_V_last_V_1_vld_out : STD_LOGIC;
    signal out_C_V_last_V_1_ack_in : STD_LOGIC;
    signal out_C_V_last_V_1_ack_out : STD_LOGIC;
    signal out_C_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal out_C_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal out_C_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal out_C_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal out_C_V_last_V_1_sel : STD_LOGIC;
    signal out_C_V_last_V_1_load_A : STD_LOGIC;
    signal out_C_V_last_V_1_load_B : STD_LOGIC;
    signal out_C_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_C_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal in_A_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln20_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln29_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_C_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal row_fu_298_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal row_reg_560 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln20_fu_312_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln20_reg_565 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln18_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_fu_322_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal row_4_fu_348_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal row_4_reg_581 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln29_fu_362_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln29_reg_586 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln27_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_4_fu_372_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal row_5_fu_398_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal row_5_reg_602 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln38_fu_412_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln38_reg_607 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln37_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_6_fu_422_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal col_6_reg_616 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal zext_ln43_fu_428_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln43_reg_621 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln38_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_C_addr_1_reg_626 : STD_LOGIC_VECTOR (5 downto 0);
    signal index_fu_448_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal index_reg_634 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal icmp_ln40_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_A_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_load_reg_649 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal input_B_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_load_reg_654 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_282_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_reg_659 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_277_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal row_6_fu_496_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal row_6_reg_672 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_block_state19 : BOOLEAN;
    signal zext_ln52_fu_510_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln52_reg_677 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln48_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_5_fu_526_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal col_5_reg_690 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal icmp_ln49_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_700 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_C_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal input_A_ce0 : STD_LOGIC;
    signal input_A_we0 : STD_LOGIC;
    signal input_B_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal input_B_ce0 : STD_LOGIC;
    signal input_B_we0 : STD_LOGIC;
    signal output_C_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal output_C_ce0 : STD_LOGIC;
    signal output_C_we0 : STD_LOGIC;
    signal row_0_reg_165 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal col_0_reg_176 : STD_LOGIC_VECTOR (3 downto 0);
    signal row_1_reg_187 : STD_LOGIC_VECTOR (3 downto 0);
    signal col_1_reg_198 : STD_LOGIC_VECTOR (3 downto 0);
    signal row_2_reg_209 : STD_LOGIC_VECTOR (3 downto 0);
    signal col_2_reg_220 : STD_LOGIC_VECTOR (3 downto 0);
    signal index_0_reg_231 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_0_reg_242 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_3_reg_255 : STD_LOGIC_VECTOR (3 downto 0);
    signal col_3_reg_266 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln23_1_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_1_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_1_fu_437_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln41_1_fu_463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln41_3_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln50_1_fu_541_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal tmp_6_fu_304_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln23_fu_328_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln23_fu_332_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_354_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln32_fu_378_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln32_fu_382_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_404_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln43_fu_432_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln41_fu_454_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln41_fu_458_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_468_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln41_2_fu_476_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln41_1_fu_480_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_502_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln50_fu_532_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln50_fu_536_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln52_1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (21 downto 0);

    component matrixmul_1_fadd_cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrixmul_1_fmul_dEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrixmul_1_input_A IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    input_A_U : component matrixmul_1_input_A
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_address0,
        ce0 => input_A_ce0,
        we0 => input_A_we0,
        d0 => in_A_V_data_0_data_out,
        q0 => input_A_q0);

    input_B_U : component matrixmul_1_input_A
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_address0,
        ce0 => input_B_ce0,
        we0 => input_B_we0,
        d0 => in_A_V_data_0_data_out,
        q0 => input_B_q0);

    output_C_U : component matrixmul_1_input_A
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => output_C_address0,
        ce0 => output_C_ce0,
        we0 => output_C_we0,
        d0 => res_0_reg_242,
        q0 => output_C_q0);

    matrixmul_1_fadd_cud_U1 : component matrixmul_1_fadd_cud
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => res_0_reg_242,
        din1 => tmp_3_reg_659,
        ce => ap_const_logic_1,
        dout => grp_fu_277_p2);

    matrixmul_1_fmul_dEe_U2 : component matrixmul_1_fmul_dEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => input_A_load_reg_649,
        din1 => input_B_load_reg_654,
        ce => ap_const_logic_1,
        dout => grp_fu_282_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    in_A_V_data_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_A_V_data_0_sel_rd <= ap_const_logic_0;
            else
                if (((in_A_V_data_0_ack_out = ap_const_logic_1) and (in_A_V_data_0_vld_out = ap_const_logic_1))) then 
                                        in_A_V_data_0_sel_rd <= not(in_A_V_data_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    in_A_V_data_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_A_V_data_0_sel_wr <= ap_const_logic_0;
            else
                if (((in_A_V_data_0_ack_in = ap_const_logic_1) and (in_A_V_data_0_vld_in = ap_const_logic_1))) then 
                                        in_A_V_data_0_sel_wr <= not(in_A_V_data_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    in_A_V_data_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_A_V_data_0_state <= ap_const_lv2_0;
            else
                if ((((in_A_V_data_0_state = ap_const_lv2_2) and (in_A_V_data_0_vld_in = ap_const_logic_0)) or ((in_A_V_data_0_state = ap_const_lv2_3) and (in_A_V_data_0_vld_in = ap_const_logic_0) and (in_A_V_data_0_ack_out = ap_const_logic_1)))) then 
                    in_A_V_data_0_state <= ap_const_lv2_2;
                elsif ((((in_A_V_data_0_state = ap_const_lv2_1) and (in_A_V_data_0_ack_out = ap_const_logic_0)) or ((in_A_V_data_0_state = ap_const_lv2_3) and (in_A_V_data_0_ack_out = ap_const_logic_0) and (in_A_V_data_0_vld_in = ap_const_logic_1)))) then 
                    in_A_V_data_0_state <= ap_const_lv2_1;
                elsif (((not(((in_A_V_data_0_vld_in = ap_const_logic_0) and (in_A_V_data_0_ack_out = ap_const_logic_1))) and not(((in_A_V_data_0_ack_out = ap_const_logic_0) and (in_A_V_data_0_vld_in = ap_const_logic_1))) and (in_A_V_data_0_state = ap_const_lv2_3)) or ((in_A_V_data_0_state = ap_const_lv2_1) and (in_A_V_data_0_ack_out = ap_const_logic_1)) or ((in_A_V_data_0_state = ap_const_lv2_2) and (in_A_V_data_0_vld_in = ap_const_logic_1)))) then 
                    in_A_V_data_0_state <= ap_const_lv2_3;
                else 
                    in_A_V_data_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    in_A_V_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_A_V_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_A_V_last_V_0_state = ap_const_lv2_2) and (in_A_V_last_V_0_vld_in = ap_const_logic_0)) or ((in_A_V_last_V_0_state = ap_const_lv2_3) and (in_A_V_last_V_0_vld_in = ap_const_logic_0) and (in_A_V_last_V_0_ack_out = ap_const_logic_1)))) then 
                    in_A_V_last_V_0_state <= ap_const_lv2_2;
                elsif ((((in_A_V_last_V_0_state = ap_const_lv2_1) and (in_A_V_last_V_0_ack_out = ap_const_logic_0)) or ((in_A_V_last_V_0_state = ap_const_lv2_3) and (in_A_V_last_V_0_ack_out = ap_const_logic_0) and (in_A_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    in_A_V_last_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_A_V_last_V_0_vld_in = ap_const_logic_0) and (in_A_V_last_V_0_ack_out = ap_const_logic_1))) and not(((in_A_V_last_V_0_ack_out = ap_const_logic_0) and (in_A_V_last_V_0_vld_in = ap_const_logic_1))) and (in_A_V_last_V_0_state = ap_const_lv2_3)) or ((in_A_V_last_V_0_state = ap_const_lv2_1) and (in_A_V_last_V_0_ack_out = ap_const_logic_1)) or ((in_A_V_last_V_0_state = ap_const_lv2_2) and (in_A_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    in_A_V_last_V_0_state <= ap_const_lv2_3;
                else 
                    in_A_V_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_C_V_data_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_C_V_data_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_C_V_data_1_ack_out = ap_const_logic_1) and (out_C_V_data_1_vld_out = ap_const_logic_1))) then 
                                        out_C_V_data_1_sel_rd <= not(out_C_V_data_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_C_V_data_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_C_V_data_1_sel_wr <= ap_const_logic_0;
            else
                if (((out_C_V_data_1_ack_in = ap_const_logic_1) and (out_C_V_data_1_vld_in = ap_const_logic_1))) then 
                                        out_C_V_data_1_sel_wr <= not(out_C_V_data_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    out_C_V_data_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_C_V_data_1_state <= ap_const_lv2_0;
            else
                if ((((out_C_V_data_1_state = ap_const_lv2_2) and (out_C_V_data_1_vld_in = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_V_data_1_vld_in = ap_const_logic_0) and (out_C_V_data_1_ack_out = ap_const_logic_1)))) then 
                    out_C_V_data_1_state <= ap_const_lv2_2;
                elsif ((((out_C_V_data_1_state = ap_const_lv2_1) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0) and (out_C_V_data_1_vld_in = ap_const_logic_1)))) then 
                    out_C_V_data_1_state <= ap_const_lv2_1;
                elsif (((not(((out_C_V_data_1_vld_in = ap_const_logic_0) and (out_C_V_data_1_ack_out = ap_const_logic_1))) and not(((out_C_TREADY = ap_const_logic_0) and (out_C_V_data_1_vld_in = ap_const_logic_1))) and (out_C_V_data_1_state = ap_const_lv2_3)) or ((out_C_V_data_1_state = ap_const_lv2_1) and (out_C_V_data_1_ack_out = ap_const_logic_1)) or ((out_C_V_data_1_state = ap_const_lv2_2) and (out_C_V_data_1_vld_in = ap_const_logic_1)))) then 
                    out_C_V_data_1_state <= ap_const_lv2_3;
                else 
                    out_C_V_data_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_C_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_C_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_C_V_last_V_1_ack_out = ap_const_logic_1) and (out_C_V_last_V_1_vld_out = ap_const_logic_1))) then 
                                        out_C_V_last_V_1_sel_rd <= not(out_C_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_C_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_C_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((out_C_V_last_V_1_ack_in = ap_const_logic_1) and (out_C_V_last_V_1_vld_in = ap_const_logic_1))) then 
                                        out_C_V_last_V_1_sel_wr <= not(out_C_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    out_C_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_C_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_C_V_last_V_1_state = ap_const_lv2_2) and (out_C_V_last_V_1_vld_in = ap_const_logic_0)) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_V_last_V_1_vld_in = ap_const_logic_0) and (out_C_V_last_V_1_ack_out = ap_const_logic_1)))) then 
                    out_C_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((out_C_V_last_V_1_state = ap_const_lv2_1) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0) and (out_C_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    out_C_V_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_C_V_last_V_1_vld_in = ap_const_logic_0) and (out_C_V_last_V_1_ack_out = ap_const_logic_1))) and not(((out_C_TREADY = ap_const_logic_0) and (out_C_V_last_V_1_vld_in = ap_const_logic_1))) and (out_C_V_last_V_1_state = ap_const_lv2_3)) or ((out_C_V_last_V_1_state = ap_const_lv2_1) and (out_C_V_last_V_1_ack_out = ap_const_logic_1)) or ((out_C_V_last_V_1_state = ap_const_lv2_2) and (out_C_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    out_C_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    out_C_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    col_0_reg_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                col_0_reg_176 <= col_fu_322_p2;
            elsif (((icmp_ln18_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                col_0_reg_176 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    col_1_reg_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                col_1_reg_198 <= col_4_fu_372_p2;
            elsif (((icmp_ln27_fu_342_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                col_1_reg_198 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    col_2_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln40_fu_442_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                col_2_reg_220 <= col_6_reg_616;
            elsif (((icmp_ln37_fu_392_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                col_2_reg_220 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    col_3_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state22) and (out_C_V_data_1_ack_in = ap_const_logic_1))) then 
                col_3_reg_266 <= col_5_reg_690;
            elsif ((not(((out_C_V_last_V_1_state = ap_const_lv2_1) or (out_C_V_data_1_state = ap_const_lv2_1) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)))) and (icmp_ln48_fu_490_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
                col_3_reg_266 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    index_0_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                index_0_reg_231 <= index_reg_634;
            elsif (((icmp_ln38_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                index_0_reg_231 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    res_0_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                res_0_reg_242 <= grp_fu_277_p2;
            elsif (((icmp_ln38_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                res_0_reg_242 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    row_0_reg_165_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln20_fu_316_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                row_0_reg_165 <= row_reg_560;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                row_0_reg_165 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    row_1_reg_187_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln18_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                row_1_reg_187 <= ap_const_lv4_0;
            elsif ((not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln29_fu_366_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                row_1_reg_187 <= row_4_reg_581;
            end if; 
        end if;
    end process;

    row_2_reg_209_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln27_fu_342_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                row_2_reg_209 <= ap_const_lv4_0;
            elsif (((icmp_ln38_fu_416_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                row_2_reg_209 <= row_5_reg_602;
            end if; 
        end if;
    end process;

    row_3_reg_255_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln37_fu_392_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                row_3_reg_255 <= ap_const_lv4_0;
            elsif (((icmp_ln49_fu_520_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
                row_3_reg_255 <= row_6_reg_672;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                col_5_reg_690 <= col_5_fu_526_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                col_6_reg_616 <= col_6_fu_422_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((out_C_V_last_V_1_state = ap_const_lv2_1) or (out_C_V_data_1_state = ap_const_lv2_1) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)))) and (icmp_ln48_fu_490_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                icmp_ln52_reg_682 <= icmp_ln52_fu_514_p2;
                    zext_ln52_reg_677(6 downto 3) <= zext_ln52_fu_510_p1(6 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_A_V_data_0_load_A = ap_const_logic_1)) then
                in_A_V_data_0_payload_A <= in_A_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_A_V_data_0_load_B = ap_const_logic_1)) then
                in_A_V_data_0_payload_B <= in_A_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                index_reg_634 <= index_fu_448_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                input_A_load_reg_649 <= input_A_q0;
                input_B_load_reg_654 <= input_B_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_C_V_data_1_load_A = ap_const_logic_1)) then
                out_C_V_data_1_payload_A <= output_C_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_C_V_data_1_load_B = ap_const_logic_1)) then
                out_C_V_data_1_payload_B <= output_C_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_C_V_last_V_1_load_A = ap_const_logic_1)) then
                out_C_V_last_V_1_payload_A <= tmp_last_V_reg_700;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_C_V_last_V_1_load_B = ap_const_logic_1)) then
                out_C_V_last_V_1_payload_B <= tmp_last_V_reg_700;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                output_C_addr_1_reg_626 <= zext_ln43_1_fu_437_p1(6 - 1 downto 0);
                    zext_ln43_reg_621(3 downto 0) <= zext_ln43_fu_428_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                row_4_reg_581 <= row_4_fu_348_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                row_5_reg_602 <= row_5_fu_398_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((out_C_V_last_V_1_state = ap_const_lv2_1) or (out_C_V_data_1_state = ap_const_lv2_1) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                row_6_reg_672 <= row_6_fu_496_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                row_reg_560 <= row_fu_298_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                tmp_3_reg_659 <= grp_fu_282_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_520_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                tmp_last_V_reg_700 <= tmp_last_V_fu_552_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln18_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    zext_ln20_reg_565(6 downto 3) <= zext_ln20_fu_312_p1(6 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln27_fu_342_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    zext_ln29_reg_586(6 downto 3) <= zext_ln29_fu_362_p1(6 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln37_fu_392_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    zext_ln38_reg_607(6 downto 3) <= zext_ln38_fu_412_p1(6 downto 3);
            end if;
        end if;
    end process;
    zext_ln20_reg_565(2 downto 0) <= "000";
    zext_ln20_reg_565(7) <= '0';
    zext_ln29_reg_586(2 downto 0) <= "000";
    zext_ln29_reg_586(7) <= '0';
    zext_ln38_reg_607(2 downto 0) <= "000";
    zext_ln38_reg_607(7) <= '0';
    zext_ln43_reg_621(7 downto 4) <= "0000";
    zext_ln52_reg_677(2 downto 0) <= "000";
    zext_ln52_reg_677(7) <= '0';

    ap_NS_fsm_assign_proc : process (in_A_V_data_0_vld_out, out_C_TREADY, out_C_V_data_1_ack_in, out_C_V_data_1_state, out_C_V_last_V_1_state, ap_CS_fsm, ap_CS_fsm_state3, icmp_ln20_fu_316_p2, ap_CS_fsm_state5, icmp_ln29_fu_366_p2, ap_CS_fsm_state21, ap_CS_fsm_state22, ap_CS_fsm_state2, icmp_ln18_fu_292_p2, ap_CS_fsm_state4, icmp_ln27_fu_342_p2, ap_CS_fsm_state6, icmp_ln37_fu_392_p2, ap_CS_fsm_state7, icmp_ln38_fu_416_p2, ap_CS_fsm_state8, icmp_ln40_fu_442_p2, ap_CS_fsm_state19, icmp_ln48_fu_490_p2, ap_CS_fsm_state20, icmp_ln49_fu_520_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln18_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln20_fu_316_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln27_fu_342_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln29_fu_366_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif ((not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln37_fu_392_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln38_fu_416_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((icmp_ln40_fu_442_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state19 => 
                if ((not(((out_C_V_last_V_1_state = ap_const_lv2_1) or (out_C_V_data_1_state = ap_const_lv2_1) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)))) and (icmp_ln48_fu_490_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((out_C_V_last_V_1_state = ap_const_lv2_1) or (out_C_V_data_1_state = ap_const_lv2_1) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)))) and (icmp_ln48_fu_490_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                if (((icmp_ln49_fu_520_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state21 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state21) and (out_C_V_data_1_ack_in = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state22 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state22) and (out_C_V_data_1_ack_in = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln23_fu_332_p2 <= std_logic_vector(unsigned(zext_ln20_reg_565) + unsigned(zext_ln23_fu_328_p1));
    add_ln32_fu_382_p2 <= std_logic_vector(unsigned(zext_ln29_reg_586) + unsigned(zext_ln32_fu_378_p1));
    add_ln41_1_fu_480_p2 <= std_logic_vector(unsigned(zext_ln43_reg_621) + unsigned(zext_ln41_2_fu_476_p1));
    add_ln41_fu_458_p2 <= std_logic_vector(unsigned(zext_ln41_fu_454_p1) + unsigned(zext_ln38_reg_607));
    add_ln43_fu_432_p2 <= std_logic_vector(unsigned(zext_ln38_reg_607) + unsigned(zext_ln43_fu_428_p1));
    add_ln50_fu_536_p2 <= std_logic_vector(unsigned(zext_ln52_reg_677) + unsigned(zext_ln50_fu_532_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state19_assign_proc : process(out_C_TREADY, out_C_V_data_1_state, out_C_V_last_V_1_state)
    begin
                ap_block_state19 <= ((out_C_V_last_V_1_state = ap_const_lv2_1) or (out_C_V_data_1_state = ap_const_lv2_1) or ((out_C_V_last_V_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)) or ((out_C_V_data_1_state = ap_const_lv2_3) and (out_C_TREADY = ap_const_logic_0)));
    end process;


    ap_block_state3_assign_proc : process(in_A_V_data_0_vld_out, icmp_ln20_fu_316_p2)
    begin
                ap_block_state3 <= ((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(in_A_V_data_0_vld_out, icmp_ln29_fu_366_p2)
    begin
                ap_block_state5 <= ((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    col_4_fu_372_p2 <= std_logic_vector(unsigned(col_1_reg_198) + unsigned(ap_const_lv4_1));
    col_5_fu_526_p2 <= std_logic_vector(unsigned(col_3_reg_266) + unsigned(ap_const_lv4_1));
    col_6_fu_422_p2 <= std_logic_vector(unsigned(col_2_reg_220) + unsigned(ap_const_lv4_1));
    col_fu_322_p2 <= std_logic_vector(unsigned(col_0_reg_176) + unsigned(ap_const_lv4_1));
    icmp_ln18_fu_292_p2 <= "1" when (row_0_reg_165 = ap_const_lv4_8) else "0";
    icmp_ln20_fu_316_p2 <= "1" when (col_0_reg_176 = ap_const_lv4_8) else "0";
    icmp_ln27_fu_342_p2 <= "1" when (row_1_reg_187 = ap_const_lv4_8) else "0";
    icmp_ln29_fu_366_p2 <= "1" when (col_1_reg_198 = ap_const_lv4_8) else "0";
    icmp_ln37_fu_392_p2 <= "1" when (row_2_reg_209 = ap_const_lv4_8) else "0";
    icmp_ln38_fu_416_p2 <= "1" when (col_2_reg_220 = ap_const_lv4_8) else "0";
    icmp_ln40_fu_442_p2 <= "1" when (index_0_reg_231 = ap_const_lv4_8) else "0";
    icmp_ln48_fu_490_p2 <= "1" when (row_3_reg_255 = ap_const_lv4_8) else "0";
    icmp_ln49_fu_520_p2 <= "1" when (col_3_reg_266 = ap_const_lv4_8) else "0";
    icmp_ln52_1_fu_546_p2 <= "1" when (col_3_reg_266 = ap_const_lv4_7) else "0";
    icmp_ln52_fu_514_p2 <= "1" when (row_3_reg_255 = ap_const_lv4_7) else "0";

    in_A_TDATA_blk_n_assign_proc : process(in_A_V_data_0_state, ap_CS_fsm_state3, icmp_ln20_fu_316_p2, ap_CS_fsm_state5, icmp_ln29_fu_366_p2)
    begin
        if ((((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            in_A_TDATA_blk_n <= in_A_V_data_0_state(0);
        else 
            in_A_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_A_TREADY <= in_A_V_last_V_0_state(1);
    in_A_V_data_0_ack_in <= in_A_V_data_0_state(1);

    in_A_V_data_0_ack_out_assign_proc : process(in_A_V_data_0_vld_out, ap_CS_fsm_state3, icmp_ln20_fu_316_p2, ap_CS_fsm_state5, icmp_ln29_fu_366_p2)
    begin
        if (((not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            in_A_V_data_0_ack_out <= ap_const_logic_1;
        else 
            in_A_V_data_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    in_A_V_data_0_data_out_assign_proc : process(in_A_V_data_0_payload_A, in_A_V_data_0_payload_B, in_A_V_data_0_sel)
    begin
        if ((in_A_V_data_0_sel = ap_const_logic_1)) then 
            in_A_V_data_0_data_out <= in_A_V_data_0_payload_B;
        else 
            in_A_V_data_0_data_out <= in_A_V_data_0_payload_A;
        end if; 
    end process;

    in_A_V_data_0_load_A <= (in_A_V_data_0_state_cmp_full and not(in_A_V_data_0_sel_wr));
    in_A_V_data_0_load_B <= (in_A_V_data_0_state_cmp_full and in_A_V_data_0_sel_wr);
    in_A_V_data_0_sel <= in_A_V_data_0_sel_rd;
    in_A_V_data_0_state_cmp_full <= '0' when (in_A_V_data_0_state = ap_const_lv2_1) else '1';
    in_A_V_data_0_vld_in <= in_A_TVALID;
    in_A_V_data_0_vld_out <= in_A_V_data_0_state(0);

    in_A_V_last_V_0_ack_out_assign_proc : process(in_A_V_data_0_vld_out, ap_CS_fsm_state3, icmp_ln20_fu_316_p2, ap_CS_fsm_state5, icmp_ln29_fu_366_p2)
    begin
        if (((not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            in_A_V_last_V_0_ack_out <= ap_const_logic_1;
        else 
            in_A_V_last_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    in_A_V_last_V_0_vld_in <= in_A_TVALID;
    index_fu_448_p2 <= std_logic_vector(unsigned(index_0_reg_231) + unsigned(ap_const_lv4_1));

    input_A_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state8, zext_ln23_1_fu_337_p1, zext_ln41_1_fu_463_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            input_A_address0 <= zext_ln41_1_fu_463_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_address0 <= zext_ln23_1_fu_337_p1(6 - 1 downto 0);
        else 
            input_A_address0 <= "XXXXXX";
        end if; 
    end process;


    input_A_ce0_assign_proc : process(in_A_V_data_0_vld_out, ap_CS_fsm_state3, icmp_ln20_fu_316_p2, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            input_A_ce0 <= ap_const_logic_1;
        else 
            input_A_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_we0_assign_proc : process(in_A_V_data_0_vld_out, ap_CS_fsm_state3, icmp_ln20_fu_316_p2)
    begin
        if ((not(((icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln20_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            input_A_we0 <= ap_const_logic_1;
        else 
            input_A_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state8, zext_ln32_1_fu_387_p1, zext_ln41_3_fu_485_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            input_B_address0 <= zext_ln41_3_fu_485_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_address0 <= zext_ln32_1_fu_387_p1(6 - 1 downto 0);
        else 
            input_B_address0 <= "XXXXXX";
        end if; 
    end process;


    input_B_ce0_assign_proc : process(in_A_V_data_0_vld_out, ap_CS_fsm_state5, icmp_ln29_fu_366_p2, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            input_B_ce0 <= ap_const_logic_1;
        else 
            input_B_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_we0_assign_proc : process(in_A_V_data_0_vld_out, ap_CS_fsm_state5, icmp_ln29_fu_366_p2)
    begin
        if ((not(((icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (in_A_V_data_0_vld_out = ap_const_logic_0))) and (icmp_ln29_fu_366_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            input_B_we0 <= ap_const_logic_1;
        else 
            input_B_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_C_TDATA <= out_C_V_data_1_data_out;

    out_C_TDATA_blk_n_assign_proc : process(out_C_V_data_1_state, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21))) then 
            out_C_TDATA_blk_n <= out_C_V_data_1_state(1);
        else 
            out_C_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_C_TLAST <= out_C_V_last_V_1_data_out;
    out_C_TVALID <= out_C_V_last_V_1_state(0);
    out_C_V_data_1_ack_in <= out_C_V_data_1_state(1);
    out_C_V_data_1_ack_out <= out_C_TREADY;

    out_C_V_data_1_data_out_assign_proc : process(out_C_V_data_1_payload_A, out_C_V_data_1_payload_B, out_C_V_data_1_sel)
    begin
        if ((out_C_V_data_1_sel = ap_const_logic_1)) then 
            out_C_V_data_1_data_out <= out_C_V_data_1_payload_B;
        else 
            out_C_V_data_1_data_out <= out_C_V_data_1_payload_A;
        end if; 
    end process;

    out_C_V_data_1_load_A <= (out_C_V_data_1_state_cmp_full and not(out_C_V_data_1_sel_wr));
    out_C_V_data_1_load_B <= (out_C_V_data_1_state_cmp_full and out_C_V_data_1_sel_wr);
    out_C_V_data_1_sel <= out_C_V_data_1_sel_rd;
    out_C_V_data_1_state_cmp_full <= '0' when (out_C_V_data_1_state = ap_const_lv2_1) else '1';

    out_C_V_data_1_vld_in_assign_proc : process(out_C_V_data_1_ack_in, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) and (out_C_V_data_1_ack_in = ap_const_logic_1))) then 
            out_C_V_data_1_vld_in <= ap_const_logic_1;
        else 
            out_C_V_data_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_C_V_data_1_vld_out <= out_C_V_data_1_state(0);
    out_C_V_last_V_1_ack_in <= out_C_V_last_V_1_state(1);
    out_C_V_last_V_1_ack_out <= out_C_TREADY;

    out_C_V_last_V_1_data_out_assign_proc : process(out_C_V_last_V_1_payload_A, out_C_V_last_V_1_payload_B, out_C_V_last_V_1_sel)
    begin
        if ((out_C_V_last_V_1_sel = ap_const_logic_1)) then 
            out_C_V_last_V_1_data_out <= out_C_V_last_V_1_payload_B;
        else 
            out_C_V_last_V_1_data_out <= out_C_V_last_V_1_payload_A;
        end if; 
    end process;

    out_C_V_last_V_1_load_A <= (out_C_V_last_V_1_state_cmp_full and not(out_C_V_last_V_1_sel_wr));
    out_C_V_last_V_1_load_B <= (out_C_V_last_V_1_state_cmp_full and out_C_V_last_V_1_sel_wr);
    out_C_V_last_V_1_sel <= out_C_V_last_V_1_sel_rd;
    out_C_V_last_V_1_state_cmp_full <= '0' when (out_C_V_last_V_1_state = ap_const_lv2_1) else '1';

    out_C_V_last_V_1_vld_in_assign_proc : process(out_C_V_data_1_ack_in, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) and (out_C_V_data_1_ack_in = ap_const_logic_1))) then 
            out_C_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            out_C_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_C_V_last_V_1_vld_out <= out_C_V_last_V_1_state(0);

    output_C_address0_assign_proc : process(output_C_addr_1_reg_626, ap_CS_fsm_state8, ap_CS_fsm_state20, zext_ln50_1_fu_541_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            output_C_address0 <= zext_ln50_1_fu_541_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_C_address0 <= output_C_addr_1_reg_626;
        else 
            output_C_address0 <= "XXXXXX";
        end if; 
    end process;


    output_C_ce0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            output_C_ce0 <= ap_const_logic_1;
        else 
            output_C_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_C_we0_assign_proc : process(ap_CS_fsm_state8, icmp_ln40_fu_442_p2)
    begin
        if (((icmp_ln40_fu_442_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            output_C_we0 <= ap_const_logic_1;
        else 
            output_C_we0 <= ap_const_logic_0;
        end if; 
    end process;

    row_4_fu_348_p2 <= std_logic_vector(unsigned(row_1_reg_187) + unsigned(ap_const_lv4_1));
    row_5_fu_398_p2 <= std_logic_vector(unsigned(row_2_reg_209) + unsigned(ap_const_lv4_1));
    row_6_fu_496_p2 <= std_logic_vector(unsigned(row_3_reg_255) + unsigned(ap_const_lv4_1));
    row_fu_298_p2 <= std_logic_vector(unsigned(row_0_reg_165) + unsigned(ap_const_lv4_1));
    tmp_6_fu_304_p3 <= (row_0_reg_165 & ap_const_lv3_0);
    tmp_7_fu_354_p3 <= (row_1_reg_187 & ap_const_lv3_0);
    tmp_8_fu_404_p3 <= (row_2_reg_209 & ap_const_lv3_0);
    tmp_9_fu_502_p3 <= (row_3_reg_255 & ap_const_lv3_0);
    tmp_last_V_fu_552_p2 <= (icmp_ln52_reg_682 and icmp_ln52_1_fu_546_p2);
    tmp_s_fu_468_p3 <= (index_0_reg_231 & ap_const_lv3_0);
    zext_ln20_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_304_p3),8));
    zext_ln23_1_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln23_fu_332_p2),64));
    zext_ln23_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_0_reg_176),8));
    zext_ln29_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_354_p3),8));
    zext_ln32_1_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_fu_382_p2),64));
    zext_ln32_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_1_reg_198),8));
    zext_ln38_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_404_p3),8));
    zext_ln41_1_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln41_fu_458_p2),64));
    zext_ln41_2_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_468_p3),8));
    zext_ln41_3_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln41_1_fu_480_p2),64));
    zext_ln41_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_0_reg_231),8));
    zext_ln43_1_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_fu_432_p2),64));
    zext_ln43_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_2_reg_220),8));
    zext_ln50_1_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln50_fu_536_p2),64));
    zext_ln50_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_3_reg_266),8));
    zext_ln52_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_502_p3),8));
end behav;
