// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixmul_1,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=6148,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=5,HLS_SYN_FF=734,HLS_SYN_LUT=1428,HLS_VERSION=2019_1}" *)

module matrixmul_1 (
        ap_clk,
        ap_rst_n,
        in_A_TDATA,
        in_A_TVALID,
        in_A_TREADY,
        in_A_TLAST,
        out_C_TDATA,
        out_C_TVALID,
        out_C_TREADY,
        out_C_TLAST
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_A_TDATA;
input   in_A_TVALID;
output   in_A_TREADY;
input  [0:0] in_A_TLAST;
output  [31:0] out_C_TDATA;
output   out_C_TVALID;
input   out_C_TREADY;
output  [0:0] out_C_TLAST;

 reg    ap_rst_n_inv;
reg   [31:0] in_A_V_data_0_data_out;
wire    in_A_V_data_0_vld_in;
wire    in_A_V_data_0_vld_out;
wire    in_A_V_data_0_ack_in;
reg    in_A_V_data_0_ack_out;
reg   [31:0] in_A_V_data_0_payload_A;
reg   [31:0] in_A_V_data_0_payload_B;
reg    in_A_V_data_0_sel_rd;
reg    in_A_V_data_0_sel_wr;
wire    in_A_V_data_0_sel;
wire    in_A_V_data_0_load_A;
wire    in_A_V_data_0_load_B;
reg   [1:0] in_A_V_data_0_state;
wire    in_A_V_data_0_state_cmp_full;
wire    in_A_V_last_V_0_vld_in;
reg    in_A_V_last_V_0_ack_out;
reg   [1:0] in_A_V_last_V_0_state;
reg   [31:0] out_C_V_data_1_data_out;
reg    out_C_V_data_1_vld_in;
wire    out_C_V_data_1_vld_out;
wire    out_C_V_data_1_ack_in;
wire    out_C_V_data_1_ack_out;
reg   [31:0] out_C_V_data_1_payload_A;
reg   [31:0] out_C_V_data_1_payload_B;
reg    out_C_V_data_1_sel_rd;
reg    out_C_V_data_1_sel_wr;
wire    out_C_V_data_1_sel;
wire    out_C_V_data_1_load_A;
wire    out_C_V_data_1_load_B;
reg   [1:0] out_C_V_data_1_state;
wire    out_C_V_data_1_state_cmp_full;
reg   [0:0] out_C_V_last_V_1_data_out;
reg    out_C_V_last_V_1_vld_in;
wire    out_C_V_last_V_1_vld_out;
wire    out_C_V_last_V_1_ack_in;
wire    out_C_V_last_V_1_ack_out;
reg   [0:0] out_C_V_last_V_1_payload_A;
reg   [0:0] out_C_V_last_V_1_payload_B;
reg    out_C_V_last_V_1_sel_rd;
reg    out_C_V_last_V_1_sel_wr;
wire    out_C_V_last_V_1_sel;
wire    out_C_V_last_V_1_load_A;
wire    out_C_V_last_V_1_load_B;
reg   [1:0] out_C_V_last_V_1_state;
wire    out_C_V_last_V_1_state_cmp_full;
reg    in_A_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln20_fu_316_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln29_fu_366_p2;
reg    out_C_TDATA_blk_n;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire   [3:0] row_fu_298_p2;
reg   [3:0] row_reg_560;
wire    ap_CS_fsm_state2;
wire   [7:0] zext_ln20_fu_312_p1;
reg   [7:0] zext_ln20_reg_565;
wire   [0:0] icmp_ln18_fu_292_p2;
wire   [3:0] col_fu_322_p2;
reg    ap_block_state3;
wire   [3:0] row_4_fu_348_p2;
reg   [3:0] row_4_reg_581;
wire    ap_CS_fsm_state4;
wire   [7:0] zext_ln29_fu_362_p1;
reg   [7:0] zext_ln29_reg_586;
wire   [0:0] icmp_ln27_fu_342_p2;
wire   [3:0] col_4_fu_372_p2;
reg    ap_block_state5;
wire   [3:0] row_5_fu_398_p2;
reg   [3:0] row_5_reg_602;
wire    ap_CS_fsm_state6;
wire   [7:0] zext_ln38_fu_412_p1;
reg   [7:0] zext_ln38_reg_607;
wire   [0:0] icmp_ln37_fu_392_p2;
wire   [3:0] col_6_fu_422_p2;
reg   [3:0] col_6_reg_616;
wire    ap_CS_fsm_state7;
wire   [7:0] zext_ln43_fu_428_p1;
reg   [7:0] zext_ln43_reg_621;
wire   [0:0] icmp_ln38_fu_416_p2;
reg   [5:0] output_C_addr_1_reg_626;
wire   [3:0] index_fu_448_p2;
reg   [3:0] index_reg_634;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln40_fu_442_p2;
wire   [31:0] input_A_q0;
reg   [31:0] input_A_load_reg_649;
wire    ap_CS_fsm_state9;
wire   [31:0] input_B_q0;
reg   [31:0] input_B_load_reg_654;
wire   [31:0] grp_fu_282_p2;
reg   [31:0] tmp_3_reg_659;
wire    ap_CS_fsm_state13;
wire   [31:0] grp_fu_277_p2;
wire    ap_CS_fsm_state18;
wire   [3:0] row_6_fu_496_p2;
reg   [3:0] row_6_reg_672;
wire    ap_CS_fsm_state19;
reg    ap_block_state19;
wire   [7:0] zext_ln52_fu_510_p1;
reg   [7:0] zext_ln52_reg_677;
wire   [0:0] icmp_ln48_fu_490_p2;
wire   [0:0] icmp_ln52_fu_514_p2;
reg   [0:0] icmp_ln52_reg_682;
wire   [3:0] col_5_fu_526_p2;
reg   [3:0] col_5_reg_690;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln49_fu_520_p2;
wire   [0:0] tmp_last_V_fu_552_p2;
reg   [0:0] tmp_last_V_reg_700;
wire   [31:0] output_C_q0;
reg   [5:0] input_A_address0;
reg    input_A_ce0;
reg    input_A_we0;
reg   [5:0] input_B_address0;
reg    input_B_ce0;
reg    input_B_we0;
reg   [5:0] output_C_address0;
reg    output_C_ce0;
reg    output_C_we0;
reg   [3:0] row_0_reg_165;
wire    ap_CS_fsm_state1;
reg   [3:0] col_0_reg_176;
reg   [3:0] row_1_reg_187;
reg   [3:0] col_1_reg_198;
reg   [3:0] row_2_reg_209;
reg   [3:0] col_2_reg_220;
reg   [3:0] index_0_reg_231;
reg   [31:0] res_0_reg_242;
reg   [3:0] row_3_reg_255;
reg   [3:0] col_3_reg_266;
wire   [63:0] zext_ln23_1_fu_337_p1;
wire   [63:0] zext_ln32_1_fu_387_p1;
wire   [63:0] zext_ln43_1_fu_437_p1;
wire   [63:0] zext_ln41_1_fu_463_p1;
wire   [63:0] zext_ln41_3_fu_485_p1;
wire   [63:0] zext_ln50_1_fu_541_p1;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state10;
wire   [6:0] tmp_6_fu_304_p3;
wire   [7:0] zext_ln23_fu_328_p1;
wire   [7:0] add_ln23_fu_332_p2;
wire   [6:0] tmp_7_fu_354_p3;
wire   [7:0] zext_ln32_fu_378_p1;
wire   [7:0] add_ln32_fu_382_p2;
wire   [6:0] tmp_8_fu_404_p3;
wire   [7:0] add_ln43_fu_432_p2;
wire   [7:0] zext_ln41_fu_454_p1;
wire   [7:0] add_ln41_fu_458_p2;
wire   [6:0] tmp_s_fu_468_p3;
wire   [7:0] zext_ln41_2_fu_476_p1;
wire   [7:0] add_ln41_1_fu_480_p2;
wire   [6:0] tmp_9_fu_502_p3;
wire   [7:0] zext_ln50_fu_532_p1;
wire   [7:0] add_ln50_fu_536_p2;
wire   [0:0] icmp_ln52_1_fu_546_p2;
reg   [21:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 in_A_V_data_0_sel_rd = 1'b0;
#0 in_A_V_data_0_sel_wr = 1'b0;
#0 in_A_V_data_0_state = 2'd0;
#0 in_A_V_last_V_0_state = 2'd0;
#0 out_C_V_data_1_sel_rd = 1'b0;
#0 out_C_V_data_1_sel_wr = 1'b0;
#0 out_C_V_data_1_state = 2'd0;
#0 out_C_V_last_V_1_sel_rd = 1'b0;
#0 out_C_V_last_V_1_sel_wr = 1'b0;
#0 out_C_V_last_V_1_state = 2'd0;
#0 ap_CS_fsm = 22'd1;
end

matrixmul_1_input_A #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
input_A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_A_address0),
    .ce0(input_A_ce0),
    .we0(input_A_we0),
    .d0(in_A_V_data_0_data_out),
    .q0(input_A_q0)
);

matrixmul_1_input_A #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
input_B_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_B_address0),
    .ce0(input_B_ce0),
    .we0(input_B_we0),
    .d0(in_A_V_data_0_data_out),
    .q0(input_B_q0)
);

matrixmul_1_input_A #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
output_C_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_C_address0),
    .ce0(output_C_ce0),
    .we0(output_C_we0),
    .d0(res_0_reg_242),
    .q0(output_C_q0)
);

matrixmul_1_fadd_cud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matrixmul_1_fadd_cud_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(res_0_reg_242),
    .din1(tmp_3_reg_659),
    .ce(1'b1),
    .dout(grp_fu_277_p2)
);

matrixmul_1_fmul_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matrixmul_1_fmul_dEe_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(input_A_load_reg_649),
    .din1(input_B_load_reg_654),
    .ce(1'b1),
    .dout(grp_fu_282_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_data_0_sel_rd <= 1'b0;
    end else begin
        if (((in_A_V_data_0_ack_out == 1'b1) & (in_A_V_data_0_vld_out == 1'b1))) begin
            in_A_V_data_0_sel_rd <= ~in_A_V_data_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_data_0_sel_wr <= 1'b0;
    end else begin
        if (((in_A_V_data_0_ack_in == 1'b1) & (in_A_V_data_0_vld_in == 1'b1))) begin
            in_A_V_data_0_sel_wr <= ~in_A_V_data_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_data_0_state <= 2'd0;
    end else begin
        if ((((in_A_V_data_0_state == 2'd2) & (in_A_V_data_0_vld_in == 1'b0)) | ((in_A_V_data_0_state == 2'd3) & (in_A_V_data_0_vld_in == 1'b0) & (in_A_V_data_0_ack_out == 1'b1)))) begin
            in_A_V_data_0_state <= 2'd2;
        end else if ((((in_A_V_data_0_state == 2'd1) & (in_A_V_data_0_ack_out == 1'b0)) | ((in_A_V_data_0_state == 2'd3) & (in_A_V_data_0_ack_out == 1'b0) & (in_A_V_data_0_vld_in == 1'b1)))) begin
            in_A_V_data_0_state <= 2'd1;
        end else if (((~((in_A_V_data_0_vld_in == 1'b0) & (in_A_V_data_0_ack_out == 1'b1)) & ~((in_A_V_data_0_ack_out == 1'b0) & (in_A_V_data_0_vld_in == 1'b1)) & (in_A_V_data_0_state == 2'd3)) | ((in_A_V_data_0_state == 2'd1) & (in_A_V_data_0_ack_out == 1'b1)) | ((in_A_V_data_0_state == 2'd2) & (in_A_V_data_0_vld_in == 1'b1)))) begin
            in_A_V_data_0_state <= 2'd3;
        end else begin
            in_A_V_data_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_A_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((in_A_V_last_V_0_state == 2'd2) & (in_A_V_last_V_0_vld_in == 1'b0)) | ((in_A_V_last_V_0_state == 2'd3) & (in_A_V_last_V_0_vld_in == 1'b0) & (in_A_V_last_V_0_ack_out == 1'b1)))) begin
            in_A_V_last_V_0_state <= 2'd2;
        end else if ((((in_A_V_last_V_0_state == 2'd1) & (in_A_V_last_V_0_ack_out == 1'b0)) | ((in_A_V_last_V_0_state == 2'd3) & (in_A_V_last_V_0_ack_out == 1'b0) & (in_A_V_last_V_0_vld_in == 1'b1)))) begin
            in_A_V_last_V_0_state <= 2'd1;
        end else if (((~((in_A_V_last_V_0_vld_in == 1'b0) & (in_A_V_last_V_0_ack_out == 1'b1)) & ~((in_A_V_last_V_0_ack_out == 1'b0) & (in_A_V_last_V_0_vld_in == 1'b1)) & (in_A_V_last_V_0_state == 2'd3)) | ((in_A_V_last_V_0_state == 2'd1) & (in_A_V_last_V_0_ack_out == 1'b1)) | ((in_A_V_last_V_0_state == 2'd2) & (in_A_V_last_V_0_vld_in == 1'b1)))) begin
            in_A_V_last_V_0_state <= 2'd3;
        end else begin
            in_A_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((out_C_V_data_1_ack_out == 1'b1) & (out_C_V_data_1_vld_out == 1'b1))) begin
            out_C_V_data_1_sel_rd <= ~out_C_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((out_C_V_data_1_ack_in == 1'b1) & (out_C_V_data_1_vld_in == 1'b1))) begin
            out_C_V_data_1_sel_wr <= ~out_C_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_data_1_state <= 2'd0;
    end else begin
        if ((((out_C_V_data_1_state == 2'd2) & (out_C_V_data_1_vld_in == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_V_data_1_vld_in == 1'b0) & (out_C_V_data_1_ack_out == 1'b1)))) begin
            out_C_V_data_1_state <= 2'd2;
        end else if ((((out_C_V_data_1_state == 2'd1) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0) & (out_C_V_data_1_vld_in == 1'b1)))) begin
            out_C_V_data_1_state <= 2'd1;
        end else if (((~((out_C_V_data_1_vld_in == 1'b0) & (out_C_V_data_1_ack_out == 1'b1)) & ~((out_C_TREADY == 1'b0) & (out_C_V_data_1_vld_in == 1'b1)) & (out_C_V_data_1_state == 2'd3)) | ((out_C_V_data_1_state == 2'd1) & (out_C_V_data_1_ack_out == 1'b1)) | ((out_C_V_data_1_state == 2'd2) & (out_C_V_data_1_vld_in == 1'b1)))) begin
            out_C_V_data_1_state <= 2'd3;
        end else begin
            out_C_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_C_V_last_V_1_ack_out == 1'b1) & (out_C_V_last_V_1_vld_out == 1'b1))) begin
            out_C_V_last_V_1_sel_rd <= ~out_C_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((out_C_V_last_V_1_ack_in == 1'b1) & (out_C_V_last_V_1_vld_in == 1'b1))) begin
            out_C_V_last_V_1_sel_wr <= ~out_C_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_C_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((out_C_V_last_V_1_state == 2'd2) & (out_C_V_last_V_1_vld_in == 1'b0)) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_V_last_V_1_vld_in == 1'b0) & (out_C_V_last_V_1_ack_out == 1'b1)))) begin
            out_C_V_last_V_1_state <= 2'd2;
        end else if ((((out_C_V_last_V_1_state == 2'd1) & (out_C_TREADY == 1'b0)) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0) & (out_C_V_last_V_1_vld_in == 1'b1)))) begin
            out_C_V_last_V_1_state <= 2'd1;
        end else if (((~((out_C_V_last_V_1_vld_in == 1'b0) & (out_C_V_last_V_1_ack_out == 1'b1)) & ~((out_C_TREADY == 1'b0) & (out_C_V_last_V_1_vld_in == 1'b1)) & (out_C_V_last_V_1_state == 2'd3)) | ((out_C_V_last_V_1_state == 2'd1) & (out_C_V_last_V_1_ack_out == 1'b1)) | ((out_C_V_last_V_1_state == 2'd2) & (out_C_V_last_V_1_vld_in == 1'b1)))) begin
            out_C_V_last_V_1_state <= 2'd3;
        end else begin
            out_C_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln20_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        col_0_reg_176 <= col_fu_322_p2;
    end else if (((icmp_ln18_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_0_reg_176 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln29_fu_366_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        col_1_reg_198 <= col_4_fu_372_p2;
    end else if (((icmp_ln27_fu_342_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        col_1_reg_198 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln40_fu_442_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        col_2_reg_220 <= col_6_reg_616;
    end else if (((icmp_ln37_fu_392_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        col_2_reg_220 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state22) & (out_C_V_data_1_ack_in == 1'b1))) begin
        col_3_reg_266 <= col_5_reg_690;
    end else if ((~((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0))) & (icmp_ln48_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        col_3_reg_266 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        index_0_reg_231 <= index_reg_634;
    end else if (((icmp_ln38_fu_416_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        index_0_reg_231 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        res_0_reg_242 <= grp_fu_277_p2;
    end else if (((icmp_ln38_fu_416_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        res_0_reg_242 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln20_fu_316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        row_0_reg_165 <= row_reg_560;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        row_0_reg_165 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        row_1_reg_187 <= 4'd0;
    end else if ((~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln29_fu_366_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        row_1_reg_187 <= row_4_reg_581;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_342_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        row_2_reg_209 <= 4'd0;
    end else if (((icmp_ln38_fu_416_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        row_2_reg_209 <= row_5_reg_602;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_392_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        row_3_reg_255 <= 4'd0;
    end else if (((icmp_ln49_fu_520_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        row_3_reg_255 <= row_6_reg_672;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        col_5_reg_690 <= col_5_fu_526_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        col_6_reg_616 <= col_6_fu_422_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0))) & (icmp_ln48_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln52_reg_682 <= icmp_ln52_fu_514_p2;
        zext_ln52_reg_677[6 : 3] <= zext_ln52_fu_510_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((in_A_V_data_0_load_A == 1'b1)) begin
        in_A_V_data_0_payload_A <= in_A_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((in_A_V_data_0_load_B == 1'b1)) begin
        in_A_V_data_0_payload_B <= in_A_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        index_reg_634 <= index_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        input_A_load_reg_649 <= input_A_q0;
        input_B_load_reg_654 <= input_B_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_data_1_load_A == 1'b1)) begin
        out_C_V_data_1_payload_A <= output_C_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_data_1_load_B == 1'b1)) begin
        out_C_V_data_1_payload_B <= output_C_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_last_V_1_load_A == 1'b1)) begin
        out_C_V_last_V_1_payload_A <= tmp_last_V_reg_700;
    end
end

always @ (posedge ap_clk) begin
    if ((out_C_V_last_V_1_load_B == 1'b1)) begin
        out_C_V_last_V_1_payload_B <= tmp_last_V_reg_700;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_416_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        output_C_addr_1_reg_626 <= zext_ln43_1_fu_437_p1;
        zext_ln43_reg_621[3 : 0] <= zext_ln43_fu_428_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_4_reg_581 <= row_4_fu_348_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_5_reg_602 <= row_5_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state19))) begin
        row_6_reg_672 <= row_6_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_reg_560 <= row_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_3_reg_659 <= grp_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_520_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        tmp_last_V_reg_700 <= tmp_last_V_fu_552_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln20_reg_565[6 : 3] <= zext_ln20_fu_312_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_342_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        zext_ln29_reg_586[6 : 3] <= zext_ln29_fu_362_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_392_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        zext_ln38_reg_607[6 : 3] <= zext_ln38_fu_412_p1[6 : 3];
    end
end

always @ (*) begin
    if ((((icmp_ln29_fu_366_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln20_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        in_A_TDATA_blk_n = in_A_V_data_0_state[1'd0];
    end else begin
        in_A_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln29_fu_366_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln20_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        in_A_V_data_0_ack_out = 1'b1;
    end else begin
        in_A_V_data_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((in_A_V_data_0_sel == 1'b1)) begin
        in_A_V_data_0_data_out = in_A_V_data_0_payload_B;
    end else begin
        in_A_V_data_0_data_out = in_A_V_data_0_payload_A;
    end
end

always @ (*) begin
    if (((~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln29_fu_366_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln20_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        in_A_V_last_V_0_ack_out = 1'b1;
    end else begin
        in_A_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_A_address0 = zext_ln41_1_fu_463_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_A_address0 = zext_ln23_1_fu_337_p1;
    end else begin
        input_A_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state3)))) begin
        input_A_ce0 = 1'b1;
    end else begin
        input_A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln20_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        input_A_we0 = 1'b1;
    end else begin
        input_A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_B_address0 = zext_ln41_3_fu_485_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_B_address0 = zext_ln32_1_fu_387_p1;
    end else begin
        input_B_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        input_B_ce0 = 1'b1;
    end else begin
        input_B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln29_fu_366_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        input_B_we0 = 1'b1;
    end else begin
        input_B_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        out_C_TDATA_blk_n = out_C_V_data_1_state[1'd1];
    end else begin
        out_C_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((out_C_V_data_1_sel == 1'b1)) begin
        out_C_V_data_1_data_out = out_C_V_data_1_payload_B;
    end else begin
        out_C_V_data_1_data_out = out_C_V_data_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (out_C_V_data_1_ack_in == 1'b1))) begin
        out_C_V_data_1_vld_in = 1'b1;
    end else begin
        out_C_V_data_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((out_C_V_last_V_1_sel == 1'b1)) begin
        out_C_V_last_V_1_data_out = out_C_V_last_V_1_payload_B;
    end else begin
        out_C_V_last_V_1_data_out = out_C_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (out_C_V_data_1_ack_in == 1'b1))) begin
        out_C_V_last_V_1_vld_in = 1'b1;
    end else begin
        out_C_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        output_C_address0 = zext_ln50_1_fu_541_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        output_C_address0 = output_C_addr_1_reg_626;
    end else begin
        output_C_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state8))) begin
        output_C_ce0 = 1'b1;
    end else begin
        output_C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln40_fu_442_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        output_C_we0 = 1'b1;
    end else begin
        output_C_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln18_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln20_fu_316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln20_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln27_fu_342_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln29_fu_366_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0)) & (icmp_ln29_fu_366_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln37_fu_392_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln38_fu_416_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln40_fu_442_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state19 : begin
            if ((~((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0))) & (icmp_ln48_fu_490_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0))) & (icmp_ln48_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln49_fu_520_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (out_C_V_data_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == ap_CS_fsm_state22) & (out_C_V_data_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_fu_332_p2 = (zext_ln20_reg_565 + zext_ln23_fu_328_p1);

assign add_ln32_fu_382_p2 = (zext_ln29_reg_586 + zext_ln32_fu_378_p1);

assign add_ln41_1_fu_480_p2 = (zext_ln43_reg_621 + zext_ln41_2_fu_476_p1);

assign add_ln41_fu_458_p2 = (zext_ln41_fu_454_p1 + zext_ln38_reg_607);

assign add_ln43_fu_432_p2 = (zext_ln38_reg_607 + zext_ln43_fu_428_p1);

assign add_ln50_fu_536_p2 = (zext_ln52_reg_677 + zext_ln50_fu_532_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state19 = ((out_C_V_last_V_1_state == 2'd1) | (out_C_V_data_1_state == 2'd1) | ((out_C_V_last_V_1_state == 2'd3) & (out_C_TREADY == 1'b0)) | ((out_C_V_data_1_state == 2'd3) & (out_C_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln20_fu_316_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((icmp_ln29_fu_366_p2 == 1'd0) & (in_A_V_data_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_4_fu_372_p2 = (col_1_reg_198 + 4'd1);

assign col_5_fu_526_p2 = (col_3_reg_266 + 4'd1);

assign col_6_fu_422_p2 = (col_2_reg_220 + 4'd1);

assign col_fu_322_p2 = (col_0_reg_176 + 4'd1);

assign icmp_ln18_fu_292_p2 = ((row_0_reg_165 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_316_p2 = ((col_0_reg_176 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_342_p2 = ((row_1_reg_187 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_366_p2 = ((col_1_reg_198 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_392_p2 = ((row_2_reg_209 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_416_p2 = ((col_2_reg_220 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_442_p2 = ((index_0_reg_231 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_490_p2 = ((row_3_reg_255 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_520_p2 = ((col_3_reg_266 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln52_1_fu_546_p2 = ((col_3_reg_266 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_514_p2 = ((row_3_reg_255 == 4'd7) ? 1'b1 : 1'b0);

assign in_A_TREADY = in_A_V_last_V_0_state[1'd1];

assign in_A_V_data_0_ack_in = in_A_V_data_0_state[1'd1];

assign in_A_V_data_0_load_A = (in_A_V_data_0_state_cmp_full & ~in_A_V_data_0_sel_wr);

assign in_A_V_data_0_load_B = (in_A_V_data_0_state_cmp_full & in_A_V_data_0_sel_wr);

assign in_A_V_data_0_sel = in_A_V_data_0_sel_rd;

assign in_A_V_data_0_state_cmp_full = ((in_A_V_data_0_state != 2'd1) ? 1'b1 : 1'b0);

assign in_A_V_data_0_vld_in = in_A_TVALID;

assign in_A_V_data_0_vld_out = in_A_V_data_0_state[1'd0];

assign in_A_V_last_V_0_vld_in = in_A_TVALID;

assign index_fu_448_p2 = (index_0_reg_231 + 4'd1);

assign out_C_TDATA = out_C_V_data_1_data_out;

assign out_C_TLAST = out_C_V_last_V_1_data_out;

assign out_C_TVALID = out_C_V_last_V_1_state[1'd0];

assign out_C_V_data_1_ack_in = out_C_V_data_1_state[1'd1];

assign out_C_V_data_1_ack_out = out_C_TREADY;

assign out_C_V_data_1_load_A = (out_C_V_data_1_state_cmp_full & ~out_C_V_data_1_sel_wr);

assign out_C_V_data_1_load_B = (out_C_V_data_1_state_cmp_full & out_C_V_data_1_sel_wr);

assign out_C_V_data_1_sel = out_C_V_data_1_sel_rd;

assign out_C_V_data_1_state_cmp_full = ((out_C_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_C_V_data_1_vld_out = out_C_V_data_1_state[1'd0];

assign out_C_V_last_V_1_ack_in = out_C_V_last_V_1_state[1'd1];

assign out_C_V_last_V_1_ack_out = out_C_TREADY;

assign out_C_V_last_V_1_load_A = (out_C_V_last_V_1_state_cmp_full & ~out_C_V_last_V_1_sel_wr);

assign out_C_V_last_V_1_load_B = (out_C_V_last_V_1_state_cmp_full & out_C_V_last_V_1_sel_wr);

assign out_C_V_last_V_1_sel = out_C_V_last_V_1_sel_rd;

assign out_C_V_last_V_1_state_cmp_full = ((out_C_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_C_V_last_V_1_vld_out = out_C_V_last_V_1_state[1'd0];

assign row_4_fu_348_p2 = (row_1_reg_187 + 4'd1);

assign row_5_fu_398_p2 = (row_2_reg_209 + 4'd1);

assign row_6_fu_496_p2 = (row_3_reg_255 + 4'd1);

assign row_fu_298_p2 = (row_0_reg_165 + 4'd1);

assign tmp_6_fu_304_p3 = {{row_0_reg_165}, {3'd0}};

assign tmp_7_fu_354_p3 = {{row_1_reg_187}, {3'd0}};

assign tmp_8_fu_404_p3 = {{row_2_reg_209}, {3'd0}};

assign tmp_9_fu_502_p3 = {{row_3_reg_255}, {3'd0}};

assign tmp_last_V_fu_552_p2 = (icmp_ln52_reg_682 & icmp_ln52_1_fu_546_p2);

assign tmp_s_fu_468_p3 = {{index_0_reg_231}, {3'd0}};

assign zext_ln20_fu_312_p1 = tmp_6_fu_304_p3;

assign zext_ln23_1_fu_337_p1 = add_ln23_fu_332_p2;

assign zext_ln23_fu_328_p1 = col_0_reg_176;

assign zext_ln29_fu_362_p1 = tmp_7_fu_354_p3;

assign zext_ln32_1_fu_387_p1 = add_ln32_fu_382_p2;

assign zext_ln32_fu_378_p1 = col_1_reg_198;

assign zext_ln38_fu_412_p1 = tmp_8_fu_404_p3;

assign zext_ln41_1_fu_463_p1 = add_ln41_fu_458_p2;

assign zext_ln41_2_fu_476_p1 = tmp_s_fu_468_p3;

assign zext_ln41_3_fu_485_p1 = add_ln41_1_fu_480_p2;

assign zext_ln41_fu_454_p1 = index_0_reg_231;

assign zext_ln43_1_fu_437_p1 = add_ln43_fu_432_p2;

assign zext_ln43_fu_428_p1 = col_2_reg_220;

assign zext_ln50_1_fu_541_p1 = add_ln50_fu_536_p2;

assign zext_ln50_fu_532_p1 = col_3_reg_266;

assign zext_ln52_fu_510_p1 = tmp_9_fu_502_p3;

always @ (posedge ap_clk) begin
    zext_ln20_reg_565[2:0] <= 3'b000;
    zext_ln20_reg_565[7] <= 1'b0;
    zext_ln29_reg_586[2:0] <= 3'b000;
    zext_ln29_reg_586[7] <= 1'b0;
    zext_ln38_reg_607[2:0] <= 3'b000;
    zext_ln38_reg_607[7] <= 1'b0;
    zext_ln43_reg_621[7:4] <= 4'b0000;
    zext_ln52_reg_677[2:0] <= 3'b000;
    zext_ln52_reg_677[7] <= 1'b0;
end

endmodule //matrixmul_1
