// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _demo_find_HH_
#define _demo_find_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct demo_find : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<8> > val_r_TDATA;
    sc_in< sc_logic > val_r_TVALID;
    sc_out< sc_logic > val_r_TREADY;
    sc_in< sc_lv<32> > in_vec_TDATA;
    sc_in< sc_logic > in_vec_TVALID;
    sc_out< sc_logic > in_vec_TREADY;
    sc_in< sc_lv<1> > in_vec_TLAST;
    sc_out< sc_lv<32> > out_vec_TDATA;
    sc_out< sc_logic > out_vec_TVALID;
    sc_in< sc_logic > out_vec_TREADY;
    sc_out< sc_lv<1> > out_vec_TLAST;


    // Module declarations
    demo_find(sc_module_name name);
    SC_HAS_PROCESS(demo_find);

    ~demo_find();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<8> > val_r_0_data_out;
    sc_signal< sc_logic > val_r_0_vld_in;
    sc_signal< sc_logic > val_r_0_vld_out;
    sc_signal< sc_logic > val_r_0_ack_in;
    sc_signal< sc_logic > val_r_0_ack_out;
    sc_signal< sc_lv<8> > val_r_0_payload_A;
    sc_signal< sc_lv<8> > val_r_0_payload_B;
    sc_signal< sc_logic > val_r_0_sel_rd;
    sc_signal< sc_logic > val_r_0_sel_wr;
    sc_signal< sc_logic > val_r_0_sel;
    sc_signal< sc_logic > val_r_0_load_A;
    sc_signal< sc_logic > val_r_0_load_B;
    sc_signal< sc_lv<2> > val_r_0_state;
    sc_signal< sc_logic > val_r_0_state_cmp_full;
    sc_signal< sc_lv<32> > in_vec_V_data_V_0_data_out;
    sc_signal< sc_logic > in_vec_V_data_V_0_vld_in;
    sc_signal< sc_logic > in_vec_V_data_V_0_vld_out;
    sc_signal< sc_logic > in_vec_V_data_V_0_ack_in;
    sc_signal< sc_logic > in_vec_V_data_V_0_ack_out;
    sc_signal< sc_lv<32> > in_vec_V_data_V_0_payload_A;
    sc_signal< sc_lv<32> > in_vec_V_data_V_0_payload_B;
    sc_signal< sc_logic > in_vec_V_data_V_0_sel_rd;
    sc_signal< sc_logic > in_vec_V_data_V_0_sel_wr;
    sc_signal< sc_logic > in_vec_V_data_V_0_sel;
    sc_signal< sc_logic > in_vec_V_data_V_0_load_A;
    sc_signal< sc_logic > in_vec_V_data_V_0_load_B;
    sc_signal< sc_lv<2> > in_vec_V_data_V_0_state;
    sc_signal< sc_logic > in_vec_V_data_V_0_state_cmp_full;
    sc_signal< sc_logic > in_vec_V_last_V_0_vld_in;
    sc_signal< sc_logic > in_vec_V_last_V_0_ack_out;
    sc_signal< sc_lv<2> > in_vec_V_last_V_0_state;
    sc_signal< sc_lv<32> > out_vec_V_data_V_1_data_out;
    sc_signal< sc_logic > out_vec_V_data_V_1_vld_in;
    sc_signal< sc_logic > out_vec_V_data_V_1_vld_out;
    sc_signal< sc_logic > out_vec_V_data_V_1_ack_in;
    sc_signal< sc_logic > out_vec_V_data_V_1_ack_out;
    sc_signal< sc_lv<32> > out_vec_V_data_V_1_payload_A;
    sc_signal< sc_lv<32> > out_vec_V_data_V_1_payload_B;
    sc_signal< sc_logic > out_vec_V_data_V_1_sel_rd;
    sc_signal< sc_logic > out_vec_V_data_V_1_sel_wr;
    sc_signal< sc_logic > out_vec_V_data_V_1_sel;
    sc_signal< sc_logic > out_vec_V_data_V_1_load_A;
    sc_signal< sc_logic > out_vec_V_data_V_1_load_B;
    sc_signal< sc_lv<2> > out_vec_V_data_V_1_state;
    sc_signal< sc_logic > out_vec_V_data_V_1_state_cmp_full;
    sc_signal< sc_lv<1> > out_vec_V_last_V_1_data_out;
    sc_signal< sc_logic > out_vec_V_last_V_1_vld_in;
    sc_signal< sc_logic > out_vec_V_last_V_1_vld_out;
    sc_signal< sc_logic > out_vec_V_last_V_1_ack_in;
    sc_signal< sc_logic > out_vec_V_last_V_1_ack_out;
    sc_signal< sc_lv<1> > out_vec_V_last_V_1_payload_A;
    sc_signal< sc_lv<1> > out_vec_V_last_V_1_payload_B;
    sc_signal< sc_logic > out_vec_V_last_V_1_sel_rd;
    sc_signal< sc_logic > out_vec_V_last_V_1_sel_wr;
    sc_signal< sc_logic > out_vec_V_last_V_1_sel;
    sc_signal< sc_logic > out_vec_V_last_V_1_load_A;
    sc_signal< sc_logic > out_vec_V_last_V_1_load_B;
    sc_signal< sc_lv<2> > out_vec_V_last_V_1_state;
    sc_signal< sc_logic > out_vec_V_last_V_1_state_cmp_full;
    sc_signal< sc_logic > val_r_TDATA_blk_n;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > in_vec_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln9_fu_87_p2;
    sc_signal< sc_logic > out_vec_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > sext_ln7_fu_83_p1;
    sc_signal< sc_lv<32> > sext_ln7_reg_120;
    sc_signal< sc_lv<6> > i_fu_93_p2;
    sc_signal< sc_lv<6> > i_reg_128;
    sc_signal< bool > ap_block_state2;
    sc_signal< bool > ap_block_state2_io;
    sc_signal< sc_lv<32> > tmp_data_V_1_fu_108_p1;
    sc_signal< sc_lv<1> > tmp_last_V_fu_113_p2;
    sc_signal< sc_lv<6> > i_0_reg_72;
    sc_signal< sc_lv<1> > icmp_ln879_fu_103_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<6> ap_const_lv6_1F;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_state2();
    void thread_ap_block_state2_io();
    void thread_ap_rst_n_inv();
    void thread_i_fu_93_p2();
    void thread_icmp_ln879_fu_103_p2();
    void thread_icmp_ln9_fu_87_p2();
    void thread_in_vec_TDATA_blk_n();
    void thread_in_vec_TREADY();
    void thread_in_vec_V_data_V_0_ack_in();
    void thread_in_vec_V_data_V_0_ack_out();
    void thread_in_vec_V_data_V_0_data_out();
    void thread_in_vec_V_data_V_0_load_A();
    void thread_in_vec_V_data_V_0_load_B();
    void thread_in_vec_V_data_V_0_sel();
    void thread_in_vec_V_data_V_0_state_cmp_full();
    void thread_in_vec_V_data_V_0_vld_in();
    void thread_in_vec_V_data_V_0_vld_out();
    void thread_in_vec_V_last_V_0_ack_out();
    void thread_in_vec_V_last_V_0_vld_in();
    void thread_out_vec_TDATA();
    void thread_out_vec_TDATA_blk_n();
    void thread_out_vec_TLAST();
    void thread_out_vec_TVALID();
    void thread_out_vec_V_data_V_1_ack_in();
    void thread_out_vec_V_data_V_1_ack_out();
    void thread_out_vec_V_data_V_1_data_out();
    void thread_out_vec_V_data_V_1_load_A();
    void thread_out_vec_V_data_V_1_load_B();
    void thread_out_vec_V_data_V_1_sel();
    void thread_out_vec_V_data_V_1_state_cmp_full();
    void thread_out_vec_V_data_V_1_vld_in();
    void thread_out_vec_V_data_V_1_vld_out();
    void thread_out_vec_V_last_V_1_ack_in();
    void thread_out_vec_V_last_V_1_ack_out();
    void thread_out_vec_V_last_V_1_data_out();
    void thread_out_vec_V_last_V_1_load_A();
    void thread_out_vec_V_last_V_1_load_B();
    void thread_out_vec_V_last_V_1_sel();
    void thread_out_vec_V_last_V_1_state_cmp_full();
    void thread_out_vec_V_last_V_1_vld_in();
    void thread_out_vec_V_last_V_1_vld_out();
    void thread_sext_ln7_fu_83_p1();
    void thread_tmp_data_V_1_fu_108_p1();
    void thread_tmp_last_V_fu_113_p2();
    void thread_val_r_0_ack_in();
    void thread_val_r_0_ack_out();
    void thread_val_r_0_data_out();
    void thread_val_r_0_load_A();
    void thread_val_r_0_load_B();
    void thread_val_r_0_sel();
    void thread_val_r_0_state_cmp_full();
    void thread_val_r_0_vld_in();
    void thread_val_r_0_vld_out();
    void thread_val_r_TDATA_blk_n();
    void thread_val_r_TREADY();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
