// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "demo_find.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic demo_find::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic demo_find::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> demo_find::ap_ST_fsm_state1 = "1";
const sc_lv<3> demo_find::ap_ST_fsm_state2 = "10";
const sc_lv<3> demo_find::ap_ST_fsm_state3 = "100";
const bool demo_find::ap_const_boolean_1 = true;
const sc_lv<1> demo_find::ap_const_lv1_0 = "0";
const sc_lv<1> demo_find::ap_const_lv1_1 = "1";
const sc_lv<2> demo_find::ap_const_lv2_0 = "00";
const sc_lv<2> demo_find::ap_const_lv2_2 = "10";
const sc_lv<2> demo_find::ap_const_lv2_3 = "11";
const sc_lv<2> demo_find::ap_const_lv2_1 = "1";
const sc_lv<32> demo_find::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> demo_find::ap_const_lv32_1 = "1";
const sc_lv<32> demo_find::ap_const_lv32_2 = "10";
const sc_lv<6> demo_find::ap_const_lv6_0 = "000000";
const sc_lv<6> demo_find::ap_const_lv6_20 = "100000";
const sc_lv<6> demo_find::ap_const_lv6_1 = "1";
const sc_lv<6> demo_find::ap_const_lv6_1F = "11111";

demo_find::demo_find(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( icmp_ln9_fu_87_p2 );

    SC_METHOD(thread_ap_block_state2_io);
    sensitive << ( out_vec_V_data_V_1_ack_in );
    sensitive << ( icmp_ln9_fu_87_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_i_fu_93_p2);
    sensitive << ( i_0_reg_72 );

    SC_METHOD(thread_icmp_ln879_fu_103_p2);
    sensitive << ( in_vec_V_data_V_0_data_out );
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( sext_ln7_reg_120 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_icmp_ln9_fu_87_p2);
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( i_0_reg_72 );

    SC_METHOD(thread_in_vec_TDATA_blk_n);
    sensitive << ( in_vec_V_data_V_0_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );

    SC_METHOD(thread_in_vec_TREADY);
    sensitive << ( in_vec_V_last_V_0_state );

    SC_METHOD(thread_in_vec_V_data_V_0_ack_in);
    sensitive << ( in_vec_V_data_V_0_state );

    SC_METHOD(thread_in_vec_V_data_V_0_ack_out);
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_in_vec_V_data_V_0_data_out);
    sensitive << ( in_vec_V_data_V_0_payload_A );
    sensitive << ( in_vec_V_data_V_0_payload_B );
    sensitive << ( in_vec_V_data_V_0_sel );

    SC_METHOD(thread_in_vec_V_data_V_0_load_A);
    sensitive << ( in_vec_V_data_V_0_sel_wr );
    sensitive << ( in_vec_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_vec_V_data_V_0_load_B);
    sensitive << ( in_vec_V_data_V_0_sel_wr );
    sensitive << ( in_vec_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_vec_V_data_V_0_sel);
    sensitive << ( in_vec_V_data_V_0_sel_rd );

    SC_METHOD(thread_in_vec_V_data_V_0_state_cmp_full);
    sensitive << ( in_vec_V_data_V_0_state );

    SC_METHOD(thread_in_vec_V_data_V_0_vld_in);
    sensitive << ( in_vec_TVALID );

    SC_METHOD(thread_in_vec_V_data_V_0_vld_out);
    sensitive << ( in_vec_V_data_V_0_state );

    SC_METHOD(thread_in_vec_V_last_V_0_ack_out);
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_in_vec_V_last_V_0_vld_in);
    sensitive << ( in_vec_TVALID );

    SC_METHOD(thread_out_vec_TDATA);
    sensitive << ( out_vec_V_data_V_1_data_out );

    SC_METHOD(thread_out_vec_TDATA_blk_n);
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_vec_TLAST);
    sensitive << ( out_vec_V_last_V_1_data_out );

    SC_METHOD(thread_out_vec_TVALID);
    sensitive << ( out_vec_V_last_V_1_state );

    SC_METHOD(thread_out_vec_V_data_V_1_ack_in);
    sensitive << ( out_vec_V_data_V_1_state );

    SC_METHOD(thread_out_vec_V_data_V_1_ack_out);
    sensitive << ( out_vec_TREADY );

    SC_METHOD(thread_out_vec_V_data_V_1_data_out);
    sensitive << ( out_vec_V_data_V_1_payload_A );
    sensitive << ( out_vec_V_data_V_1_payload_B );
    sensitive << ( out_vec_V_data_V_1_sel );

    SC_METHOD(thread_out_vec_V_data_V_1_load_A);
    sensitive << ( out_vec_V_data_V_1_sel_wr );
    sensitive << ( out_vec_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_out_vec_V_data_V_1_load_B);
    sensitive << ( out_vec_V_data_V_1_sel_wr );
    sensitive << ( out_vec_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_out_vec_V_data_V_1_sel);
    sensitive << ( out_vec_V_data_V_1_sel_rd );

    SC_METHOD(thread_out_vec_V_data_V_1_state_cmp_full);
    sensitive << ( out_vec_V_data_V_1_state );

    SC_METHOD(thread_out_vec_V_data_V_1_vld_in);
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_out_vec_V_data_V_1_vld_out);
    sensitive << ( out_vec_V_data_V_1_state );

    SC_METHOD(thread_out_vec_V_last_V_1_ack_in);
    sensitive << ( out_vec_V_last_V_1_state );

    SC_METHOD(thread_out_vec_V_last_V_1_ack_out);
    sensitive << ( out_vec_TREADY );

    SC_METHOD(thread_out_vec_V_last_V_1_data_out);
    sensitive << ( out_vec_V_last_V_1_payload_A );
    sensitive << ( out_vec_V_last_V_1_payload_B );
    sensitive << ( out_vec_V_last_V_1_sel );

    SC_METHOD(thread_out_vec_V_last_V_1_load_A);
    sensitive << ( out_vec_V_last_V_1_sel_wr );
    sensitive << ( out_vec_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_out_vec_V_last_V_1_load_B);
    sensitive << ( out_vec_V_last_V_1_sel_wr );
    sensitive << ( out_vec_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_out_vec_V_last_V_1_sel);
    sensitive << ( out_vec_V_last_V_1_sel_rd );

    SC_METHOD(thread_out_vec_V_last_V_1_state_cmp_full);
    sensitive << ( out_vec_V_last_V_1_state );

    SC_METHOD(thread_out_vec_V_last_V_1_vld_in);
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_out_vec_V_last_V_1_vld_out);
    sensitive << ( out_vec_V_last_V_1_state );

    SC_METHOD(thread_sext_ln7_fu_83_p1);
    sensitive << ( val_r_0_data_out );

    SC_METHOD(thread_tmp_data_V_1_fu_108_p1);
    sensitive << ( icmp_ln879_fu_103_p2 );

    SC_METHOD(thread_tmp_last_V_fu_113_p2);
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( i_0_reg_72 );

    SC_METHOD(thread_val_r_0_ack_in);
    sensitive << ( val_r_0_state );

    SC_METHOD(thread_val_r_0_ack_out);
    sensitive << ( val_r_0_vld_out );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_val_r_0_data_out);
    sensitive << ( val_r_0_payload_A );
    sensitive << ( val_r_0_payload_B );
    sensitive << ( val_r_0_sel );

    SC_METHOD(thread_val_r_0_load_A);
    sensitive << ( val_r_0_sel_wr );
    sensitive << ( val_r_0_state_cmp_full );

    SC_METHOD(thread_val_r_0_load_B);
    sensitive << ( val_r_0_sel_wr );
    sensitive << ( val_r_0_state_cmp_full );

    SC_METHOD(thread_val_r_0_sel);
    sensitive << ( val_r_0_sel_rd );

    SC_METHOD(thread_val_r_0_state_cmp_full);
    sensitive << ( val_r_0_state );

    SC_METHOD(thread_val_r_0_vld_in);
    sensitive << ( val_r_TVALID );

    SC_METHOD(thread_val_r_0_vld_out);
    sensitive << ( val_r_0_state );

    SC_METHOD(thread_val_r_TDATA_blk_n);
    sensitive << ( val_r_0_state );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_val_r_TREADY);
    sensitive << ( val_r_0_state );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( val_r_0_vld_out );
    sensitive << ( in_vec_V_data_V_0_vld_out );
    sensitive << ( out_vec_TREADY );
    sensitive << ( out_vec_V_data_V_1_ack_in );
    sensitive << ( out_vec_V_data_V_1_state );
    sensitive << ( out_vec_V_last_V_1_state );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_87_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_state2_io );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    val_r_0_sel_rd = SC_LOGIC_0;
    val_r_0_sel_wr = SC_LOGIC_0;
    val_r_0_state = "00";
    in_vec_V_data_V_0_sel_rd = SC_LOGIC_0;
    in_vec_V_data_V_0_sel_wr = SC_LOGIC_0;
    in_vec_V_data_V_0_state = "00";
    in_vec_V_last_V_0_state = "00";
    out_vec_V_data_V_1_sel_rd = SC_LOGIC_0;
    out_vec_V_data_V_1_sel_wr = SC_LOGIC_0;
    out_vec_V_data_V_1_state = "00";
    out_vec_V_last_V_1_sel_rd = SC_LOGIC_0;
    out_vec_V_last_V_1_sel_wr = SC_LOGIC_0;
    out_vec_V_last_V_1_state = "00";
    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "demo_find_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, val_r_TDATA, "(port)val_r_TDATA");
    sc_trace(mVcdFile, val_r_TVALID, "(port)val_r_TVALID");
    sc_trace(mVcdFile, val_r_TREADY, "(port)val_r_TREADY");
    sc_trace(mVcdFile, in_vec_TDATA, "(port)in_vec_TDATA");
    sc_trace(mVcdFile, in_vec_TVALID, "(port)in_vec_TVALID");
    sc_trace(mVcdFile, in_vec_TREADY, "(port)in_vec_TREADY");
    sc_trace(mVcdFile, in_vec_TLAST, "(port)in_vec_TLAST");
    sc_trace(mVcdFile, out_vec_TDATA, "(port)out_vec_TDATA");
    sc_trace(mVcdFile, out_vec_TVALID, "(port)out_vec_TVALID");
    sc_trace(mVcdFile, out_vec_TREADY, "(port)out_vec_TREADY");
    sc_trace(mVcdFile, out_vec_TLAST, "(port)out_vec_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, val_r_0_data_out, "val_r_0_data_out");
    sc_trace(mVcdFile, val_r_0_vld_in, "val_r_0_vld_in");
    sc_trace(mVcdFile, val_r_0_vld_out, "val_r_0_vld_out");
    sc_trace(mVcdFile, val_r_0_ack_in, "val_r_0_ack_in");
    sc_trace(mVcdFile, val_r_0_ack_out, "val_r_0_ack_out");
    sc_trace(mVcdFile, val_r_0_payload_A, "val_r_0_payload_A");
    sc_trace(mVcdFile, val_r_0_payload_B, "val_r_0_payload_B");
    sc_trace(mVcdFile, val_r_0_sel_rd, "val_r_0_sel_rd");
    sc_trace(mVcdFile, val_r_0_sel_wr, "val_r_0_sel_wr");
    sc_trace(mVcdFile, val_r_0_sel, "val_r_0_sel");
    sc_trace(mVcdFile, val_r_0_load_A, "val_r_0_load_A");
    sc_trace(mVcdFile, val_r_0_load_B, "val_r_0_load_B");
    sc_trace(mVcdFile, val_r_0_state, "val_r_0_state");
    sc_trace(mVcdFile, val_r_0_state_cmp_full, "val_r_0_state_cmp_full");
    sc_trace(mVcdFile, in_vec_V_data_V_0_data_out, "in_vec_V_data_V_0_data_out");
    sc_trace(mVcdFile, in_vec_V_data_V_0_vld_in, "in_vec_V_data_V_0_vld_in");
    sc_trace(mVcdFile, in_vec_V_data_V_0_vld_out, "in_vec_V_data_V_0_vld_out");
    sc_trace(mVcdFile, in_vec_V_data_V_0_ack_in, "in_vec_V_data_V_0_ack_in");
    sc_trace(mVcdFile, in_vec_V_data_V_0_ack_out, "in_vec_V_data_V_0_ack_out");
    sc_trace(mVcdFile, in_vec_V_data_V_0_payload_A, "in_vec_V_data_V_0_payload_A");
    sc_trace(mVcdFile, in_vec_V_data_V_0_payload_B, "in_vec_V_data_V_0_payload_B");
    sc_trace(mVcdFile, in_vec_V_data_V_0_sel_rd, "in_vec_V_data_V_0_sel_rd");
    sc_trace(mVcdFile, in_vec_V_data_V_0_sel_wr, "in_vec_V_data_V_0_sel_wr");
    sc_trace(mVcdFile, in_vec_V_data_V_0_sel, "in_vec_V_data_V_0_sel");
    sc_trace(mVcdFile, in_vec_V_data_V_0_load_A, "in_vec_V_data_V_0_load_A");
    sc_trace(mVcdFile, in_vec_V_data_V_0_load_B, "in_vec_V_data_V_0_load_B");
    sc_trace(mVcdFile, in_vec_V_data_V_0_state, "in_vec_V_data_V_0_state");
    sc_trace(mVcdFile, in_vec_V_data_V_0_state_cmp_full, "in_vec_V_data_V_0_state_cmp_full");
    sc_trace(mVcdFile, in_vec_V_last_V_0_vld_in, "in_vec_V_last_V_0_vld_in");
    sc_trace(mVcdFile, in_vec_V_last_V_0_ack_out, "in_vec_V_last_V_0_ack_out");
    sc_trace(mVcdFile, in_vec_V_last_V_0_state, "in_vec_V_last_V_0_state");
    sc_trace(mVcdFile, out_vec_V_data_V_1_data_out, "out_vec_V_data_V_1_data_out");
    sc_trace(mVcdFile, out_vec_V_data_V_1_vld_in, "out_vec_V_data_V_1_vld_in");
    sc_trace(mVcdFile, out_vec_V_data_V_1_vld_out, "out_vec_V_data_V_1_vld_out");
    sc_trace(mVcdFile, out_vec_V_data_V_1_ack_in, "out_vec_V_data_V_1_ack_in");
    sc_trace(mVcdFile, out_vec_V_data_V_1_ack_out, "out_vec_V_data_V_1_ack_out");
    sc_trace(mVcdFile, out_vec_V_data_V_1_payload_A, "out_vec_V_data_V_1_payload_A");
    sc_trace(mVcdFile, out_vec_V_data_V_1_payload_B, "out_vec_V_data_V_1_payload_B");
    sc_trace(mVcdFile, out_vec_V_data_V_1_sel_rd, "out_vec_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, out_vec_V_data_V_1_sel_wr, "out_vec_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, out_vec_V_data_V_1_sel, "out_vec_V_data_V_1_sel");
    sc_trace(mVcdFile, out_vec_V_data_V_1_load_A, "out_vec_V_data_V_1_load_A");
    sc_trace(mVcdFile, out_vec_V_data_V_1_load_B, "out_vec_V_data_V_1_load_B");
    sc_trace(mVcdFile, out_vec_V_data_V_1_state, "out_vec_V_data_V_1_state");
    sc_trace(mVcdFile, out_vec_V_data_V_1_state_cmp_full, "out_vec_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, out_vec_V_last_V_1_data_out, "out_vec_V_last_V_1_data_out");
    sc_trace(mVcdFile, out_vec_V_last_V_1_vld_in, "out_vec_V_last_V_1_vld_in");
    sc_trace(mVcdFile, out_vec_V_last_V_1_vld_out, "out_vec_V_last_V_1_vld_out");
    sc_trace(mVcdFile, out_vec_V_last_V_1_ack_in, "out_vec_V_last_V_1_ack_in");
    sc_trace(mVcdFile, out_vec_V_last_V_1_ack_out, "out_vec_V_last_V_1_ack_out");
    sc_trace(mVcdFile, out_vec_V_last_V_1_payload_A, "out_vec_V_last_V_1_payload_A");
    sc_trace(mVcdFile, out_vec_V_last_V_1_payload_B, "out_vec_V_last_V_1_payload_B");
    sc_trace(mVcdFile, out_vec_V_last_V_1_sel_rd, "out_vec_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, out_vec_V_last_V_1_sel_wr, "out_vec_V_last_V_1_sel_wr");
    sc_trace(mVcdFile, out_vec_V_last_V_1_sel, "out_vec_V_last_V_1_sel");
    sc_trace(mVcdFile, out_vec_V_last_V_1_load_A, "out_vec_V_last_V_1_load_A");
    sc_trace(mVcdFile, out_vec_V_last_V_1_load_B, "out_vec_V_last_V_1_load_B");
    sc_trace(mVcdFile, out_vec_V_last_V_1_state, "out_vec_V_last_V_1_state");
    sc_trace(mVcdFile, out_vec_V_last_V_1_state_cmp_full, "out_vec_V_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, val_r_TDATA_blk_n, "val_r_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, in_vec_TDATA_blk_n, "in_vec_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln9_fu_87_p2, "icmp_ln9_fu_87_p2");
    sc_trace(mVcdFile, out_vec_TDATA_blk_n, "out_vec_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, sext_ln7_fu_83_p1, "sext_ln7_fu_83_p1");
    sc_trace(mVcdFile, sext_ln7_reg_120, "sext_ln7_reg_120");
    sc_trace(mVcdFile, i_fu_93_p2, "i_fu_93_p2");
    sc_trace(mVcdFile, i_reg_128, "i_reg_128");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, ap_block_state2_io, "ap_block_state2_io");
    sc_trace(mVcdFile, tmp_data_V_1_fu_108_p1, "tmp_data_V_1_fu_108_p1");
    sc_trace(mVcdFile, tmp_last_V_fu_113_p2, "tmp_last_V_fu_113_p2");
    sc_trace(mVcdFile, i_0_reg_72, "i_0_reg_72");
    sc_trace(mVcdFile, icmp_ln879_fu_103_p2, "icmp_ln879_fu_103_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("demo_find.hdltvin.dat");
    mHdltvoutHandle.open("demo_find.hdltvout.dat");
}

demo_find::~demo_find() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void demo_find::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(out_vec_V_data_V_1_ack_in.read(), ap_const_logic_1))) {
        i_0_reg_72 = i_reg_128.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(val_r_0_vld_out.read(), ap_const_logic_1))) {
        i_0_reg_72 = ap_const_lv6_0;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_vec_V_data_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_vld_out.read()))) {
            in_vec_V_data_V_0_sel_rd =  (sc_logic) (~in_vec_V_data_V_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_vec_V_data_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_ack_in.read()))) {
            in_vec_V_data_V_0_sel_wr =  (sc_logic) (~in_vec_V_data_V_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_vec_V_data_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, in_vec_V_data_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, in_vec_V_data_V_0_state.read())))) {
            in_vec_V_data_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, in_vec_V_data_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_vec_V_data_V_0_state.read())))) {
            in_vec_V_data_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, in_vec_V_data_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_vec_V_data_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, in_vec_V_data_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_ack_out.read()))))) {
            in_vec_V_data_V_0_state = ap_const_lv2_3;
        } else {
            in_vec_V_data_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_vec_V_last_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_last_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, in_vec_V_last_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, in_vec_V_last_V_0_state.read())))) {
            in_vec_V_last_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, in_vec_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_vec_V_last_V_0_state.read())))) {
            in_vec_V_last_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, in_vec_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_vec_V_last_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, in_vec_V_last_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_last_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_last_V_0_ack_out.read()))))) {
            in_vec_V_last_V_0_state = ap_const_lv2_3;
        } else {
            in_vec_V_last_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_vec_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_vld_out.read()))) {
            out_vec_V_data_V_1_sel_rd =  (sc_logic) (~out_vec_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_vec_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_ack_in.read()))) {
            out_vec_V_data_V_1_sel_wr =  (sc_logic) (~out_vec_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_vec_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_vec_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, out_vec_V_data_V_1_state.read())))) {
            out_vec_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read())))) {
            out_vec_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, out_vec_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_vec_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_ack_out.read()))))) {
            out_vec_V_data_V_1_state = ap_const_lv2_3;
        } else {
            out_vec_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_vec_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_vld_out.read()))) {
            out_vec_V_last_V_1_sel_rd =  (sc_logic) (~out_vec_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_vec_V_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_ack_in.read()))) {
            out_vec_V_last_V_1_sel_wr =  (sc_logic) (~out_vec_V_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_vec_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_vec_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, out_vec_V_last_V_1_state.read())))) {
            out_vec_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read())))) {
            out_vec_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, out_vec_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_vec_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_ack_out.read()))))) {
            out_vec_V_last_V_1_state = ap_const_lv2_3;
        } else {
            out_vec_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        val_r_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_vld_out.read()))) {
            val_r_0_sel_rd =  (sc_logic) (~val_r_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        val_r_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_ack_in.read()))) {
            val_r_0_sel_wr =  (sc_logic) (~val_r_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        val_r_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, val_r_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_ack_out.read()) && 
              esl_seteq<1,2,2>(val_r_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, val_r_0_vld_in.read()) && 
              esl_seteq<1,2,2>(val_r_0_state.read(), ap_const_lv2_2)))) {
            val_r_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, val_r_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(val_r_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, val_r_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(val_r_0_state.read(), ap_const_lv2_1)))) {
            val_r_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(val_r_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(val_r_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(val_r_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, val_r_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, val_r_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_ack_out.read()))))) {
            val_r_0_state = ap_const_lv2_3;
        } else {
            val_r_0_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        i_reg_128 = i_fu_93_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_load_A.read())) {
        in_vec_V_data_V_0_payload_A = in_vec_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_load_B.read())) {
        in_vec_V_data_V_0_payload_B = in_vec_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_load_A.read())) {
        out_vec_V_data_V_1_payload_A = tmp_data_V_1_fu_108_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_load_B.read())) {
        out_vec_V_data_V_1_payload_B = tmp_data_V_1_fu_108_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_load_A.read())) {
        out_vec_V_last_V_1_payload_A = tmp_last_V_fu_113_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_load_B.read())) {
        out_vec_V_last_V_1_payload_B = tmp_last_V_fu_113_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(val_r_0_vld_out.read(), ap_const_logic_1))) {
        sext_ln7_reg_120 = sext_ln7_fu_83_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_load_A.read())) {
        val_r_0_payload_A = val_r_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_load_B.read())) {
        val_r_0_payload_B = val_r_TDATA.read();
    }
}

void demo_find::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void demo_find::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void demo_find::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void demo_find::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())));
}

void demo_find::thread_ap_block_state2_io() {
    ap_block_state2_io = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_vec_V_data_V_1_ack_in.read()));
}

void demo_find::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void demo_find::thread_i_fu_93_p2() {
    i_fu_93_p2 = (!i_0_reg_72.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_0_reg_72.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void demo_find::thread_icmp_ln879_fu_103_p2() {
    icmp_ln879_fu_103_p2 = (!in_vec_V_data_V_0_data_out.read().is_01() || !sext_ln7_reg_120.read().is_01())? sc_lv<1>(): sc_lv<1>(in_vec_V_data_V_0_data_out.read() == sext_ln7_reg_120.read());
}

void demo_find::thread_icmp_ln9_fu_87_p2() {
    icmp_ln9_fu_87_p2 = (!i_0_reg_72.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_72.read() == ap_const_lv6_20);
}

void demo_find::thread_in_vec_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()))) {
        in_vec_TDATA_blk_n = in_vec_V_data_V_0_state.read()[0];
    } else {
        in_vec_TDATA_blk_n = ap_const_logic_1;
    }
}

void demo_find::thread_in_vec_TREADY() {
    in_vec_TREADY = in_vec_V_last_V_0_state.read()[1];
}

void demo_find::thread_in_vec_V_data_V_0_ack_in() {
    in_vec_V_data_V_0_ack_in = in_vec_V_data_V_0_state.read()[1];
}

void demo_find::thread_in_vec_V_data_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
         !(esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        in_vec_V_data_V_0_ack_out = ap_const_logic_1;
    } else {
        in_vec_V_data_V_0_ack_out = ap_const_logic_0;
    }
}

void demo_find::thread_in_vec_V_data_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_vec_V_data_V_0_sel.read())) {
        in_vec_V_data_V_0_data_out = in_vec_V_data_V_0_payload_B.read();
    } else {
        in_vec_V_data_V_0_data_out = in_vec_V_data_V_0_payload_A.read();
    }
}

void demo_find::thread_in_vec_V_data_V_0_load_A() {
    in_vec_V_data_V_0_load_A = (in_vec_V_data_V_0_state_cmp_full.read() & ~in_vec_V_data_V_0_sel_wr.read());
}

void demo_find::thread_in_vec_V_data_V_0_load_B() {
    in_vec_V_data_V_0_load_B = (in_vec_V_data_V_0_sel_wr.read() & in_vec_V_data_V_0_state_cmp_full.read());
}

void demo_find::thread_in_vec_V_data_V_0_sel() {
    in_vec_V_data_V_0_sel = in_vec_V_data_V_0_sel_rd.read();
}

void demo_find::thread_in_vec_V_data_V_0_state_cmp_full() {
    in_vec_V_data_V_0_state_cmp_full =  (sc_logic) ((!in_vec_V_data_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(in_vec_V_data_V_0_state.read() != ap_const_lv2_1))[0];
}

void demo_find::thread_in_vec_V_data_V_0_vld_in() {
    in_vec_V_data_V_0_vld_in = in_vec_TVALID.read();
}

void demo_find::thread_in_vec_V_data_V_0_vld_out() {
    in_vec_V_data_V_0_vld_out = in_vec_V_data_V_0_state.read()[0];
}

void demo_find::thread_in_vec_V_last_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
         !(esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        in_vec_V_last_V_0_ack_out = ap_const_logic_1;
    } else {
        in_vec_V_last_V_0_ack_out = ap_const_logic_0;
    }
}

void demo_find::thread_in_vec_V_last_V_0_vld_in() {
    in_vec_V_last_V_0_vld_in = in_vec_TVALID.read();
}

void demo_find::thread_out_vec_TDATA() {
    out_vec_TDATA = out_vec_V_data_V_1_data_out.read();
}

void demo_find::thread_out_vec_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        out_vec_TDATA_blk_n = out_vec_V_data_V_1_state.read()[1];
    } else {
        out_vec_TDATA_blk_n = ap_const_logic_1;
    }
}

void demo_find::thread_out_vec_TLAST() {
    out_vec_TLAST = out_vec_V_last_V_1_data_out.read();
}

void demo_find::thread_out_vec_TVALID() {
    out_vec_TVALID = out_vec_V_last_V_1_state.read()[0];
}

void demo_find::thread_out_vec_V_data_V_1_ack_in() {
    out_vec_V_data_V_1_ack_in = out_vec_V_data_V_1_state.read()[1];
}

void demo_find::thread_out_vec_V_data_V_1_ack_out() {
    out_vec_V_data_V_1_ack_out = out_vec_TREADY.read();
}

void demo_find::thread_out_vec_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_data_V_1_sel.read())) {
        out_vec_V_data_V_1_data_out = out_vec_V_data_V_1_payload_B.read();
    } else {
        out_vec_V_data_V_1_data_out = out_vec_V_data_V_1_payload_A.read();
    }
}

void demo_find::thread_out_vec_V_data_V_1_load_A() {
    out_vec_V_data_V_1_load_A = (out_vec_V_data_V_1_state_cmp_full.read() & ~out_vec_V_data_V_1_sel_wr.read());
}

void demo_find::thread_out_vec_V_data_V_1_load_B() {
    out_vec_V_data_V_1_load_B = (out_vec_V_data_V_1_sel_wr.read() & out_vec_V_data_V_1_state_cmp_full.read());
}

void demo_find::thread_out_vec_V_data_V_1_sel() {
    out_vec_V_data_V_1_sel = out_vec_V_data_V_1_sel_rd.read();
}

void demo_find::thread_out_vec_V_data_V_1_state_cmp_full() {
    out_vec_V_data_V_1_state_cmp_full =  (sc_logic) ((!out_vec_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_vec_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void demo_find::thread_out_vec_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
         !(esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        out_vec_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        out_vec_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void demo_find::thread_out_vec_V_data_V_1_vld_out() {
    out_vec_V_data_V_1_vld_out = out_vec_V_data_V_1_state.read()[0];
}

void demo_find::thread_out_vec_V_last_V_1_ack_in() {
    out_vec_V_last_V_1_ack_in = out_vec_V_last_V_1_state.read()[1];
}

void demo_find::thread_out_vec_V_last_V_1_ack_out() {
    out_vec_V_last_V_1_ack_out = out_vec_TREADY.read();
}

void demo_find::thread_out_vec_V_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_vec_V_last_V_1_sel.read())) {
        out_vec_V_last_V_1_data_out = out_vec_V_last_V_1_payload_B.read();
    } else {
        out_vec_V_last_V_1_data_out = out_vec_V_last_V_1_payload_A.read();
    }
}

void demo_find::thread_out_vec_V_last_V_1_load_A() {
    out_vec_V_last_V_1_load_A = (out_vec_V_last_V_1_state_cmp_full.read() & ~out_vec_V_last_V_1_sel_wr.read());
}

void demo_find::thread_out_vec_V_last_V_1_load_B() {
    out_vec_V_last_V_1_load_B = (out_vec_V_last_V_1_sel_wr.read() & out_vec_V_last_V_1_state_cmp_full.read());
}

void demo_find::thread_out_vec_V_last_V_1_sel() {
    out_vec_V_last_V_1_sel = out_vec_V_last_V_1_sel_rd.read();
}

void demo_find::thread_out_vec_V_last_V_1_state_cmp_full() {
    out_vec_V_last_V_1_state_cmp_full =  (sc_logic) ((!out_vec_V_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_vec_V_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void demo_find::thread_out_vec_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
         !(esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        out_vec_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        out_vec_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void demo_find::thread_out_vec_V_last_V_1_vld_out() {
    out_vec_V_last_V_1_vld_out = out_vec_V_last_V_1_state.read()[0];
}

void demo_find::thread_sext_ln7_fu_83_p1() {
    sext_ln7_fu_83_p1 = esl_sext<32,8>(val_r_0_data_out.read());
}

void demo_find::thread_tmp_data_V_1_fu_108_p1() {
    tmp_data_V_1_fu_108_p1 = esl_zext<32,1>(icmp_ln879_fu_103_p2.read());
}

void demo_find::thread_tmp_last_V_fu_113_p2() {
    tmp_last_V_fu_113_p2 = (!i_0_reg_72.read().is_01() || !ap_const_lv6_1F.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_72.read() == ap_const_lv6_1F);
}

void demo_find::thread_val_r_0_ack_in() {
    val_r_0_ack_in = val_r_0_state.read()[1];
}

void demo_find::thread_val_r_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(val_r_0_vld_out.read(), ap_const_logic_1))) {
        val_r_0_ack_out = ap_const_logic_1;
    } else {
        val_r_0_ack_out = ap_const_logic_0;
    }
}

void demo_find::thread_val_r_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, val_r_0_sel.read())) {
        val_r_0_data_out = val_r_0_payload_B.read();
    } else {
        val_r_0_data_out = val_r_0_payload_A.read();
    }
}

void demo_find::thread_val_r_0_load_A() {
    val_r_0_load_A = (val_r_0_state_cmp_full.read() & ~val_r_0_sel_wr.read());
}

void demo_find::thread_val_r_0_load_B() {
    val_r_0_load_B = (val_r_0_sel_wr.read() & val_r_0_state_cmp_full.read());
}

void demo_find::thread_val_r_0_sel() {
    val_r_0_sel = val_r_0_sel_rd.read();
}

void demo_find::thread_val_r_0_state_cmp_full() {
    val_r_0_state_cmp_full =  (sc_logic) ((!val_r_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(val_r_0_state.read() != ap_const_lv2_1))[0];
}

void demo_find::thread_val_r_0_vld_in() {
    val_r_0_vld_in = val_r_TVALID.read();
}

void demo_find::thread_val_r_0_vld_out() {
    val_r_0_vld_out = val_r_0_state.read()[0];
}

void demo_find::thread_val_r_TDATA_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        val_r_TDATA_blk_n = val_r_0_state.read()[0];
    } else {
        val_r_TDATA_blk_n = ap_const_logic_1;
    }
}

void demo_find::thread_val_r_TREADY() {
    val_r_TREADY = val_r_0_state.read()[1];
}

void demo_find::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(val_r_0_vld_out.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln9_fu_87_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && !(esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_data_V_1_state.read()) || esl_seteq<1,2,2>(ap_const_lv2_1, out_vec_V_last_V_1_state.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln9_fu_87_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_vec_V_data_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_data_V_1_state.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, out_vec_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_vec_V_last_V_1_state.read())) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(out_vec_V_data_V_1_ack_in.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void demo_find::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"val_r_TDATA\" :  \"" << val_r_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"val_r_TVALID\" :  \"" << val_r_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"val_r_TREADY\" :  \"" << val_r_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_vec_TDATA\" :  \"" << in_vec_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_vec_TVALID\" :  \"" << in_vec_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_vec_TREADY\" :  \"" << in_vec_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_vec_TLAST\" :  \"" << in_vec_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_vec_TDATA\" :  \"" << out_vec_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_vec_TVALID\" :  \"" << out_vec_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_vec_TREADY\" :  \"" << out_vec_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_vec_TLAST\" :  \"" << out_vec_TLAST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

