// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="demo_find,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.473000,HLS_SYN_LAT=65,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=211,HLS_SYN_LUT=275,HLS_VERSION=2019_1}" *)

module demo_find (
        ap_clk,
        ap_rst_n,
        val_r_TDATA,
        val_r_TVALID,
        val_r_TREADY,
        in_vec_TDATA,
        in_vec_TVALID,
        in_vec_TREADY,
        in_vec_TLAST,
        out_vec_TDATA,
        out_vec_TVALID,
        out_vec_TREADY,
        out_vec_TLAST
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst_n;
input  [7:0] val_r_TDATA;
input   val_r_TVALID;
output   val_r_TREADY;
input  [31:0] in_vec_TDATA;
input   in_vec_TVALID;
output   in_vec_TREADY;
input  [0:0] in_vec_TLAST;
output  [31:0] out_vec_TDATA;
output   out_vec_TVALID;
input   out_vec_TREADY;
output  [0:0] out_vec_TLAST;

 reg    ap_rst_n_inv;
reg   [7:0] val_r_0_data_out;
wire    val_r_0_vld_in;
wire    val_r_0_vld_out;
wire    val_r_0_ack_in;
reg    val_r_0_ack_out;
reg   [7:0] val_r_0_payload_A;
reg   [7:0] val_r_0_payload_B;
reg    val_r_0_sel_rd;
reg    val_r_0_sel_wr;
wire    val_r_0_sel;
wire    val_r_0_load_A;
wire    val_r_0_load_B;
reg   [1:0] val_r_0_state;
wire    val_r_0_state_cmp_full;
reg   [31:0] in_vec_V_data_V_0_data_out;
wire    in_vec_V_data_V_0_vld_in;
wire    in_vec_V_data_V_0_vld_out;
wire    in_vec_V_data_V_0_ack_in;
reg    in_vec_V_data_V_0_ack_out;
reg   [31:0] in_vec_V_data_V_0_payload_A;
reg   [31:0] in_vec_V_data_V_0_payload_B;
reg    in_vec_V_data_V_0_sel_rd;
reg    in_vec_V_data_V_0_sel_wr;
wire    in_vec_V_data_V_0_sel;
wire    in_vec_V_data_V_0_load_A;
wire    in_vec_V_data_V_0_load_B;
reg   [1:0] in_vec_V_data_V_0_state;
wire    in_vec_V_data_V_0_state_cmp_full;
wire    in_vec_V_last_V_0_vld_in;
reg    in_vec_V_last_V_0_ack_out;
reg   [1:0] in_vec_V_last_V_0_state;
reg   [31:0] out_vec_V_data_V_1_data_out;
reg    out_vec_V_data_V_1_vld_in;
wire    out_vec_V_data_V_1_vld_out;
wire    out_vec_V_data_V_1_ack_in;
wire    out_vec_V_data_V_1_ack_out;
reg   [31:0] out_vec_V_data_V_1_payload_A;
reg   [31:0] out_vec_V_data_V_1_payload_B;
reg    out_vec_V_data_V_1_sel_rd;
reg    out_vec_V_data_V_1_sel_wr;
wire    out_vec_V_data_V_1_sel;
wire    out_vec_V_data_V_1_load_A;
wire    out_vec_V_data_V_1_load_B;
reg   [1:0] out_vec_V_data_V_1_state;
wire    out_vec_V_data_V_1_state_cmp_full;
reg   [0:0] out_vec_V_last_V_1_data_out;
reg    out_vec_V_last_V_1_vld_in;
wire    out_vec_V_last_V_1_vld_out;
wire    out_vec_V_last_V_1_ack_in;
wire    out_vec_V_last_V_1_ack_out;
reg   [0:0] out_vec_V_last_V_1_payload_A;
reg   [0:0] out_vec_V_last_V_1_payload_B;
reg    out_vec_V_last_V_1_sel_rd;
reg    out_vec_V_last_V_1_sel_wr;
wire    out_vec_V_last_V_1_sel;
wire    out_vec_V_last_V_1_load_A;
wire    out_vec_V_last_V_1_load_B;
reg   [1:0] out_vec_V_last_V_1_state;
wire    out_vec_V_last_V_1_state_cmp_full;
reg    val_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_vec_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln9_fu_87_p2;
reg    out_vec_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire  signed [31:0] sext_ln7_fu_83_p1;
reg  signed [31:0] sext_ln7_reg_120;
wire   [5:0] i_fu_93_p2;
reg   [5:0] i_reg_128;
reg    ap_block_state2;
reg    ap_block_state2_io;
wire   [31:0] tmp_data_V_1_fu_108_p1;
wire   [0:0] tmp_last_V_fu_113_p2;
reg   [5:0] i_0_reg_72;
wire   [0:0] icmp_ln879_fu_103_p2;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 val_r_0_sel_rd = 1'b0;
#0 val_r_0_sel_wr = 1'b0;
#0 val_r_0_state = 2'd0;
#0 in_vec_V_data_V_0_sel_rd = 1'b0;
#0 in_vec_V_data_V_0_sel_wr = 1'b0;
#0 in_vec_V_data_V_0_state = 2'd0;
#0 in_vec_V_last_V_0_state = 2'd0;
#0 out_vec_V_data_V_1_sel_rd = 1'b0;
#0 out_vec_V_data_V_1_sel_wr = 1'b0;
#0 out_vec_V_data_V_1_state = 2'd0;
#0 out_vec_V_last_V_1_sel_rd = 1'b0;
#0 out_vec_V_last_V_1_sel_wr = 1'b0;
#0 out_vec_V_last_V_1_state = 2'd0;
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_vec_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((in_vec_V_data_V_0_ack_out == 1'b1) & (in_vec_V_data_V_0_vld_out == 1'b1))) begin
            in_vec_V_data_V_0_sel_rd <= ~in_vec_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_vec_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((in_vec_V_data_V_0_ack_in == 1'b1) & (in_vec_V_data_V_0_vld_in == 1'b1))) begin
            in_vec_V_data_V_0_sel_wr <= ~in_vec_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_vec_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((in_vec_V_data_V_0_state == 2'd2) & (in_vec_V_data_V_0_vld_in == 1'b0)) | ((in_vec_V_data_V_0_state == 2'd3) & (in_vec_V_data_V_0_vld_in == 1'b0) & (in_vec_V_data_V_0_ack_out == 1'b1)))) begin
            in_vec_V_data_V_0_state <= 2'd2;
        end else if ((((in_vec_V_data_V_0_state == 2'd3) & (in_vec_V_data_V_0_ack_out == 1'b0) & (in_vec_V_data_V_0_vld_in == 1'b1)) | ((in_vec_V_data_V_0_state == 2'd1) & (in_vec_V_data_V_0_ack_out == 1'b0)))) begin
            in_vec_V_data_V_0_state <= 2'd1;
        end else if ((((in_vec_V_data_V_0_state == 2'd2) & (in_vec_V_data_V_0_vld_in == 1'b1)) | (~((in_vec_V_data_V_0_vld_in == 1'b0) & (in_vec_V_data_V_0_ack_out == 1'b1)) & ~((in_vec_V_data_V_0_ack_out == 1'b0) & (in_vec_V_data_V_0_vld_in == 1'b1)) & (in_vec_V_data_V_0_state == 2'd3)) | ((in_vec_V_data_V_0_state == 2'd1) & (in_vec_V_data_V_0_ack_out == 1'b1)))) begin
            in_vec_V_data_V_0_state <= 2'd3;
        end else begin
            in_vec_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_vec_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((in_vec_V_last_V_0_state == 2'd2) & (in_vec_V_last_V_0_vld_in == 1'b0)) | ((in_vec_V_last_V_0_state == 2'd3) & (in_vec_V_last_V_0_vld_in == 1'b0) & (in_vec_V_last_V_0_ack_out == 1'b1)))) begin
            in_vec_V_last_V_0_state <= 2'd2;
        end else if ((((in_vec_V_last_V_0_state == 2'd1) & (in_vec_V_last_V_0_ack_out == 1'b0)) | ((in_vec_V_last_V_0_state == 2'd3) & (in_vec_V_last_V_0_ack_out == 1'b0) & (in_vec_V_last_V_0_vld_in == 1'b1)))) begin
            in_vec_V_last_V_0_state <= 2'd1;
        end else if (((~((in_vec_V_last_V_0_vld_in == 1'b0) & (in_vec_V_last_V_0_ack_out == 1'b1)) & ~((in_vec_V_last_V_0_ack_out == 1'b0) & (in_vec_V_last_V_0_vld_in == 1'b1)) & (in_vec_V_last_V_0_state == 2'd3)) | ((in_vec_V_last_V_0_state == 2'd1) & (in_vec_V_last_V_0_ack_out == 1'b1)) | ((in_vec_V_last_V_0_state == 2'd2) & (in_vec_V_last_V_0_vld_in == 1'b1)))) begin
            in_vec_V_last_V_0_state <= 2'd3;
        end else begin
            in_vec_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_vec_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_vec_V_data_V_1_ack_out == 1'b1) & (out_vec_V_data_V_1_vld_out == 1'b1))) begin
            out_vec_V_data_V_1_sel_rd <= ~out_vec_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_vec_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((out_vec_V_data_V_1_ack_in == 1'b1) & (out_vec_V_data_V_1_vld_in == 1'b1))) begin
            out_vec_V_data_V_1_sel_wr <= ~out_vec_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_vec_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((out_vec_V_data_V_1_state == 2'd2) & (out_vec_V_data_V_1_vld_in == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_V_data_V_1_vld_in == 1'b0) & (out_vec_V_data_V_1_ack_out == 1'b1)))) begin
            out_vec_V_data_V_1_state <= 2'd2;
        end else if ((((out_vec_V_data_V_1_state == 2'd1) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0) & (out_vec_V_data_V_1_vld_in == 1'b1)))) begin
            out_vec_V_data_V_1_state <= 2'd1;
        end else if (((~((out_vec_V_data_V_1_vld_in == 1'b0) & (out_vec_V_data_V_1_ack_out == 1'b1)) & ~((out_vec_TREADY == 1'b0) & (out_vec_V_data_V_1_vld_in == 1'b1)) & (out_vec_V_data_V_1_state == 2'd3)) | ((out_vec_V_data_V_1_state == 2'd1) & (out_vec_V_data_V_1_ack_out == 1'b1)) | ((out_vec_V_data_V_1_state == 2'd2) & (out_vec_V_data_V_1_vld_in == 1'b1)))) begin
            out_vec_V_data_V_1_state <= 2'd3;
        end else begin
            out_vec_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_vec_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_vec_V_last_V_1_ack_out == 1'b1) & (out_vec_V_last_V_1_vld_out == 1'b1))) begin
            out_vec_V_last_V_1_sel_rd <= ~out_vec_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_vec_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((out_vec_V_last_V_1_ack_in == 1'b1) & (out_vec_V_last_V_1_vld_in == 1'b1))) begin
            out_vec_V_last_V_1_sel_wr <= ~out_vec_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_vec_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((out_vec_V_last_V_1_state == 2'd2) & (out_vec_V_last_V_1_vld_in == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_V_last_V_1_vld_in == 1'b0) & (out_vec_V_last_V_1_ack_out == 1'b1)))) begin
            out_vec_V_last_V_1_state <= 2'd2;
        end else if ((((out_vec_V_last_V_1_state == 2'd1) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0) & (out_vec_V_last_V_1_vld_in == 1'b1)))) begin
            out_vec_V_last_V_1_state <= 2'd1;
        end else if (((~((out_vec_V_last_V_1_vld_in == 1'b0) & (out_vec_V_last_V_1_ack_out == 1'b1)) & ~((out_vec_TREADY == 1'b0) & (out_vec_V_last_V_1_vld_in == 1'b1)) & (out_vec_V_last_V_1_state == 2'd3)) | ((out_vec_V_last_V_1_state == 2'd1) & (out_vec_V_last_V_1_ack_out == 1'b1)) | ((out_vec_V_last_V_1_state == 2'd2) & (out_vec_V_last_V_1_vld_in == 1'b1)))) begin
            out_vec_V_last_V_1_state <= 2'd3;
        end else begin
            out_vec_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        val_r_0_sel_rd <= 1'b0;
    end else begin
        if (((val_r_0_ack_out == 1'b1) & (val_r_0_vld_out == 1'b1))) begin
            val_r_0_sel_rd <= ~val_r_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        val_r_0_sel_wr <= 1'b0;
    end else begin
        if (((val_r_0_ack_in == 1'b1) & (val_r_0_vld_in == 1'b1))) begin
            val_r_0_sel_wr <= ~val_r_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        val_r_0_state <= 2'd0;
    end else begin
        if ((((val_r_0_vld_in == 1'b0) & (val_r_0_state == 2'd2)) | ((val_r_0_vld_in == 1'b0) & (val_r_0_state == 2'd3) & (val_r_0_ack_out == 1'b1)))) begin
            val_r_0_state <= 2'd2;
        end else if ((((val_r_0_ack_out == 1'b0) & (val_r_0_state == 2'd1)) | ((val_r_0_ack_out == 1'b0) & (val_r_0_state == 2'd3) & (val_r_0_vld_in == 1'b1)))) begin
            val_r_0_state <= 2'd1;
        end else if (((~((val_r_0_vld_in == 1'b0) & (val_r_0_ack_out == 1'b1)) & ~((val_r_0_ack_out == 1'b0) & (val_r_0_vld_in == 1'b1)) & (val_r_0_state == 2'd3)) | ((val_r_0_state == 2'd1) & (val_r_0_ack_out == 1'b1)) | ((val_r_0_state == 2'd2) & (val_r_0_vld_in == 1'b1)))) begin
            val_r_0_state <= 2'd3;
        end else begin
            val_r_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((out_vec_V_data_V_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_72 <= i_reg_128;
    end else if (((1'b1 == ap_CS_fsm_state1) & (val_r_0_vld_out == 1'b1))) begin
        i_0_reg_72 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state2_io) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_128 <= i_fu_93_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((in_vec_V_data_V_0_load_A == 1'b1)) begin
        in_vec_V_data_V_0_payload_A <= in_vec_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((in_vec_V_data_V_0_load_B == 1'b1)) begin
        in_vec_V_data_V_0_payload_B <= in_vec_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((out_vec_V_data_V_1_load_A == 1'b1)) begin
        out_vec_V_data_V_1_payload_A <= tmp_data_V_1_fu_108_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((out_vec_V_data_V_1_load_B == 1'b1)) begin
        out_vec_V_data_V_1_payload_B <= tmp_data_V_1_fu_108_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((out_vec_V_last_V_1_load_A == 1'b1)) begin
        out_vec_V_last_V_1_payload_A <= tmp_last_V_fu_113_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((out_vec_V_last_V_1_load_B == 1'b1)) begin
        out_vec_V_last_V_1_payload_B <= tmp_last_V_fu_113_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (val_r_0_vld_out == 1'b1))) begin
        sext_ln7_reg_120 <= sext_ln7_fu_83_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((val_r_0_load_A == 1'b1)) begin
        val_r_0_payload_A <= val_r_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((val_r_0_load_B == 1'b1)) begin
        val_r_0_payload_B <= val_r_TDATA;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        in_vec_TDATA_blk_n = in_vec_V_data_V_0_state[1'd0];
    end else begin
        in_vec_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state2_io) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0))) & (icmp_ln9_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        in_vec_V_data_V_0_ack_out = 1'b1;
    end else begin
        in_vec_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((in_vec_V_data_V_0_sel == 1'b1)) begin
        in_vec_V_data_V_0_data_out = in_vec_V_data_V_0_payload_B;
    end else begin
        in_vec_V_data_V_0_data_out = in_vec_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((~((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state2_io) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0))) & (icmp_ln9_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        in_vec_V_last_V_0_ack_out = 1'b1;
    end else begin
        in_vec_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln9_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        out_vec_TDATA_blk_n = out_vec_V_data_V_1_state[1'd1];
    end else begin
        out_vec_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((out_vec_V_data_V_1_sel == 1'b1)) begin
        out_vec_V_data_V_1_data_out = out_vec_V_data_V_1_payload_B;
    end else begin
        out_vec_V_data_V_1_data_out = out_vec_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if ((~((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state2_io) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0))) & (icmp_ln9_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_vec_V_data_V_1_vld_in = 1'b1;
    end else begin
        out_vec_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((out_vec_V_last_V_1_sel == 1'b1)) begin
        out_vec_V_last_V_1_data_out = out_vec_V_last_V_1_payload_B;
    end else begin
        out_vec_V_last_V_1_data_out = out_vec_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if ((~((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state2_io) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0))) & (icmp_ln9_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_vec_V_last_V_1_vld_in = 1'b1;
    end else begin
        out_vec_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (val_r_0_vld_out == 1'b1))) begin
        val_r_0_ack_out = 1'b1;
    end else begin
        val_r_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((val_r_0_sel == 1'b1)) begin
        val_r_0_data_out = val_r_0_payload_B;
    end else begin
        val_r_0_data_out = val_r_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        val_r_TDATA_blk_n = val_r_0_state[1'd0];
    end else begin
        val_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (val_r_0_vld_out == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state2_io) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0))) & (icmp_ln9_fu_87_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state2_io) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0))) & (icmp_ln9_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((out_vec_V_data_V_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2 = ((out_vec_V_last_V_1_state == 2'd1) | (out_vec_V_data_V_1_state == 2'd1) | ((icmp_ln9_fu_87_p2 == 1'd0) & (in_vec_V_data_V_0_vld_out == 1'b0)) | ((out_vec_V_last_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)) | ((out_vec_V_data_V_1_state == 2'd3) & (out_vec_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln9_fu_87_p2 == 1'd0) & (out_vec_V_data_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_fu_93_p2 = (i_0_reg_72 + 6'd1);

assign icmp_ln879_fu_103_p2 = ((in_vec_V_data_V_0_data_out == sext_ln7_reg_120) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_87_p2 = ((i_0_reg_72 == 6'd32) ? 1'b1 : 1'b0);

assign in_vec_TREADY = in_vec_V_last_V_0_state[1'd1];

assign in_vec_V_data_V_0_ack_in = in_vec_V_data_V_0_state[1'd1];

assign in_vec_V_data_V_0_load_A = (in_vec_V_data_V_0_state_cmp_full & ~in_vec_V_data_V_0_sel_wr);

assign in_vec_V_data_V_0_load_B = (in_vec_V_data_V_0_state_cmp_full & in_vec_V_data_V_0_sel_wr);

assign in_vec_V_data_V_0_sel = in_vec_V_data_V_0_sel_rd;

assign in_vec_V_data_V_0_state_cmp_full = ((in_vec_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign in_vec_V_data_V_0_vld_in = in_vec_TVALID;

assign in_vec_V_data_V_0_vld_out = in_vec_V_data_V_0_state[1'd0];

assign in_vec_V_last_V_0_vld_in = in_vec_TVALID;

assign out_vec_TDATA = out_vec_V_data_V_1_data_out;

assign out_vec_TLAST = out_vec_V_last_V_1_data_out;

assign out_vec_TVALID = out_vec_V_last_V_1_state[1'd0];

assign out_vec_V_data_V_1_ack_in = out_vec_V_data_V_1_state[1'd1];

assign out_vec_V_data_V_1_ack_out = out_vec_TREADY;

assign out_vec_V_data_V_1_load_A = (out_vec_V_data_V_1_state_cmp_full & ~out_vec_V_data_V_1_sel_wr);

assign out_vec_V_data_V_1_load_B = (out_vec_V_data_V_1_state_cmp_full & out_vec_V_data_V_1_sel_wr);

assign out_vec_V_data_V_1_sel = out_vec_V_data_V_1_sel_rd;

assign out_vec_V_data_V_1_state_cmp_full = ((out_vec_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_vec_V_data_V_1_vld_out = out_vec_V_data_V_1_state[1'd0];

assign out_vec_V_last_V_1_ack_in = out_vec_V_last_V_1_state[1'd1];

assign out_vec_V_last_V_1_ack_out = out_vec_TREADY;

assign out_vec_V_last_V_1_load_A = (out_vec_V_last_V_1_state_cmp_full & ~out_vec_V_last_V_1_sel_wr);

assign out_vec_V_last_V_1_load_B = (out_vec_V_last_V_1_state_cmp_full & out_vec_V_last_V_1_sel_wr);

assign out_vec_V_last_V_1_sel = out_vec_V_last_V_1_sel_rd;

assign out_vec_V_last_V_1_state_cmp_full = ((out_vec_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_vec_V_last_V_1_vld_out = out_vec_V_last_V_1_state[1'd0];

assign sext_ln7_fu_83_p1 = $signed(val_r_0_data_out);

assign tmp_data_V_1_fu_108_p1 = icmp_ln879_fu_103_p2;

assign tmp_last_V_fu_113_p2 = ((i_0_reg_72 == 6'd31) ? 1'b1 : 1'b0);

assign val_r_0_ack_in = val_r_0_state[1'd1];

assign val_r_0_load_A = (val_r_0_state_cmp_full & ~val_r_0_sel_wr);

assign val_r_0_load_B = (val_r_0_state_cmp_full & val_r_0_sel_wr);

assign val_r_0_sel = val_r_0_sel_rd;

assign val_r_0_state_cmp_full = ((val_r_0_state != 2'd1) ? 1'b1 : 1'b0);

assign val_r_0_vld_in = val_r_TVALID;

assign val_r_0_vld_out = val_r_0_state[1'd0];

assign val_r_TREADY = val_r_0_state[1'd1];

endmodule //demo_find
